### ISSUE TITLE
Spring Cloud Function Context uses JavaEE API.

### ISSUE THREAD

**Issue by ssobue** [spring-cloud/spring-cloud-function#1002]
Hi, I'm use this module through Spring Cloud Stream. Please let me know what you notice.

**Describe the bug**

"spring-cloud-function-context" modules uses JavaEE API (e.g. javax.annotation-api).

Spring blog says Spring Boot 3.0+ supports for Jakarta EE 10 with an EE 9 baseline, but this module still using JavaEE after the upgrade Spring Cloud Function 4.0+.

- https://spring.io/blog/2022/11/24/spring-boot-3-0-goes-ga

Do you have any plans to migrate to JakartaEE API?

**Sample**

- Code that uses JavaEE
  - https://github.com/spring-cloud/spring-cloud-function/blob/main/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/context/FunctionCatalog.java#L24
  - https://github.com/spring-cloud/spring-cloud-function/blob/main/spring-cloud-function-deployer/src/it/bootapp-with-javax/pom.xml#L30-L34

- Dependencies
  - https://github.com/spring-cloud/spring-cloud-function/blob/main/spring-cloud-function-context/pom.xml#L50-L59

**Comment by olegz** [comment]
This - https://github.com/spring-cloud/spring-cloud-function/blob/main/spring-cloud-function-deployer/src/it/bootapp-with-javax/pom.xml#L30-L34 is just a sample to show what types of apps are supported by the deployer. So it is not relevant to the underlying framework whet one may have in its POM

**Comment by olegz** [comment]
Also, `javax.annotation-api` is required by grpc for its code generation modules (outside of spring control)

**Comment by ssobue** [comment]
@olegz Thanks for the quick response and fix!
