### ISSUE TITLE
Remove date configuration code when configuring insensitive properties of ObjectMapper

### ISSUE THREAD

**Issue by Javed6234** [spring-cloud/spring-cloud-function#1003]
**Describe the bug**
Our ObjectMapper bean is modified by spring-cloud-function with a new deserialiser which results in string represented date defaulting to "1970-01-01" which is the same as "new Date(0)"

Here is the code that seems to be causing the issue
```
if (this.jsonMapper instanceof JacksonMapper) {
			((JacksonMapper) this.jsonMapper).configureObjectMapper(objectMapper -> {
				if (!objectMapper.isEnabled(MapperFeature.ACCEPT_CASE_INSENSITIVE_PROPERTIES)) {
					SimpleModule module = new SimpleModule();
					module.addDeserializer(Date.class, new JsonDeserializer<Date>() {
						@Override
						public Date deserialize(JsonParser jsonParser, DeserializationContext deserializationContext)
								throws IOException {
							Calendar calendar = Calendar.getInstance();
							calendar.setTimeInMillis(jsonParser.getValueAsLong());
							return calendar.getTime();
						}
					});
					objectMapper.registerModule(module);
					objectMapper.registerModule(new JodaModule());
					objectMapper.configure(MapperFeature.ACCEPT_CASE_INSENSITIVE_PROPERTIES, true);
				}
			});
		}
```

jsonParser.getValueAsLong() returns 0 as the date is not represented as a long.
I have a few questions:

1. What is the reason for overriding the date deserialisation?
2. What is the relation betweeen ACCEPT_CASE_INSENSITIVE_PROPERTIES and needing to override the deserialiser?

**Comment by dlavelle7** [comment]
+1 on this issue, our team are considering removing spring-cloud-function from our AWS lambdas due to this issue.

It would be really great if we could get a response on this, thanks :)

Also seeing a lot of dependencies being sucked in with this package, increasing our Lambda deployment size, and leaving us more prone to Lambda cold starts.

**Comment by olegz** [comment]
I honestly was trying to find a reason why I added this code, but as much as I dug I can't find a good reason, so let me fix that.

**Comment by dlavelle7** [comment]
@olegz ,

Thanks a million, that's great, let me know if you need any more info.

I'll have a look at our client side serialisation too, as Javed highlighted there is a mismatch which found this

**Comment by olegz** [comment]
I basically removed that code. It looks rogue to me and I can not find a single issue related to it. Sorry about that.

**Comment by dlavelle7** [comment]
@olegz ,
That's no problem, thanks for the speedy response!

Any idea when a new artefact will be published with this fix? Or could a beta version be published maybe?

**Comment by olegz** [comment]
Unfortunately we just had 3.2 release few days ago

**Comment by olegz** [comment]
Wait, i may have found the culprit. So re-opening it

**Comment by olegz** [comment]
Can you please provide more context as to what kind of event you are dealing with (S3, Api Gateway etc). The best way would be to provide a real JSON example of such event (mask sensitive data).

**Comment by olegz** [comment]
Actually, never mind, closing

**Comment by Javed6234** [comment]
We have a global singleton objectMapper that was being modified by the above code.
We're using that objectMapper to deserialise string represented dates from DynamoDB to java.util.Date.

Another use is for DynamodbStreamRecord events from a DynamoDB stream
using aws-lambda-java-events:3.11.0
```
{
  "Records": [
    {
      "eventID": "123",
      "eventName": "MODIFY",
      "eventVersion": "1.1",
      "eventSource": "aws:dynamodb",
      "awsRegion": "us-east-1",
      "dynamodb": {
        "Keys": {
          "Id": {
            "N": "101"
          }
        },
        "NewImage": {
          "versionName": {
            "S": "1.0"
          },
          {...
        },
        "OldImage": {
          "versionName": {
            "S": "2.0"
          },
          {...
        },
        "ApproximateCreationDateTime": 1428537600,
        "SequenceNumber": "123",
        "SizeBytes": 26,
        "StreamViewType": "NEW_AND_OLD_IMAGES"
      },
      "eventSourceARN": "arn:aws:dynamodb"
    }
  ]
}
```

If I enable ACCEPT_CASE_INSENSITIVE_PROPERTIES to prevent the Date override, I get an casting exception
```
java.lang.ClassCastException: class [B cannot be cast to class com.amazonaws.services.lambda.runtime.events.DynamodbEvent ([B is in module java.base of loader 'bootstrap'; com.amazonaws.services.lambda.runtime.events.DynamodbEvent is in unnamed module of loader lambdainternal.CustomerClassLoader @1a6c5a9e)
```

I also tried to use gson instead of jackson using `-spring.cloud.function.preferred-json-mapper: gson`
That ended up with the DynamoDB event being null.

For now, I have added `@Scope(value = ConfigurableBeanFactory.SCOPE_PROTOTYPE)` to the ObjectMapper bean so when this library calls `context.getBean(ObjectMapper.class)`, it will get a new instance of the Bean.
