### ISSUE TITLE
Validation of Input Object/Parameters using @Valid annotation

### ISSUE THREAD

**Issue by abhishekvermaa10** [spring-cloud/spring-cloud-function#1004]
In web applications, we tend to valid input object/parameter. In Spring REST we can do so by:

- mentioning validations on fields of DTO class
- using @Validated annotation on contoller class
- using @Valid annotation before input object/parameter

Like below works in Spring REST and throws org.springframework.web.bind.MethodArgumentNotValidException:
`@Validated
@RestController
public class EmployeeController {
	@Autowired
	private EmployeeService employeeService;

	@PostMapping("/addEmployee")
	public void addEmployee(@Valid @RequestBody EmployeeDTO employeeDTO) {
		employeeService.addEmployee(employeeDTO);
	}
}`

But below didn't worked in Spring Cloud Function and reaches service class code:
`
@Validated
@SpringBootApplication
public class DemoApplication {
	@Autowired
	private EmployeeService employeeService;

	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}

	@Bean
	public Consumer<EmployeeDTO> addEmployee() {
		return (@Valid EmployeeDTO employeeDTO) -> employeeService.addEmployee(employeeDTO);
	}
}`

Validation dependencies are same in both codes and EmployeeDTO looks like below:
`public class EmployeeDTO {
	private Long employeeId;
	@NotNull(message = "Name should not be null.")
	private String name;
	//getters, setters, constructors
}`

Java version: 17
Spring Boot version: 3.0.2
Spring Cloud version: 2022.0.1

**Comment by kunalvarpe** [comment]
I would like to contribute/help here. Please let me know if someone can provide little guidence to me.
