### ISSUE TITLE
3.2.9 - System.out.println in SimpleFunctionRegistry

### ISSUE THREAD

**Issue by groat-mike** [spring-cloud/spring-cloud-function#1005]
**Describe the bug**
Updated from 2021.0.5 to 2021.0.6 and found that SimpleFunctionRegistry had started sysouting something along the lines of "Invoking function: ...".

**Comment by olegz** [comment]
Yes there are two debug statements:

```
if (logger.isDebugEnabled()) {
logger.debug("Invoking function: " + this + "with input type: " + this.getInputType());
}
. . .

if (logger.isDebugEnabled() && !(input  instanceof Publisher)) {
logger.debug("Invoking function " + this);
}

```
So, adjust your logger configurations

**Comment by carolmorneau** [comment]
Hi @olegz,
The problem seems to be on v3.2.9: 
https://github.com/spring-cloud/spring-cloud-function/blob/v3.2.9/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/context/catalog/SimpleFunctionRegistry.java#L930

**Comment by groater-c1** [comment]
Thanks @olegz & @carolmorneau!

I typed the issue up on my iPad so sorry it is so scant on details, but this is good in the main branch, and maybe just needs to be backported.

**Comment by groat-mike** [comment]
I could not successfully build the 3.2.x branch with `./mvnw clean install -DskipTests` and received this error after forking and first trying to build:
> [ERROR] Failed to execute goal on project function-sample-kotlin-web: Could not resolve dependencies for project io.spring.sample:function-sample-kotlin-web:jar:1.0: The following artifacts could not be resolved: org.springframework.cloud:spring-cloud-function-kotlin:jar:3.2.9-SNAPSHOT, org.springframework.cloud:spring-cloud-function-web:jar:3.2.9-SNAPSHOT, org.springframework.cloud:spring-cloud-function-context:jar:3.2.9-SNAPSHOT: Could not find artifact org.springframework.cloud:spring-cloud-function-kotlin:jar:3.2.9-SNAPSHOT -> [Help 1]

That said, its such a small change I figured if I was missing something you would know what to do @olegz.
