### ISSUE TITLE
Kotlin functions aren't detected as expected

### ISSUE THREAD

**Issue by martypitt** [spring-cloud/spring-cloud-function#1020]
**Describe the bug**
I'm fairly certiain this is something I've done wrong, but I can't see where.

The [docs](https://cloud.spring.io/spring-cloud-function/reference/html/spring-cloud-function.html#_kotlin_lambda_support) suggest that this should work:

```kotlin
@SpringBootApplication
class FunctionalApp {

    @Bean
    fun kotlinFunction(): (String) -> String {
        return { it.toUpperCase() }
    }
}
```

However, the function isn't registered.  Hitting `/actuator/functions` returns:

```json
{
  "functionRouter": {
    "type": "FUNCTION",
    "input-type": "object",
    "output-type": "object"
  }
}
```

If I move the registration into Java, it works as expected:

```java
@Configuration
public class FunctionalConfig {
    @Bean
    public Function<String, String> uppercase() {
        return input -> input.toUpperCase();
    }
}
```
Now, hitting `/actuator/functions` returns:
```json
{
  "functionRouter": {
    "type": "FUNCTION",
    "input-type": "object",
    "output-type": "object"
  },
  "uppercase": {
    "type": "FUNCTION",
    "input-type": "string",
    "output-type": "string"
  }
}
```

**Sample**
This issue was detected as part of a broader project, which has a number of issues associated with it.  There's a reproducable example showing this example [here](https://github.com/martypitt/spring-function-bug) - specifically note that `kotlinFunction` isn't registered.

**Comment by CLD1994** [comment]
I had the same problem.
![image](https://user-images.githubusercontent.com/10044266/230738320-f9f845bb-44d8-49c6-98c5-dabcc7336946.png)
![image](https://user-images.githubusercontent.com/10044266/230738126-b05a25e5-944a-4378-aa34-c8feed34fc50.png)
![image](https://user-images.githubusercontent.com/10044266/230738335-a48ab598-5e7f-4a56-b756-e6deb478d257.png)
![image](https://user-images.githubusercontent.com/10044266/230738378-f07d139e-3fe2-4efb-8710-5f33320fe2b9.png)

**Comment by fleboulch** [comment]
I have the same issue as described here.
I'm using spring cloud stream binder rabbit v4.0.2
