### ISSUE TITLE
AWS event loop not started when running as a Container Image

### ISSUE THREAD

**Issue by martypitt** [spring-cloud/spring-cloud-function#1021]
**Describe the bug**
The goal:  
 * Build a Native Image (using Spring Boot native)
 * Deploy as a Lambda Function, using a Container Image (deployed to ECR, rather than uploaded directly)

**Issue:**

When deployed in this fashion, the Spring Boot app starts OK, but fails to collect the event from AWS, so ultimately times out and is shut down.

**Root cause:**
When deployed as a container image, there are a number of issues that prevent the `CustomRuntimeInitializer` from bootstrapping the  event loop, and the event loop from functioning:

**`isCustomRuntime` expects `_HANDLER` variable**

```java
	private boolean isCustomRuntime(Environment environment) {
		String handler = environment.getProperty("_HANDLER");
		if (StringUtils.hasText(handler)) {
```

This is designed to work when the Lambda image is uploaded, and the `handler` has been configured.  When running with container images, this isn't an option.

Also, manually setting the env variable isn't an option either, as AWS doesn't allow env varaibles beginning with an underscore.

**Requires `spring.cloud.function.web.export.enabled` disabled**

This isn't really a bug, but it wasn't obvious without reading the code that `spring.cloud.function.web.export.enabled` must be set to false.  (See `CustomRuntimeInitializer::isWebExportEnabled`)

**CustomRuntimeEventLoop required `DEFAULT_HANDLER` set:

This isn't really a bug either, but required digging into the code.

In order to get function execution working, I had to set and env var of `DEFAULT_HANDLER` with the name of the function.

### Workaround
In order to get this working, I manually configured a `CustomRuntimeEventLoop`:

```kotlin
    @Bean
    fun awsEventLoop(context: ConfigurableApplicationContext): CustomRuntimeEventLoop {
        return CustomRuntimeEventLoop(context)
    }
```

I also set the env var of `DEFAULT_HANDLER` to the name of the function I wanted to invoke within AWS.  

**Sample**
There's a working example of this issue [here](https://github.com/martypitt/spring-function-bug)

**Comment by olegz** [comment]
Actually I am not sure I follow. We have a working example  - https://github.com/spring-cloud/spring-cloud-function/tree/main/spring-cloud-function-samples/function-sample-aws-native, so obviously i can't reproduce it. 
Perhaps we're talking about different type of container image.
Anyway, please take a look and let us know the steps to reproduce it.

Also, setting `DEFAULT_HANDLER` is not really workaround, perhaps purely documented. So what solution are you really looking for ?

**Comment by martypitt** [comment]
The difference is in what gets deployed.

The demo stack you've provided is for uploading a native image with a custom runtime.
We're building docker images, deploying them to AWS's Container Registry (ECR).  The Lambda pulls the image from ECR, and runs it as a standard image.

This approach allows us to have larger image sizes - as native images via/ upload have an upper limit size of ~200MB.  (That number is from memory). Containers deployed to ECR can be ~2GB (again, from memory).

When running as a "normal" docker image, the `_HANDLER` envvar isn't set, and can't be set (AWS disallows env vars that start with an underscore).

**Comment by prasanna0586** [comment]
> The difference is in what gets deployed.
> 
> The demo stack you've provided is for uploading a native image with a custom runtime. We're building docker images, deploying them to AWS's Container Registry (ECR). The Lambda pulls the image from ECR, and runs it as a standard image.
> 
> This approach allows us to have larger image sizes - as native images via/ upload have an upper limit size of ~200MB. (That number is from memory). Containers deployed to ECR can be ~2GB (again, from memory).
> 
> When running as a "normal" docker image, the `_HANDLER` envvar isn't set, and can't be set (AWS disallows env vars that start with an underscore).

I am facing the same issue. We are also building a docker image (actually a graalvm native OCI image like this -> https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html#native-image.developing-your-first-application.buildpacks) and deploying it to ECR which the lambda pulls at runtime. I had to do what @martypitt did to make it work. It is not a bug, but feel like there should be a better way to handle this. It was also not documented (nor the example provided above helped).

This is what I did:

Setting the following environment variable (rather than setting it in the property files, I am passing it as an environment variable to the lambda function in my CDK)

spring_cloud_function_web_export_enabled: 'false'
DEFAULT_HANDLER: <name of the function> (for instance readMessageFromSQS)

FYI the function looks like this

	@Bean
	public Consumer<Message<SQSMessageEvent>> readMessageFromSQS() {
		return incomingMessage -> {
			..........
		}
	}

I also created a bean like this:

	@Bean
	public CustomRuntimeEventLoop customRuntimeEventLoop(ConfigurableApplicationContext configurableApplicationContext) {
		return new CustomRuntimeEventLoop(configurableApplicationContext);
	}
