### ISSUE TITLE
CRUD based REST API using Spring Cloud Function

### ISSUE THREAD

**Issue by hbagchi** [spring-cloud/spring-cloud-function#1025]
**Support for PUT and DELETE http method**
I want to implement a CRUD based REST API using Spring Cloud Function on AWS Lambda. I am unable to find an example or documentation that demonstrates how to implement the common http methods - POST, GET, PUT and DELETE. I did find POST and GET from the documentation but it is dissimilar to sprint Boot paradigms. e.g., using annotation to map resource URLs to methods. Can this be done in spring cloud function? 

**Obervation**
I get a 405 http error when I am calling Spring Cloud Function using PUT or DELETE http methods! I am using 'spring-cloud-starter-function-web" with spring-cloud.version as v 2021.0.6.

**Comment by olegz** [comment]
We never thought about spring-cloud-function to be used like that, but i'll accept it as feature request

**Comment by hbagchi** [comment]
Does it mean **spring-cloud-function** does not support PUT and DELETE ? Is there a workaround to support all 4 http methods?

**Comment by olegz** [comment]
So, Spring Cloud Function is not a replacement for Spring MVC, so "..using annotation to map resource URLs to methods.." is not going to happen. Another reason is to stay true to the core promise of Spring Cloud Function - keep java code clean of any abstractions that would imply any behavior (such as annotations) and instead add such behavior via Spring Boot auto-configuration.
If you need that level of granularity Spring already provides framework for that.
If you need to expose a function over HTTP. that is what we do.

However, I still believe that some of the REST semantics would be nice to have. For example exposing function over HTTP but only via GET or POST etc.

**Comment by olegz** [comment]
So I just did initial push, you can try it with the snapshot 4.0.4-SNAPSHOT.
I still have to add tests and documentation but here is the gist of it. . .
Everything works as is unless. . . you add 
```
spring.cloud.function.http.GET=uppercase;reverse;foo|bar
spring.cloud.function.http.POST=reverse
. . . PUT=..
. . . DELETE=. . .
. . .
```
Basically, function is exposed to any HTTP method unless you provide the above mapping in application.properties, YAML etc. . . at which point you are pinning a function to a particular method
