### ISSUE TITLE
JsonMessageConverter Object target type issues

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-function#1045]
If the target type is `Object,` the previous behavior is changed through [this commit.](https://github.com/spring-cloud/spring-cloud-function/commit/6969ec9720417850d11ecffd1139bec5ca1eaa44). Restore the old behavior for `Object` target types.

Without fixing this, the following tests in Spring Cloud Stream will fail:
https://github.com/spring-cloud/spring-cloud-stream/blob/main/core/spring-cloud-stream-integration-tests/src/test/java/org/springframework/cloud/stream/binder/PollableConsumerTests.java#L214

and

https://github.com/spring-cloud/spring-cloud-stream/blob/main/core/spring-cloud-stream-integration-tests/src/test/java/org/springframework/cloud/stream/binder/PollableConsumerTests.java#L246

**Comment by olegz** [comment]
Fixed with stream - https://github.com/spring-cloud/spring-cloud-stream/commit/1e5b41cfeec6b75fed8955945b952c3b270c46a7
