### ISSUE TITLE
Upgrading to Azure Function Extension V4 causes NullPointerException

### ISSUE THREAD

**Issue by jdwilkin** [spring-cloud/spring-cloud-function#1051]
I have been using spring-cloud-function-adapter-azure successfully for along time on version 3.1.3 with spring boot 2.5.5.  I recently was required by Azure to update the function extension version and upon doing so my Azure function starting throwing a NullPointerException when calling handleRequest from FunctionInvoker:

at org.springframework.cloud.function.context.FunctionType.isWrapper(FunctionType.java:102)
at org.springframework.cloud.function.context.FunctionType.isWrapper(FunctionType.java:176)
at org.springframework.cloud.function.context.FunctionType.of(FunctionType.java:111)
at org.springframework.cloud.function.context.FunctionRegistration.type(FunctionRegistration.java:122)
at org.springframework.cloud.function.context.catalog.BeanFactoryAwareFunctionRegistry.lookup(BeanFactoryAwareFunctionRegistry.java:142)
at org.springframework.cloud.function.context.FunctionCatalog.lookup(FunctionCatalog.java:42)
at org.springframework.cloud.function.adapter.azure.FunctionInvoker.handleRequest(FunctionInvoker.java:115)

I then went down a lengthy road of updating various things but ran into 2 significant roadblocks:

1) updating spring boot to 3.x requires Java 17 (I am still on 8)
2) updating to spring-cloud-function-adapter-azure to 4 required I no long extend FunctionInvoker (seemed to require Java 17), but when implementing the new Autowired approach the trigger "executes" but there are no spring boot log entries and the execution doesn't get into my code at all.

Is the answer just Azure Function Extension V4 requires updating to V4 of the adapter and that requires Java 17?

**Comment by tzolov** [comment]
Hi @jdwilkin ,

Regarding 
> updating spring boot to 3.x requires Java 17 (I am still on 8)

Starting with Spring Boot 3+, upgrading Java to 17+ is compulsory : [Spring Boot 3.0 Release Notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Release-Notes#java-17-baseline-and-java-19-support). 

> updating to spring-cloud-function-adapter-azure to 4 required I no long extend FunctionInvoker (seemed to require Java 17), but when implementing the new Autowired approach the trigger "executes" but there are no spring boot log entries and the execution doesn't get into my code at all.

The [Accessing Azure ExecutionContext](https://docs.spring.io/spring-cloud-function/docs/4.0.2-SNAPSHOT/reference/html/azure.html#_accessing_azure_executioncontext) explains how to add and use the ExecutionContext using the new (autowired) API.

> Is the answer just Azure Function Extension V4 requires updating to V4 of the adapter and that requires Java 17?

Afraid i don't understand the question, but here are the [Azure supported Java versions for each major version of the Functions runtime](https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference-java?tabs=bash%2Cconsumption#supported-versions)

Also i'm afraid i would not be able to reproduce the above exception without additional context or preferably a sample?
