### ISSUE TITLE
Documentation and sample diverge for gradle aws lambda

### ISSUE THREAD

**Issue by F43nd1r** [spring-cloud/spring-cloud-function#1055]
**Describe the bug**
The [documentation on gradle setup](https://docs.spring.io/spring-cloud-function/docs/current/reference/html/aws.html#_gradle) completely diverges from the [sample provided](https://github.com/spring-cloud/spring-cloud-function/blob/main/spring-cloud-function-samples/function-sample-aws/build.gradle). It seems like 3f8b7f1bbe054399c4547e4edcd073593abd2b90 changed the gradle file completely (to me it looks generated, and doesn't even include vital plugins, like spring-boot).

Please provide a working sample build.gradle for v4.

**Comment by olegz** [comment]
Tis has been resolved - https://github.com/spring-cloud/spring-cloud-function/blob/main/spring-cloud-function-samples/function-sample-aws/build.gradle and https://docs.spring.io/spring-cloud-function/reference/adapters/aws-intro.html
