### ISSUE TITLE
AWS Lambda layer support for spring cloud function adapter

### ISSUE THREAD

**Issue by pranavakkian-dev** [spring-cloud/spring-cloud-function#1061]
**Is your feature request related to a problem? Please describe.**
In my organisation we are using spring-cloud-function-adapter-aws to create JAR file to be used in AWS Lambda functions but with the increasing needs the size of the JAR file is increasing which is a concern. So, would to possible somehow to provide AWS Lambda layer support.

**Describe the solution you'd like**
There should be a way to import AWS Lambda layers when we deploy jar file and when we are developing in local it should take the dependency from local maven repository.

**Describe alternatives you've considered**
We have used spring-boot-thin-layout as well as maven-shade-plugin already.

**Additional context**
NA

**Comment by msailes** [comment]
Hi @pranavakkian-dev,

Adding spring-cloud-function-adapter-aws or any other dependency to a layer would not help here. 

From the [AWS documentation](https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html)

**Deployment package size**
50 MB (zipped, for direct upload)
250 MB (unzipped)
This quota applies to all the files you upload, including layers and custom runtimes.
3 MB (console editor)

If your code is above the 250MB limit, you can deploy your function as a container image.

**Comment by olegz** [comment]
Closing due to resolution provided by AWS resource
