### ISSUE TITLE
Function startup logs

### ISSUE THREAD

**Issue by ffarinha-msft** [spring-cloud/spring-cloud-function#1070]
**Is your feature request related to a problem? Please describe.**

On Azure Function App, the first time a function runs there will be some startup logs coming from "org.springframework.cloud.function.utils.FunctionClassUtils" to the STDOUT which will be captured by the Application Insights Agent running on the same (when setting APPLICATIONINSIGHTS_ENABLE_AGENT is turned on)

Example:
![image](https://github.com/spring-cloud/spring-cloud-function/assets/92974977/d5464cc0-ddb7-4d90-93f2-ad2bd2bfbe08)

**Describe the solution you'd like**
I  would like to have a flag that allowed me to turn of information level logs from org.springframework.cloud.function.utils.FunctionClassUtils. If there is such a flag I haven't been able to find it.

**Describe alternatives you've considered**
I was able to turn of information level logs from org.springframework.boot, by adding the following properties to my application.properties file:

spring.main.banner-mode=off
logging.level.org.springframework=WARN
spring.main.log-startup-info=OFF

Example of the log I turned off
![image](https://github.com/spring-cloud/spring-cloud-function/assets/92974977/b3f0871f-54d6-4ea3-9f5c-c4006a6a1859)

But I tried adding all the below properties to my application.properties file without any luck:

logging.level.org.springframework.cloud.config=WARN
logging.level.org.springframework.cloud.function=WARN
logging.level.org.springframework.cloud=WARN
logging.level.org.springframework.cloud.function.utils.FunctionClassUtils=WARN
logging.level.org.springframework.cloud.function.utils=WARN
logging.level.root=OFF

I also tried to use the preview feature of Application Insights to filter the logs but I found that it will also turn off my custom logging https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-sampling-overrides#how-it-works

**Comment by ffarinha-msft** [comment]
Hi @tzolov 

Thank you for coming back to me.

The issue described can be reproduce with a simple hello world spring function has this examples:

[https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/getting-started-with-spring-cloud-function-in-azure](url)

[https://github.com/Azure-Samples/hello-spring-function-azure](url)

Once you have your simple hello world spring function application you deploy the code to a Linux Azure Function App (I did not test on Windows).

Then you trigger the function execution and you will notice that the first invocation will have the initialization logs I mentioned:
![image](https://github.com/spring-cloud/spring-cloud-function/assets/92974977/3a7d58f0-e163-4c83-93ef-14d4581f71dc)

![image](https://github.com/spring-cloud/spring-cloud-function/assets/92974977/2591fc0d-54d8-49d6-abc1-116bb4cba29b)

![image](https://github.com/spring-cloud/spring-cloud-function/assets/92974977/1915d440-0945-4c03-b410-6db56ad0f375)

**Comment by tzolov** [comment]
@ffarinha-msft ,

Thank you for your update, but unfortunately I'm still not able to reach the portal pages you've shared above. 
As you can see below i have the `APPLICATIONINSIGHTS_ENABLE_AGENT` set to `true` the App Insights seems enabled but i can not see the `Developer/Monitor` menu options.
I'm not Azure portal savvy. Do i need a special plan?

![Screenshot 2023-10-30 at 15 06 05_anonymized](https://github.com/spring-cloud/spring-cloud-function/assets/1351573/5f464b99-73f4-4cb6-ab10-d018d44beedc)
![Screenshot 2023-10-30 at 15 03 05_anonymized](https://github.com/spring-cloud/spring-cloud-function/assets/1351573/24cec36c-c554-4957-925a-6164954060af)
![Screenshot 2023-10-30 at 15 04 26_anonymized](https://github.com/spring-cloud/spring-cloud-function/assets/1351573/b05bc616-1441-4f0b-9a18-3b983507b66c)

**Comment by ffarinha-msft** [comment]
Hi @tzolov 

Thank you for coming back.

It looks like you were almost there (you don't need any special plan) :)

You already accessed Application Insights resource from the screen shot you shared. Once there you need to click on "Tansaction Search":

![image](https://github.com/spring-cloud/spring-cloud-function/assets/92974977/0da80727-d3e7-4050-8fa3-3e94ec4db502)

Then you search for the log message we are after.
**Note** the log only happens after on the first function execution so you might need to restart the function app and then trigger the function again. Also important to note that the logs on App Insights my take a couple of minutes to show up.

![image](https://user-images.githubusercontent.com/92974977/271222795-33ed7968-bd10-409e-bfc6-0a3d2a8cf923.png)

You then double click on one of those results and a blade like below will open where you can then see more details about each of the logs:
![image](https://user-images.githubusercontent.com/92974977/271223700-2cab9274-5566-4c7a-ba44-14e5ae7207dc.png)
