### ISSUE TITLE
Getter for message field in FunctionContext class

### ISSUE THREAD

**Issue by rogelio-o** [spring-cloud/spring-cloud-function#1071]
We were customizing the span name of traces using a customizer that is not available anymore due to the Sleuth deprecation. Now, we are migrating to SB 3.0, and we want to do the same customization by using `FunctionObservationConvention`.

In the method `getContextualName` of a class implementing `FunctionObservationConvention`, we are returning the contextual name of the observation as `send _MessagePayloadClassName_ to StreamBridge`. The problem is that, even having the message in the `FunctionContext`, we cannot access it. So, we cannot get the payload class name to generate the custom span name.

Is it possible to have a getter accessor to the field `message` in the class `FunctionContext`?

**Comment by olegz** [comment]
Resolved
