### ISSUE TITLE
Simple function registry is not using conversion hint to de-serialize message to input type provided in the cloud function 

### ISSUE THREAD

**Issue by sudhu678** [spring-cloud/spring-cloud-function#1075]
**Describe the bug**
The simple function registry checks whether a conversion hint is required in order to invoke the respective message converter. For the below input type, conversion happens without type. By using the default JSON converter, the message is deserialized to LinkedHashMap instead of the Java class for Event which is a generic type and Account list type. 

```
Consumer<org.springframework.messaging.Message<Message<Event<List<Account>>>>>
```
Why don't you consider actualType for conversion if it has valid input here?

![image](https://github.com/spring-cloud/spring-cloud-function/assets/28265483/e5516348-cede-4c2c-bf00-75d05bbef2d1)

**Sample**
If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

**Comment by olegz** [comment]
I am not sure what you are asking. - _"If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it."_

That is what we are typically asking developers to provide. 

Regardless, I just verified that conversion hint is indeed working and we do have a test case for it - https://github.com/spring-cloud/spring-cloud-function/blob/main/spring-cloud-function-context/src/test/java/org/springframework/cloud/function/userissues/UserIssuesTests.java#L61C19-L61C19

**Comment by sudhu678** [comment]
Could you please confirm post-conversion data type is the actual Java class and not linkedhashmap? In my test, both event and list of account is returned as linkedhashmap instead of the respective java class

**Comment by olegz** [comment]
Yes, i cam confirm as the test validates against the POJO
```
public Function<List<Product>, Integer> consumer() {
	return v -> {
		assertThat(v.get(0).getName()).isEqualTo("julien");
		assertThat(v.get(1).getName()).isEqualTo("ricky");
		assertThat(v.get(2).getName()).isEqualTo("bubbles");
		return v.size();
	};
}
```

**Comment by olegz** [comment]
Perhaps you can provide a small sample that reproduces the issue so we can tale a look. just create one and oush iyt to github somewhere

**Comment by sudhu678** [comment]
If you carefully observe my code input has Spring message class wrapped by our custom message (generic type) followed by Event and then List<Unit>

**Custom message class:**
public class Message<T> {
   private T body;
}

**Event Class:**
public class Event<T>{
  private T payload;
}

**Unit class**
public class Unit {
   private name;
}

After consuming the message, we expect the message to be de-serialized to the below composite type
![image](https://github.com/spring-cloud/spring-cloud-function/assets/28265483/46c219f1-b87d-419b-878f-e8c72b9c6af5)

However, the event and list of units are de-serialized as a linked hashmap.

The body is deserialized as a linked hashmap instead of the event Java class
![image](https://github.com/spring-cloud/spring-cloud-function/assets/28265483/32ebb47b-57d2-47ab-ba92-944535a6fcc0)

Similarly, units are de-serialized as linked hashmap instead of the unit java class
![image](https://github.com/spring-cloud/spring-cloud-function/assets/28265483/ddfd7482-fd99-46f6-b1af-6475880e49da)


springBootVersion=2.7.12

**Comment by sudhu678** [comment]
All of our existing microservices use this format. We don't want to take a big undertaking now. If the below method returns true then conversion works fine using the actual type. If the actual type is a Spring generic message, the code won't use a full hierarchy of type conversion.

![image](https://github.com/spring-cloud/spring-cloud-function/assets/28265483/5a3aa45f-0893-45c7-af36-d5f4c6829d7c)
