### ISSUE TITLE
Global Exception handling in spring cloud function

### ISSUE THREAD

**Issue by upliftdev** [spring-cloud/spring-cloud-function#1080]
**Describe the bug**
Iam trying to use Spring cloud function as lamda authorizer as well as regular function. I don't see any documentation around how global exceptions are handled with spring cloud function implementation

**Sample**
For eg I simulated an error where i get a below errorType and stack trace which leaks all the implementation details around what framework is used to implement the lamda. How do I implement a global error handling to send a generic error?
```
< HTTP/1.1 200 OK
< Date: Fri, 13 Oct 2023 06:55:54 GMT
< Content-Type: application/json
< Content-Length: 1391
< x-amzn-RequestId: 92dc8aa7-8fb0-47d0-a88b-17d706801603
< x-amz-apigw-id: Mul-hFtTBcwFUwg=
< X-Amzn-Trace-Id: Root=1-6528e9f6-7080c33030ed3adb1c8919d0;Sampled=0;lineage=ca018847:0|8396ee64:0
< Cache-Control: proxy-revalidate
< Proxy-Connection: Keep-Alive
< Connection: Keep-Alive
< 
{"errorMessage":"class [B cannot be cast to class com.example.demofunction.model.KeyCreationRequest ([B is in module java.base of loader 'bootstrap'; com.example.demofunction.model.KeyCreationRequest is in unnamed module of loader com.amazonaws.services.lambda.runtime.api.client.CustomerClassLoader @1ddc4ec2)","errorType":"java.lang.ClassCastException","stackTrace":["org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.invokeFunctionAndEnrichResultIfNecessary(SimpleFunctionRegistry.java:943)","org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.invokeFunction(SimpleFunctionRegistry.java:889)","org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.doApply(SimpleFunctionRegistry.java:734)","org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(SimpleFunctionRegistry.java:577)","org.springframework.cloud.function.adapter.a* Connection #0 to host 127.0.0.1 left intact
ws.FunctionInvoker.handleRequest(FunctionInvoker.java:91)","java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)","java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)","java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)","java.base/java.lang.reflect.Method.invoke(Unknown Source)"]}Note: Unnecessary use of -X or --request, POST is already inferred.
```

**Comment by olegz** [comment]
I am not sure exactly what you are asking. Spring Cloud Function simply provides a better implementation model where instead of implementing AWS specific `StreamHandlers` and be aware of AWS API, you can write a simple Java function. 

The error you are showing appears to be a standard AWS API Gateway response, so I assume the error mappings should be done by various mechanisms provided by AWS (not S-c-function).

Also, what version of s-c-function you are using?

**Comment by upliftdev** [comment]
Thanks @olegz for responding. Iam using scf 4.0.5

When Iam creating a function as above, Iam not able to control what response goes back incase if input request is not parsable. I don't want my public api getting full error stack trace rather i want to customize my error response 

@Bean
public Function<String, KeyCreationResponse> createKmsAsyncKeyPair(KeyGenerator keyGenerator) {
	return keyGenerator::generateKeys;
}


Iam looking for something like ExceptionHandler  where can mask traces and send standard error like Problemdetail back to API gateway.

**Comment by upliftdev** [comment]
I want the error message that is sent to client as  "Bad Request" instead of the full trace. How can i have a error handler in scf to customize the error response ?

{"errorMessage":"class [B cannot be cast to class com.example.demofunction.model.KeyCreationRequest ([B is in module java.base of loader 'bootstrap'; com.example.demofunction.model.KeyCreationRequest is in unnamed module of loader com.amazonaws.services.lambda.runtime.api.client.CustomerClassLoader @1ddc4ec2)","errorType":"java.lang.ClassCastException","stackTrace":["org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.invokeFunctionAndEnrichResultIfNecessary(SimpleFunctionRegistry.java:943)","org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.invokeFunction(SimpleFunctionRegistry.java:889)","org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.doApply(SimpleFunctionRegistry.java:734)","org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(SimpleFunctionRegistry.java:577)","org.springframework.cloud.function.adapter.a* Connection #0 to host 127.0.0.1 left intact
ws.FunctionInvoker.handleRequest(FunctionInvoker.java:91)","java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)","java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)","java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)","java.base/java.lang.reflect.Method.invoke(Unknown Source)"]"

**Comment by olegz** [comment]
The exception response is not create by Spring Cloud Function. It is the AWS feature. If we do something and don't re-throw the exception you'll end up with 200/OK. . 

I am looking to see what if anything we can do on the the framework side, but I was wondering if you looked at AWS mechanisms how to control API Gateway errors?

**Comment by olegz** [comment]
Closing it due to lack of follow up from the original user

**Comment by TorosyanV** [comment]
Can we reopen it? because have the same issue. 
And I don't think it has something to do with AWS. If an exception is not handled it

**Comment by TorosyanV** [comment]
@upliftdev this is how you can make it work.

```java
public class AwsLambdaErrorMessageConverter {
    public static Message<StatusResponse> convertToError(Exception e, Message<?> request) {
        return MessageBuilder.withPayload(StatusResponse.error(e.getMessage()))
                .setHeader("statusCode", HttpStatus.INTERNAL_SERVER_ERROR.value())
                .build();
    }
}

@Bean
    public Function<Message<String>, Message<?>> handle() {
        return request -> {
            try {
                return MessageBuilder.withPayload(StatusResponse.ok("Success")).build();
            } catch (Exception e) {
                return AwsLambdaErrorMessageConverter.convertToError(e, request);
            }
        };
    }


public class StatusResponse {

    private final Status status;

    private final String message;


    private StatusResponse(final Status status, final String message) {
        this.status = status;
        this.message = message;
    }

    public static StatusResponse ok(String message) {
        return new StatusResponse(Status.OK, message);
    }

    public static StatusResponse error(String message) {
        return new StatusResponse(Status.ERROR, message);
    }

    @JsonProperty
    public Status getStatus() {
        return status;
    }

    @JsonProperty
    public String getMessage() {
        return message;
    }

    enum Status {
        OK, ERROR;

        @JsonValue
        public String toValue() {
            return this.toString().toLowerCase(Locale.getDefault());
        }
    }
}
```

**Comment by GustavoOS** [comment]
> [@upliftdev](https://github.com/upliftdev) this is how you can make it work.
> 
> public class AwsLambdaErrorMessageConverter {
>     public static Message<StatusResponse> convertToError(Exception e, Message<?> request) {
>         return MessageBuilder.withPayload(StatusResponse.error(e.getMessage()))
>                 .setHeader("statusCode", HttpStatus.INTERNAL_SERVER_ERROR.value())
>                 .build();
>     }
> }
> 
> @Bean
>     public Function<Message<String>, Message<?>> handle() {
>         return request -> {
>             try {
>                 return MessageBuilder.withPayload(StatusResponse.ok("Success")).build();
>             } catch (Exception e) {
>                 return AwsLambdaErrorMessageConverter.convertToError(e, request);
>             }
>         };
>     }
> 
> 
> public class StatusResponse {
> 
>     private final Status status;
> 
>     private final String message;
> 
> 
>     private StatusResponse(final Status status, final String message) {
>         this.status = status;
>         this.message = message;
>     }
> 
>     public static StatusResponse ok(String message) {
>         return new StatusResponse(Status.OK, message);
>     }
> 
>     public static StatusResponse error(String message) {
>         return new StatusResponse(Status.ERROR, message);
>     }
> 
>     @JsonProperty
>     public Status getStatus() {
>         return status;
>     }
> 
>     @JsonProperty
>     public String getMessage() {
>         return message;
>     }
> 
>     enum Status {
>         OK, ERROR;
> 
>         @JsonValue
>         public String toValue() {
>             return this.toString().toLowerCase(Locale.getDefault());
>         }
>     }
> }
 The problem with this solution is that the status code is not propagated itself (returns 200)
