### ISSUE TITLE
Support of Multiple Function Location Jars

### ISSUE THREAD

**Issue by anoop-awasthi** [spring-cloud/spring-cloud-function#1090]
We have a use case where Indivisual functions are developed in their seperate Jars due to Isolation reasons and we want to deploy these multiple functions combined in a single deployer. 
Single Deployer should maintain child application contexts and loads the corresponding function jar.

Ex- 
```
spring.cloud.function.location=target/upper-1.0.0.jar;target/lower-1.0.0.jar
spring.cloud.function.definition=upperFunction;lowerFunction
```

Similar Issue mentioned in 
https://github.com/spring-cloud/spring-cloud-function/issues/564

**Comment by cybdrachir** [comment]
We have the same use case. Is there any plan to add this feature?

**Comment by olegz** [comment]
We have spring-cloud-function-deployer module that doers exactly what you are asking for and in fact was designed for that. Here is the test from it https://github.com/spring-cloud/spring-cloud-function/blob/main/spring-cloud-function-deployer/src/test/java/org/springframework/cloud/function/deployer/FunctionDeployerTests.java.

Also, here are the docs for it https://docs.spring.io/spring-cloud-function/reference/spring-cloud-function/deploying-a-packaged.html

**Comment by olegz** [comment]
Is this about allowing multiple locations instead of a single JAR?

**Comment by olegz** [comment]
Any updates on this?
