### ISSUE TITLE
gcp adapter | support for CloudFunctions gen2

### ISSUE THREAD

**Issue by sebastiankonieczek** [spring-cloud/spring-cloud-function#1092]
**Is your feature request related to a problem? Please describe.**
GCP CloudFunctions gen2 use CloudEvents as event format when creating a trigger function.
With spring-cloud-function-adapter-gcp only the old RawBackgroundFunction interface is supported.
This is really annoying as one needs to stick to GCP CloudFunction gen1

See: [https://cloud.google.com/functions/docs/concepts/version-comparison](https://cloud.google.com/functions/docs/concepts/version-comparison)

**Describe the solution you'd like**
The FunktionInvoker class should also implement the CloudEventsFunction interface from com.google.cloud.functions:functions-framework-api and support conversion of the payload to CloudEvents.

**Comment by vlakkamuber** [comment]
Any update on this issue?
