### ISSUE TITLE
Simplify Gradle packaging configuration for AWS

### ISSUE THREAD

**Issue by olegz** [spring-cloud/spring-cloud-function#1108]
This effectively means we need a custom gradle plugin

**Comment by webcane** [comment]
> Plugin [id: 'org.springframework.cloud.function.aws-lambda.packaging', version: '1.0.0'] was not found in any of the following sources:
> - Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
> - Plugin Repositories (could not resolve plugin artifact 'org.springframework.cloud.function.aws-lambda.packaging:org.springframework.cloud.function.aws-lambda.packaging.gradle.plugin:1.0.0')
>   Searched in the following repositories:
>     MavenRepo
>     MavenLocal(file:/Users/niedrem/.m2/repository/)
>     maven(https://repo.spring.io/milestone)
>     Gradle Central Plugin Repository
>

**Comment by awscamille** [comment]
Yeah I am getting the same issue - looks like the plugin is not on the Gradle repository anymore.

**Comment by beccagaspard** [comment]
Hi @olegz - curious about the status of this issue.  I see it was merged in to the 4.1 releases, but doesn't look like the plugin is published yet.  This seems like a great feature and I'm eager to try it out! 🤓 Thanks!

**Comment by erikpragt-connectid** [comment]
Hi @olegz , I'm running into the same issue. Thanks for your work on this, but is there an eta for this package to be published? Cheers!

**Comment by jamesmbowler** [comment]
Any updates on this? 🙏

**Comment by jamesward** [comment]
Ping. This plugin is still MIA.
