### ISSUE TITLE
NoSuchBeanDefinitionException: No qualifying bean of type FunctionCatalog available

### ISSUE THREAD

**Issue by jcabreroca** [spring-cloud/spring-cloud-function#1115]
**Describe the bug**
I'm getting this message when I'm trying to invoke my lambda:

> org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.cloud.function.context.FunctionCatalog' available

I've also tried to launch using `mvn spring-boot:run` goal. Then I'm getting:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Web application could not be started as there was no org.springframework.boot.web.servlet.server.ServletWebServerFactory bean defined in the context.

Action:

Check your application's dependencies for a supported servlet web server.
Check the configured web application type.
```

Any ideas?

**Sample**
I've created a [public repo here](https://gitlab.com/jeusdit/aws-lambda-spring-function-sample).

**Comment by jeusdi** [comment]
Please, close. It was absolutly my fault.

**Comment by olegz** [comment]
Missing @SpringBootApplication ;)
No problem, all is good
