### ISSUE TITLE
spring-cloud-function-adapter-azure-web always returns 200

### ISSUE THREAD

**Issue by cpiment** [spring-cloud/spring-cloud-function#1126]
**Describe the bug**
The Azure Web Adapter always returns response code 200, even if the method it calls from the Spring Web application returns any other response code.

Also I have detected that if you call a path that doesn't exist in the underlying Controllers, you also get a 200 response code and no errors in logs.

**Sample**
https://github.com/spring-cloud/spring-cloud-function/blob/118c223be1de0f3429942bedb592e714d0ea14c0/spring-cloud-function-adapters/spring-cloud-function-adapter-azure-web/src/main/java/org/springframework/cloud/function/adapter/azure/web/AzureWebProxyInvoker.java#L130

Response code should be built using the response code from the underlying `httpResponse`, the same way the response body and response headers are generated.

**Comment by mixaverros88** [comment]
Also I faced the same issue.
The response status should be 400.

![Screenshot_15](https://github.com/user-attachments/assets/bab845f8-6e24-4ca2-978e-e706ee850838)

**Comment by cpiment** [comment]
There are several issues regarding the Azure Function Adapter which have gone stale.

**Comment by cpiment** [comment]
This issue is not completed AFAIK. The code always return 200

**Comment by alxmrtn-kroger** [comment]
Also experiencing this - is there any workaround?

**Comment by cpiment** [comment]
@olegz sorry for tagging you, but do you know how can we reopen the issue since it isn't fixed?
