### ISSUE TITLE
Run lambda from ECR image

### ISSUE THREAD

**Issue by jeusdi** [spring-cloud/spring-cloud-function#1133]
I've been able to launch my lambda. I created and update it using jar file straightforwardly.

My jar file is generated at: `./target/frontoffice-apigateway-0.0.1-SNAPSHOT-aws.jar`.

However, I need to change the way I uploading code. I mean, I first need to create a docker image and push it on my ECR repository.

Here my `Containerfile`:

```Docker
FROM public.ecr.aws/lambda/java:21

# Copy function code and runtime dependencies from Maven layout
COPY ./target/frontoffice-apigateway-0.0.1-SNAPSHOT-aws.jar ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest"]
```

And it's succesfully pushed on ECR repository.

I've created a new lambda attaching my recently pushed image, but I'm getting when it starts:

```json
{
  "errorMessage": "Class not found: org.springframework.cloud.function.adapter.aws.FunctionInvoker",
  "errorType": "java.lang.ClassNotFoundException"
}
```

I've also played creating a new lambda attaching straightforwardly the jar file using aws console and code runs.

Any ideas?

**Comment by olegz** [comment]
This is not related to s-c-function. This question is more related to AWS, and its infrastructure. In other words there is nothing in s-c-function code that can address your question, so i'll close the issue
