### ISSUE TITLE
use-native-decoding=true does not work when combined with function composition

### ISSUE THREAD

**Issue by carolmorneau** [spring-cloud/spring-cloud-function#1144]
**Description**
`use-native-decoding=true` works as expected when there is no function composition. The `skipInputConversion` flag in [SimpleFunctionRegistry](https://github.com/spring-cloud/spring-cloud-function/blob/main/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/context/catalog/SimpleFunctionRegistry.java#L1105) is properly set and payload conversion is not attempted.

However, if function composition is used in combination with `use-native-encoding=true`, the `skipInputConversion` flag is always `false` and payload conversion is attempted.   

**To Reproduce**
Using this [sample project](https://github.com/carolmorneau/function-composition-rabbit/tree/master) which is based on the [function-composition-rabbit](https://github.com/spring-cloud/spring-cloud-stream-samples/tree/main/multi-functions-samples/function-composition-rabbit) sample

* Run the sample with the `issue2945` profile
* Send some data to the RabbitMQ exchange (at least 3 messages since batch-size=3)
* Notice that an exception is thrown from `JsonMessageConverter`; however, we would expect `skipInputConversion=true` and converters to not be called. 

**Expected behavior**

I would expect the framework to not attempt payload conversion when `use-native-decoding=true`

**Comment by olegz** [comment]
We need to ensure that if `setSkipInputConversion` is set on a function then even if this function is composed from multiple functions the settings propagates to all of them

**Comment by carolmorneau** [comment]
Thank you @olegz 
It was not my main focus but I believe the same issue takes place for the producer property `use-native-encoding=true`. 

Thank you
