### ISSUE TITLE
Refine KotlinDetector.isKotlinType documentation for Kotlin 2.x lambdas

### ISSUE THREAD

**Issue by antechrestos** [spring-cloud/spring-cloud-function#1147]
Using the [spring cloud stream with reactive](https://docs.spring.io/spring-cloud-stream/reference/spring-cloud-stream/producing-and-consuming-messages.html#reactive-functions-support)  used to work well by instanciating kotlin function  as follows

```kotlin
@Configuration(proxyBeanMethods = false)
class MessageConfiguration {

   @Bean
   fun myMessageConsumer() = { rawMessagesFlux ->
            rawMessagesFlux
                .flatMap { // ... }
                .then()
   }
```

Moving to **kotlin 2.0** fails as generated bean class returns `false` when passing it to `KotlinDetector.isKotlinType`. Hence starting of spring cloud stream module fails as `KotlinFunctionWrapper` is not put and the `Configuration` expects java `Function`,  `Consumer` or `Supplier` ...

I also made a [sample repo](https://github.com/antechrestos/spring-function-kotlin-2.0-bug)

@sdeleuze  digged and found that maybe somehting can be done on your side, or at least be documented (see [issue on spring framework repo](https://github.com/spring-projects/spring-framework/issues/32905) ).

Thanks!

**Comment by olegz** [comment]
This has been addressed. Can you please re-test it with 4.1.3-SNAPSHOT?

**Comment by antechrestos** [comment]
@olegz I can confirm that with `4.1.3-SNAPSHOT` my application starts well :+1:
