### ISSUE TITLE
ContextFunctionCatalogAutoConfiguration is doing component scan at the wrong phase

### ISSUE THREAD

**Issue by snicoll** [spring-cloud/spring-cloud-function#1149]
**Describe the bug**
`org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration` is an auto-configuration that should back off if a `FunctionCatalog` bean is present. `PlainFunctionScanConfiguration` is doing component scan, which is a `PARSE_CONFIGURATION` business. You can't scan for additional beans that should happen early and prevent that from happening if a bean is present.

**Sample**
This will fail in Spring Framework `6.2.0-M1` onwards as we've tighten up that rule, see https://github.com/spring-projects/spring-framework/issues/23206. As such, I am expecting the tests of this project to fail when building against Spring Framework 6.2.

**Comment by olegz** [comment]
I am not sure I fully understand the issue. The `FunctionCatalog` is created by `ContextFunctionCatalogAutoConfiguration`, so it will always be present. So I am not sure what do you mean when you say _back off if a `FunctionCatalog` bean is present_.

What am I missing?

**Comment by snicoll** [comment]
[This](https://github.com/spring-cloud/spring-cloud-function/blob/8b66fd296e72e8c0f1ed5df0711da5ea75527cb8/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/context/config/ContextFunctionCatalogAutoConfiguration.java#L86)
