### ISSUE TITLE
Provide ability to incorporate the entire input as a Message's payload (no parsing) for AWS

### ISSUE THREAD

**Issue by M0rious** [spring-cloud/spring-cloud-function#1154]
**Describe the bug**
We are using SpringCloudFunctions on AWS for Lambdas.
The messages send to the Lambdas contain a property "payload".
This worked fine up until spring-cloud-function-adapter-aws@4.0.6.
With the current version 4.1.2  the message does not reach the lambda implementation correctly.
Only the "payload" property gets passed to the function-code

**Sample**
Deploy a SCF-Lambda to AWS or Localstack and log the input:

```
@SpringBootApplication
@Slf4j
public class SampleLambda {

  @Bean
  public Function<Message<String>, String> transformMessage() {
    return input -> {
        log.info("Debug: {}", input.getPayload());
      return input.getPayload();
    };
  }
}
```
Sample-Input:
```
{
  "a": "b",
  "payload": {
    "c": "d"
  }
} 
```

Output:

`"Debug: {\"c\":\"d\"},.."`

**Comment by M0rious** [comment]
The lambda is triggered by a step function that builds a json object as input for the lambda.
Why would we pass this as a header to the lambda?
Here an extended examplee:
```
{
  "someProperty": "someValue",
  "payload": {
    "otherProperty": "otherValue"
  }
} 
```

Would log:
`"Debug: {\"otherProperty\":\"otherValue\"},.."`
Everything outside of the "payload" property of the message we build for the lambda does not reach our code.

**Comment by mrjv** [comment]
We are getting a similar error after upgrading to Spring Cloud Function 4.1.1. (Or actually same as #1135, but after upgrading to 4.1.2 I expect the same as above). Same scenario as @M0rious: our lambda input request has a json field called "payload" that is not expected any special handling on an AWS Lambda adapter level.

The special handling of the "payload" field seems to have been introduced by the following commit, although I don't understand how the change is related to #1086 as mentioned in the commit message:
https://github.com/spring-cloud/spring-cloud-function/commit/8a93e10a0e95dd26d3f111b38a1e9be5fd42a5c2#diff-c3541839d4b70d7bf7b3c116f62949cdab0fd8923e1ccf57a6788e6411d67d87

@olegz What was the original reason for adding special handling of requests having a "payload" field? Ideally there would be some way to opt in or opt out from this behavior to avoid breaking changes to existing Lambda functions.

**Comment by olegz** [comment]
Don't get me wrong, we can fix it, just trying to understand  your expectation and what I read is that given that Spring `Message` has a distinct `payload` field, you would expect/like your `payload` to go there and the rest as `headers`, correct?

**Comment by M0rious** [comment]
> Don't get me wrong, we can fix it, just trying to understand your expectation and what I read is that given that Spring `Message` has a distinct `payload` field, you would expect/like your `payload` to go there and the rest as `headers`, correct?

Yes - if we send a JSON-Message to the Lambda we expect the whole message to be in the payload field - regardless of the fields contained in the message we send.

We use Message<String> as Input for the Lambda so we can call getHeaders to use e.g. the 'aws-context' header for logging.

**Comment by mrjv** [comment]
We are still looking for a way to opt-out from this behavior. Our use-case is the same as described by @M0rious above. We have a Lambda function with the following type of payload:
```
{
  "someProperty": "someValue",
  "payload": {
    "otherProperty": "otherValue"
  }
} 
```
and need access to the full payload (including "someProperty") instead of just the nested payload field.

It appears that the field extraction is done in AWSLambdaUtils.java:
https://github.com/spring-cloud/spring-cloud-function/blob/1fc0fe36ebcc6fa4b2f284d85fae7c1cb5eb4e42/spring-cloud-function-adapters/spring-cloud-function-adapter-aws/src/main/java/org/springframework/cloud/function/adapter/aws/AWSLambdaUtils.java#L127-L130

On a high-level, we are looking for something like the following:
```java
 MessageBuilder builder = MessageBuilder 
 		.withPayload(SOME_PAYLOAD_EXTRACTION_FLAG && structMessage instanceof Map msg && msg.containsKey("payload") 
 				? (msg.get("payload")) 
 				: payload); 
```
Where we would set `SOME_PAYLOAD_EXTRACTION_FLAG` to false using a configuration or similar.

@olegz Could you please reopen this issue?
