### ISSUE TITLE
4.1.2 Broken input logging

### ISSUE THREAD

**Issue by franczakr** [spring-cloud/spring-cloud-function#1157]
**Describe the bug**
After switching from 4.1.1 to 4.1.2 AWSLambdaUtils divides input JSON into multiple log entries preventing AWS Cloudwatch from formatting it properly and causing a huge amount of logs. 
In 4.1.1 it logged the entire input in a single log entry and AWS CloudWatch formatted and colored it, while now we get one JSON line per log entry.

https://github.com/spring-cloud/spring-cloud-function/blob/f0ae10ff841ef3b28198ae1cf2f9677e2c99ffb4/spring-cloud-function-adapters/spring-cloud-function-adapter-aws/src/main/java/org/springframework/cloud/function/adapter/aws/AWSLambdaUtils.java#L116

It's probably caused by SerializationFeature.INDENT_OUTPUT in the new JsonMasker class.

https://github.com/spring-cloud/spring-cloud-function/blob/f0ae10ff841ef3b28198ae1cf2f9677e2c99ffb4/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/utils/JsonMasker.java#L56

Can you remove this feature / give an option to disable it or/and at least skip processing by JsonMasker when keysToMask is empty?

**Sample**
Any AWS Lambda application that accepts JSON input

**Comment by olegz** [comment]
Sorry about that, it was done primarily to test and visualize but i see your point
