### ISSUE TITLE
Broken documentation links

### ISSUE THREAD

**Issue by breun** [spring-cloud/spring-cloud-function#1166]
The links on https://spring.io/projects/spring-cloud-function#learn are broken:

* 4.1.3 links to https://docs.spring.io/spring-cloud-function/docs/current/reference/html/, which shows the documentation for version 4.0.5.
* 4.1.4-SNAPSHOT links to https://docs.spring.io/spring-cloud-function/docs/4.1.4-SNAPSHOT/reference/html/, which returns 404 Not Found.

The correct link format seems to be https://docs.spring.io/spring-cloud-function/reference/${version}, because these work:

* 4.1.3: https://docs.spring.io/spring-cloud-function/reference/4.1.3
* 4.1.4-SNAPSHOT: https://docs.spring.io/spring-cloud-function/reference/4.1.4-SNAPSHOT

**Comment by ryanjbaxter** [comment]
Should be fixed
