### ISSUE TITLE
Methods not implemented in ProxyHttpServletResponse and ProxyServletContext

### ISSUE THREAD

**Issue by sjuarezgx** [spring-cloud/spring-cloud-function#1170]
There are several methods in the aforedmentioned classes that are not implemented.
package org.springframework.cloud.function.serverless.web

For example, in the ProxyHttpServletResponse the addCookie and getCookie methods throw UnsupportedOperationException.
The same happens with several methods of ProxyServletContext which throw the same exception (such as getRealPath, getMajorVersion, etc).

Is there a plan to implement them?

In case the answer is no, what is the recommended solution?

You recommend extending those clases?

**Comment by olegz** [comment]
Well, personally I would like to know more about your use case. The serverless web feature of s-c-function is not really a replacement for full blown Spring MVC application and is primarily to support REST endpoint model that actually fits the stateless model of serverless applications. In other words it was never intended to support a general purpose website with forms, state management etc. . .
Of course things can change, but would need more info from the community

**Comment by olegz** [comment]
Closing it due to lack of follow up form the original reporter
