### ISSUE TITLE
Spring Cloud Function managed ObjectMapper serializes instants as timestamps

### ISSUE THREAD

**Issue by 0xabadea** [spring-cloud/spring-cloud-function#1171]
Due to https://github.com/spring-cloud/spring-cloud-function/issues/1148 Spring Cloud Function stopped using the SB-provided `ObjectMapper` and started using its own instead. This `ObjectMapper` has the default value of `SerializationFeature.WRITE_DATES_AS_TIMESTAMPS`, i.e., true, which results in dates being serialized as timestamps such as `1722512479.223919000`.

May I use this opportunity and suggest that not using the SB-provided `ObjectMapper` is not a good idea, as it modifies behavior that SB users have come to rely on. Apart from date serialization, see the complaints about the SCF mapper not supporting Kotlin, as it doesn't register `KotlinModule`.

**Comment by olegz** [comment]
This has been addressed - https://github.com/spring-cloud/spring-cloud-function/issues/1148
