### ISSUE TITLE
Issue with @Bean Annotation in Separate Java Files When Deploying to Google Cloud Functions

### ISSUE THREAD

**Issue by yihangYH** [spring-cloud/spring-cloud-function#1179]
I am experiencing an issue when deploying a Spring Cloud Function application to Google Cloud Functions (GCP). The problem arises when I try to define functions using the @Bean annotation in separate .java files (i.e., files other than the one containing the main method).

When I define functions using the @Bean annotation in separate .java files, everything works perfectly fine when running the application locally. However, when I deploy the same application to Google Cloud Functions, I encounter the following error:

`
IllegalArgumentException: Failed to lookup function to route based on the value of 'spring.cloud.function.definition' property 'hi'
`

The error disappears if I move all the @Bean annotated methods into the same .java file that contains the main method. This behavior seems inconsistent and is causing issues when trying to modularize the codebase.

I have seen a similar [issue](ttps://github.com/spring-cloud/spring-cloud-function/issues/1164) reported, but there has been no response. I am wondering if this is a known issue with a potential workaround or if there is any additional configuration required when deploying to Google Cloud Functions.

I have tried using the following annotations to ensure that all @Bean methods are properly scanned and registered, but the issue persists:
`
@SpringBootApplication(scanBasePackages = {"com.example.demo", "com.example.demo.functions"})
@ComponentScan(basePackages = "com.example.demo.functions")
`

Any guidance or assistance would be greatly appreciated.

**Comment by olegz** [comment]
Does the file containing @Bean annotations is also annotated with @Configurationi or @EnableAutoConfiguration? Do you have some sample code you can show?

**Comment by yihangYH** [comment]
> Does the file containing @bean annotations is also annotated with @Configurationi or @EnableAutoConfiguration? Do you have some sample code you can show?

Yes, please check below code. For the same code, I managed to run successfully in aws lambda
```
package com.example.demo.functions;
import com.example.demo.model.RequestModel;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import java.util.function.Function;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@Configuration
public class Request {
    private static final Logger logger = LoggerFactory.getLogger(Request.class);


    @Bean
    public Function<RequestModel, String> hi() {
        return requestModel -> {
            logger.info("Hi function called with name: {}", requestModel.getName());
            String name = requestModel.getName();
            return "Hi " + name;
        };
    }

    @Bean
    public Function<RequestModel, String> goodbye() {
        return requestModel -> {
            logger.info("Goodbye function called with name: {}", requestModel.getName());
            String name = requestModel.getName();
            return "goodbye " + name;
        };
    }
}
```
