### ISSUE TITLE
The ContextFunctionPostProcessor doesn't resolve function from the FactoryBean

### ISSUE THREAD

**Issue by artembilan** [spring-cloud/spring-cloud-function#118]
There is the code in the `ContextFunctionPostProcessor.findType()`:
````java
else if (source instanceof Resource) {
	try {
		Class<?> beanType = ClassUtils.forName(definition.getBeanClassName(),
					null);
		for (Type type : beanType.getGenericInterfaces()) {
			if (type.getTypeName().startsWith("java.util.function")) {
					param = extractType(type, paramType, index);
					break;
			}
		}
		if (param == null) {
			// Last chance
			param = beanType;
		}
	}
	catch (ClassNotFoundException e) {
		throw new IllegalStateException(
			"Cannot instrospect bean: " + definition, e);
	}
}
````
Where `beanType` can be resolved to some `FactoryBean`. For example `GatewayProxyFactoryBean` from Spring Integration for `Function` service interface.

This code must include something similar what SF has for the `BeanFactory.isTypeMatch()` resolution:
```
if (beanInstance instanceof FactoryBean) {
	if (!BeanFactoryUtils.isFactoryDereference(name)) {
		Class<?> type = getTypeForFactoryBean((FactoryBean<?>) beanInstance);
		return (type != null && typeToMatch.isAssignableFrom(type));
	}
	else {
		return typeToMatch.isInstance(beanInstance);
	}
}
```

Also `param = beanType;` looks suspicious as well. In my case we fail into the `FactoryBean` type.
However we definitely expect here a generic type since we have came here just because this bean is `Function`. So, an `Object.class` should be good one as a general fallback.

**Comment by dsyer** [comment]
That sounds reasonable. PR welcome.
