### ISSUE TITLE
CloudEventMessageUtils.getSource fails on Kafka messages.

### ISSUE THREAD

**Issue by joachimm** [spring-cloud/spring-cloud-function#1190]
**Describe the bug**

CloudEventMessageUtils.getSource, fails on incoming Kafka message.

I am using cloud stream binder and the header 'ce_source' is of type byte[]
getSource expects String or URI.

**Sample**
       CloudEventMessageUtils.getSource(MessageBuilder.withPayload(new Object()).setHeader("ce_source", new byte[] {}));

**Comment by olegz** [comment]
What about the other headers? Are they all `byte[]`?

**Comment by joachimm** [comment]
All the ce_ prefixed ones are.

**Comment by joachimm** [comment]
I added a comment to the safeGetURI fix.
I think the byte[] handling is unreachable code.

**Comment by olegz** [comment]
Yes, sorry, meant to remove it

**Comment by olegz** [comment]
fixed
