### ISSUE TITLE
v.4.1.3 source code file contains 4.0.x branch's class file.

### ISSUE THREAD

**Issue by Be-poz** [spring-cloud/spring-cloud-function#1194]
I'm not sure if this was intended or not, but the v.4.1.3 source code file contains class files from v.4.0.3. 

The class mentioned above is shown below.
[4.1.x branch - SmartCompositeMessageConverter](https://github.com/spring-cloud/spring-cloud-function/blob/4.1.x/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/context/config/SmartCompositeMessageConverter.java)
[4.0.x branch - SmartCompositeMessageConverter](https://github.com/spring-cloud/spring-cloud-function/blob/4.0.x/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/context/config/SmartCompositeMessageConverter.java)

I'm guessing this is because the class in the 4.1.x branch was committed a month ago, and the 4.1.3. release was about 4 months ago, is that correct?  If that's correct, I'd like to make sure that the 4.1.4 release contains this commit.

**Comment by olegz** [comment]
I am not sure what are you asking. Can you please clarify? `SmartCompositeMessageConverter` is one of the core components of the framework, so it's in all branches

**Comment by Be-poz** [comment]
<img width="596" alt="image" src="https://github.com/user-attachments/assets/b2999292-54a5-42b0-8735-e0e1594509c2">

I wanted to say that the source code for the SmartCompositeConverter in the 4.1.3 version is not from the 4.1.x branch, but from 4.0.x. I also wanted to make sure that this was because a commit was made to the SmartCompositeConverter code in the 4.1.x branch after the 4.1.3 release, and I wondered if the 4.1.4 release would reflect that commit.

**Comment by olegz** [comment]
Yes

**Comment by Be-poz** [comment]
What I was confused about at first  
* Why does the 4.1.3 version source zip file have a class source code in the 4.0.x branch?

What I guessed
* [The commit](https://github.com/spring-cloud/spring-cloud-function/commit/6dee668e3ec20710460b0384a8b6afe53d078633) added to the 4.1.x branch seems to have not been reflected because it was added after the date 4.1.3 was released.

What I wanted to ask
* If so, will the class file with that commit be released in the next release?  

It's pretty obvious that this will be in the next release, but I wanted to ask just to be sure. 
Thanks. You can close this issue.

**Comment by olegz** [comment]
I am still confused about what you are asking and what `source.zip` you are referring to.
The fix has been added to 4.1.x - https://github.com/spring-cloud/spring-cloud-function/commit/6dee668e3ec20710460b0384a8b6afe53d078633 as well as 4.2.x https://github.com/spring-cloud/spring-cloud-function/commit/571783ffae5f24df9fbc0cc08a2e3838c97b58ae
So yes they will be included in the next release.
4.1.x will be released on November 12
