### ISSUE TITLE
ClassCastExceptions: Missing Jackson Modules

### ISSUE THREAD

**Issue by Richie94** [spring-cloud/spring-cloud-function#1201]
By Upgrading from spring.cloud from 4.1.2 to 4.1.3 I got errors caused by the inability in the deserialization.

When I digged a bit deeper, I found that the JacksonMapper has a completely different ObjectMapper than in the version before. In my case, there was only a jsr-10 module registered, whereas in the previous version it also detected my other modules (like kotlin-modul, which caused the error)

I found here https://github.com/spring-cloud/spring-cloud-function/commit/8b66fd296e72e8c0f1ed5df0711da5ea75527cb8 that you changed from using the provided objectmapper to using your own. 

Why has this changed been made? 
How can i add my modules here?

**Comment by olegz** [comment]
Yes, this issue has been addressed and will be available in the next 4.1.4 and 4.1
