### ISSUE TITLE
Build and test for Linux/ARM64

### ISSUE THREAD

**Issue by odidev** [spring-cloud/spring-cloud-function#1205]
## Description  

For aarch64 platform, I have built " spring-cloud-function " from source.  

## Steps   

Following [STEPS](https://github.com/spring-cloud/spring-cloud-function/blob/main/README.adoc) were used for the building and installation: 

```
$ git clone https://github.com/spring-cloud/spring-cloud-function.git  &&  cd spring-cloud-function/

$ git checkout v4.1.1

$ Install JDK and setup JAVA_HOME.

$ Install MVN and setup Maven

$ mvn clean install
``` 

## Outcome  

Maven build, test and install is successful.

All this information is also added to [Software Ecosystem Dashboard for Arm](https://www.arm.com/developer-hub/ecosystem-dashboard/).

**Comment by olegz** [comment]
Closing it as there is no action to perform
