### ISSUE TITLE
CloudEvent header values are not formatted according to the specification

### ISSUE THREAD

**Issue by kschlesselmann** [spring-cloud/spring-cloud-function#1211]
We use the cloud event support of Spring Cloud Function to produce Kafka messages using Spring Cloud Stream. It looks like the headers are not properly formatted. For example ce_source contains surrounding quotes and [ce_time is not RFC3339 compliant](https://github.com/cloudevents/spec/blob/v1.0/spec.md#time).

I created a [sample](https://github.com/fortis-it-services/spring-cloud-function-1211) that demonstrates the issues.

This is a follow up to my [older issue](https://github.com/spring-cloud/spring-cloud-function/issues/1089)

**Comment by olegz** [comment]
Duplicate to https://github.com/spring-cloud/spring-cloud-function/issues/1089
