### ISSUE TITLE
Class implementing Function interface is not properly detected when apply method is in a superclass

### ISSUE THREAD

**Issue by agascon** [spring-cloud/spring-cloud-function#1221]
**Describe the bug**
We have an AWS Lambda implemented in Java using Spring Cloud Function + Spring Cloud AWS adapter. 

We upgraded recently to Spring Cloud 2024 and the lambda started to fail with error...

`Only Supplier, Function or Consumer supported at the moment. Was class <classname>: java.lang.IllegalArgumentException`

Lambda is implementing Function interface but in a superclass so this is not handled properly in _spring-cloud-function-context_, _FunctionTypeUtils_, likely in _discoverFunctionalMethod_ static method.

As mitigation we had to implement the apply method at the actual lambda function, something like this...
```
    @Override
    public String apply(final Message<KafkaEvent> inputMessage) {
        return super.apply(inputMessage);
    }
```

I think _discoverFunctionalMethod_ to consider all methods (including those inherited from superclasses) when validating the class.

**Comment by agascon** [comment]
Hi @olegz , thanks for the quick answer.  I did a quick test and I think 4.2.1-SNAPSHOT is resolving the issue.

Either way, we will run some further regression and confirm this is the case.

Thanks!

**Comment by olegz** [comment]
Please let me know if I can close it

**Comment by agascon** [comment]
I would say yes, the issue is resolved in the SNAPSHOT
