### ISSUE TITLE
Support for consumer groups in HTTP

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-function#123]
What does that even mean? Spring Cloud Stream has "consumer group" as a core domain feature (although there has been some discussion about making it optional). What would that look like for HTTP consumers? See also #36.

**Comment by olegz** [comment]
I don't really know what it means or what would be the benefit. In Spring Cloud Stream "consumer group" plays a big role when tied together with SCDF by essentially routing between the instances of a consumer, so I look at it as more of an application connectivity feature. Are we planning to connect apps like that over HTTP? 
And yes we are considering on expending the concept of binders in Spring Cloud Stream basing it on features like persistent pub-sub, support for consumer groups etc.
