### ISSUE TITLE
Issue running spring-cloud-function-deployer

### ISSUE THREAD

**Issue by Nerdkapp** [spring-cloud/spring-cloud-function#127]
Hi,

I built the whole project with `./mvnw clean install` but  function-deployer application fails to start.

I ran: `mvn spring-boot:run` getting the following exception:

`org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'bindingService' defined in class path resource [org/springframework/cloud/stream/config/BindingServiceConfiguration.class]: Unsatisfied dependency expressed through method 'bindingService' parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.cloud.stream.config.BinderFactoryConfiguration': Unsatisfied dependency expressed through field 'binderTypeRegistry'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'binderTypeRegistry' defined in class path resource [org/springframework/cloud/stream/config/BinderFactoryConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.stream.binder.BinderTypeRegistry]: Circular reference involving containing bean 'org.springframework.cloud.stream.config.BinderFactoryConfiguration' - consider declaring the factory method as static for independence from its containing instance. Factory method 'binderTypeRegistry' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Cannot create binder factory, no `META-INF/spring.binders` resources found on the classpath
        at org.springframework.beans.factory.support.ConstructorResolve`

I tried also to run the application starting it from the IDE and running the jar with `java -jar spring-cloud-function-deployer-1.0.0.BUILD-SNAPSHOT.jar` but nothing seems to work.

Any hint?

Thanks!

**Comment by dsyer** [comment]
Looks like a bug in the dependencies. Spring Cloud Stream for sure is not required, so you can probably work around it by setting `spring.cloud.stream.enabled=false`.

**Comment by dsyer** [comment]
Fixed in 24bd68d
