### ISSUE TITLE
AWS adapter needs `Start-Class` entry in MANIFEST.MF of shaded jar 

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-function#128]
Tried a number of combinations. Looks like the `spring-boot-thin-layout` plugin in the example for AWS does add `Start-Class` to the manifest. Removing that plugin, I had to add a `Start-Class` entry in the manifest for the `maven-jar-plugin` plugin to get it to work.  This wasn't obvious from reading the docs.

**Comment by dsyer** [comment]
You can also use an env var "MAIN_CLASS".
