### ISSUE TITLE
"spring-cloud-function-compiler" in Maven is not accessible

### ISSUE THREAD

**Issue by ravikalla** [spring-cloud/spring-cloud-function#133]
I used below dependency and it is throwing an exception  saying that the dependency count be found.

<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-function-compiler</artifactId>
    <version>1.0.0.M1</version>
</dependency>

**Comment by laxika** [comment]
Do you use the Spring repositories?

https://repo.spring.io/milestone

**Comment by ravikalla** [comment]
The one in Maven is not accessible - though it appears there?

**Comment by spencergibb** [comment]
If you read the mvnrepository page it says it's hosted in the spring milestone repo. That's where it is available.
