### ISSUE TITLE
spring-cloud-dataflow vs spring cloud-function

### ISSUE THREAD

**Issue by cforce** [spring-cloud/spring-cloud-function#137]
Is the only difference the granularity (microservice >data flow > task>function) of the deployment unit/ business logic boxed? 
Please help to find out what will stick together, what may be dropped in favour or just melts together of this two projects where i see so much coverage in patterns an functionality, 

```
> https://github.com/spring-cloud/spring-cloud-function  <>  https://github.com/spring-cloud/spring-cloud-dataflow
> spring cloud-function-task  <> spring-cloud-task
> spring cloud-function-web   <>  spring-cloud-web
> spring-cloud-function-stream   <> spring-cloud-stream
> spring-cloud-function-deployer <> Spring Cloud Skipper -> Spring-cloud-deployer(cloudfoundry,kuberntes, yarn,mesos) 
> spring-cloud-function-registry-service <> spring-cloud-dataflow-registry
> @FunctionScan <> @EnableTask
> @FunctionEntry <>
```

While dataflow already has support for Kubernetes to scale out running processes i don't undertstand how spring-cloud-function-deployer will solve that stateful process managment of function instances at high scale and on which provided XaaS.

Tx for clarifying differences, commonalities and common roadmap of this two projects.

**Comment by dsyer** [comment]
There is some chance that dataflow apps will be functions in some future version. The convergence is explicit and obvious (spring cloud stream is the glue).

I wouldn't look at any other of your parallels and draw too many conclusions (and some of them have one end that doesn't exist anyway, like `spring-cloud-web` and `spring-cloud-function-registry-service`. The deployer in particular is highly experimental, but could be a taste of what a dataflow server would look like if all apps were running locally (i.e. no intention to manage anything at high scale or in XaaS).

**Comment by cforce** [comment]
The spring cloud function adapter are currently a wrapper awound spring cloud function implementations to deploy them on supported FaaS providers.
How do i call a SCF in dataflow? I found a starter-app - ias that "wrapper" for calling SCF in data flow server?
https://github.com/spring-cloud-stream-app-starters/function/blob/master/spring-cloud-starter-stream-app-function/README.adoc

**Comment by dsyer** [comment]
I guess that is _a_ wrapper. It would be just as easy for some (most?) apps to just include spring-cloud-function-stream as a dependency, and then they are automatically SCDF apps. SCF only requires the binding AFAIK.

**Comment by cforce** [comment]
SpringCloudFunction itself does not offer features  to compose data flow streams, but Spring cloud data flow  does.
Having the [SPCF adapter](https://github.com/spring-cloud-stream-app-starters/function/blob/master/spring-cloud-starter-stream-app-function/README.adoc) for calling in SpringCloud DataFlow's allows me to deploy and excute SPCFunctions controll from DaFlowServer. 
Currently DataFlowServer  allows me to deploy on Kuberntes, Cloudfoundry & Openshift
Iss there also an approach to deploy on SpringCloudFunctions Adapatered FaaS platforms like IBM OpenWhisk, Google, Azure, AWS Lambda ans the use this in a composed data flow ?
If functions in all this FaaS will published via OpenServiceBroker as catalogue, i could register them automatically in SpringClouddataFlow and use the functions in my data flow stream compositions.

**Comment by cforce** [comment]
Additional I would like to know what riff integration is planned or how spring cloud data flow relates to Pivotals FaaS Plattform Riff

**Comment by olegz** [comment]
In short Data Flow orchestrates [Spring Cloud Stream](https://cloud.spring.io/spring-cloud-stream/) applications over messaging middleware of your choice (Rabbit, Kafka etc). As of now Spring Cloud Stream is [fully integrated with Spring Cloud Function](https://spring.io/blog/2018/08/28/spring-cloud-stream-fishtown-m2-2-1-0-m2-release-announcement) by providing an alternative programming model. So, to compose data flow from individual functions is no different then compose data flow from any other spring cloud stream app.

**Comment by cforce** [comment]
Registration in  DataFlowServer of  producer/consumer as stream app (spring cloud stream) and function (spring cloud function) is needed, so this apps can be downloaded, used for stream/pipe/dataflow layouts and afterwards to be shipped/deployed on Kubernetes or PCF (or local for developing).
What dataflow server does not support is to register Azure/AWS or Google Functions which are already deployed on their clouds plattform and to use them as producer/consumer in your dataflow stream.
Besides a FaaS platform like project Eirini (proceeded from RIF) besides native Kubernetes as deployment target would be a cloud native option.

**Comment by olegz** [comment]
I am going to close this as stale and if anything the discussion is more about data-flow hence out of scope of SCF. If you have more specific suggestion/request, please open a new issue.
