### ISSUE TITLE
Better support for flexible Azure handler signatures

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-function#139]
Apparently Azure cannot discover the parameter types if the user handler extends `AzureSpringBootRequestHandler` and doesn't wrap the `handleRequest()` method, e.g.

```java
public class FooHandler extends AzureSpringBootRequestHandler<Foo, Bar> {

	public Bar execute(Foo foo, ExecutionContext context) {
		return handleRequest(foo, context);
	}

}
```

**Comment by dsyer** [comment]
It still works for me using the code above. Look at the sample in the project. If you are looking at master you will need snapshots.

**Comment by johannaboerner** [comment]
Thanks, I found my problem. It was all about the pom.xml

**Comment by olegz** [comment]
I'll close it given quite a few improvement to  adapters in general as well as Azure specifically. 

Please raise a new issue to address whatever may be missing now
