### ISSUE TITLE
Can't find the openwhisk sample 

### ISSUE THREAD

**Issue by csantanapr** [spring-cloud/spring-cloud-function#145]
From this site there is a link to openwhisk sample but the link is broken
Site: https://cloud.spring.io/spring-cloud-function/#quick-start
Link: https://github.com/spring-cloud/spring-cloud-function/tree/master/spring-cloud-function-samples/function-sample-openwhisk
![image](https://user-images.githubusercontent.com/1094878/36623225-c04cf4c6-18d0-11e8-84a2-9494a855bed1.png)

**Comment by kameshsampath** [comment]
@csantanapr  - here are two examples 

* https://github.com/kameshsampath/openwhisk-scf-docker (Docker Image)
* https://github.com/kameshsampath/ow-scf-fruiteason - (POF example)
* https://github.com/kameshsampath/ow-scf-greeter - (Spring Boot App example)

@dsyer  - is it possible for document to point to these repos or can it be forked under spring-cloud-functions repo ?

**Comment by dsyer** [comment]
We could put a link in the README for the openwhisk adapter I guess, if you are planning on maintaining the samples. Send a PR and we can do that quickly. Longer term we might want to start a new project in github.com/spring-cloud-samples.

**Comment by kameshsampath** [comment]
@dsyer  - where should we send the PR , README.adoc of this repo ?

**Comment by dsyer** [comment]
There's a readme in the ow adapter module (in this project) isn't there?

**Comment by kameshsampath** [comment]
oh yeah !! I can add them there to OW Adapter

**Comment by kameshsampath** [comment]
#147  should solve this. 

@dsyer  - added the links to README, please feel free to mere when you are on it. thanks.

**Comment by kameshsampath** [comment]
thanks @dsyer for merging
