### ISSUE TITLE
Samples should work "standalone"

### ISSUE THREAD

**Issue by Clockwork-Muse** [spring-cloud/spring-cloud-function#148]
Currently, the samples are dependent on being built inside a copy of the repository, which means programmers looking for _only_ the samples get a non-functioning build.

This is mostly due to the fact that, for the moment, the builds are dependent on snapshot releases.  It would be better to modify the sample poms to be standalone projects, which may only require adding the relevant `repositories` entries for now.

**Comment by dsyer** [comment]
AFAIK the samples all have repository declarations (e.g. https://github.com/spring-cloud/spring-cloud-function/blob/master/spring-cloud-function-samples/function-sample-pojo/pom.xml#L80). Can you be more specific about which ones didn't work for you?

**Comment by Clockwork-Muse** [comment]
The [Azure sample lacks the declarations](https://github.com/spring-cloud/spring-cloud-function/blob/master/spring-cloud-function-samples/function-sample-azure/pom.xml)
