### ISSUE TITLE
Dependency spring-cloud-starter-function-web with provided scope in samples causes issues with some spring framework types.

### ISSUE THREAD

**Issue by Clockwork-Muse** [spring-cloud/spring-cloud-function#149]
All the sample poms include this dependency:

```xml
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-function-web</artifactId>
    <scope>provided</scope>
</dependency>
```
... and the scope of `provided` is causing issues when trying to run on Azure.

For instance, the following function definition throws `ClassNotFoundException` while running on Azure (or at least the test runner):

```Java
@Bean
public Function<String, String> uppercase() {
    int res = HttpStatus.OK.value();
    return request -> {
        return request.toUpperCase();
    };
}
```

...Note that this code builds _and tests_ just fine, passing both default tests.  It's not until it hits the runner that it errors out:

>[2018-02-26 23:59:38] Caused by: java.lang.ClassNotFoundException: org.springframework.http.HttpStatus
[2018-02-26 23:59:38]   at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
[2018-02-26 23:59:38]   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
[2018-02-26 23:59:38]   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
[2018-02-26 23:59:38]   ... 45 more
[2018-02-26 23:59:38] .

([full stack trace](https://gist.github.com/Clockwork-Muse/bd1e41c0fec57a3d5af963ea78cef071))

Obviously, removing the scope "fixes" the issue, but I'm not sure if there's a better/more relevant solution here.

**Comment by dsyer** [comment]
You need `spring-web` as a runtime time dependency if you want to use `HttpStatus`. Wouldn't it be easier to use "200"? Or delete that line completely, since you don't use the value?

**Comment by Clockwork-Muse** [comment]
.... using just `"200"` would be a magic number, which I'd prefer to avoid.

The line only looks like that because that's how I narrowed down the issue.  Before I had it as:
```Java
@Bean
public Function<HttpRequestMessage<String>, HttpResponseMessage<String>> uppercase() {
    return request -> request.createResponse(HttpStatus.OK.value(), request.getBody().toUpperCase());
}
``` 
....which hangs (or times out, if one was set in the host.json).  That's an Azure/worker issue, though, not Spring's fault.

**Comment by dsyer** [comment]
You lost me. What is `HttpRequestMessage`? Is it something from Azure?

**Comment by Clockwork-Muse** [comment]
Yes, `HttpRequestMessage` is from Azure.  Which I'd like to avoid, but I can't seem to get `Message` to be picked up.  The actual problem Azure faces, though, is solely from not handling the thrown error/exception, not the type.
