### ISSUE TITLE
Make Jackson optional in case apps need special features

### ISSUE THREAD

**Issue by L0key** [spring-cloud/spring-cloud-function#150]
I've got an existing project that I'm trying to convert that uses Jackson for JSON serialization/deserialization.  Is there any way to force spring cloud to not default to GSON for JSON object parsing?

**Comment by L0key** [comment]
BTW I tried excluding GSON from the dependencies as some posts mentioned, but that only produced this error:
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/gson/Gson

**Comment by L0key** [comment]
NM - found commit 975398d30cc3fb7a48d1024b02c33f96ccbdd20c and it appears that GSON has been made required

**Comment by dsyer** [comment]
It should only affect spring-cloud-web at the minute. And not all use cases at that. Can you be more specific about where the issue arose, and we can maybe make an abstraction that hides the detail (Spring MVC already has one).

**Comment by L0key** [comment]
Sure thing @dsyer!

Within the `@SpringBootApplication` class I created a function to deserialize the request and invoke the logic (a Spring service) in Lambda:
```
   @Bean
    public Function<MyRequest, MyResponse> function() {

        return value -> service.execute(value);
    }
```

Before the function has a chance to fire, the deserialization of the request gives the class def error since my request object contains both JsonNode and byte[] properties.  This would've been handled seamlessly in Jackson, but GSON doesn't deal with Jackson JsonNode/ObjectNode objects (of course!), and doesn't support byte array serialization/deserialization to/from base64 strings out-of-the-box.

**Comment by dsyer** [comment]
That wouldn't happen in Lambda right? You must be testing it locally with the spring-cloud-function-web support? I dare say you could register an adapter in Gson for Jackson types. Kind of screwy, but then again so is using Jackson in a request/response DTO.

**Comment by L0key** [comment]
Yeah we have a bit of a unique use-case for this and we're using Jackson "across the board".  I'll try registering an adapter for GSON, just thought it'd be easier to rely on the usual Spring support for whatever parsing library is available.

You're right, this is only for local testing and I'm sure it works fine in Lambda given that they use Jackson natively as their JSON parsing library.

**Comment by gotson** [comment]
Hello, i also have some issues with GSON.

The input object of my function has some JODA time fields, and GSON fails to deserialize it.

I tried adding a bean of type `Gson` in my project, with custom serializers registered, but it doesn't seem that Spring is picking it up.

**Comment by dsyer** [comment]
Can you post a link to a sample project please?

**Comment by gotson** [comment]
My bad, my bean was named _mapper_, like the one for Jackson.
Without the name property on the @Bean annotation it works fine!
