### ISSUE TITLE
Function beans rejected in @Configuration classes after instantiation

### ISSUE THREAD

**Issue by Clockwork-Muse** [spring-cloud/spring-cloud-function#153]
Attempting to extract function bean definitions to a separate class results in the bean being ignored.  That is, something like: 

```Java
@Configuration
public class Config {
    @Bean
    // The problem exists regardless of requiring dependency injection, which works just fine.
    public static Function<Flux<RequestType>, Flux<ResponseType>> create(TypeHandler handler) {
        return request -> request.flatMap(handler::create);
    }
}
```
.... ultimate results in NPE ([full stack trace](https://gist.github.com/Clockwork-Muse/22d1399431d3bbfa58f348759858e143)):
>Exception: Error creating bean with name 'functionCatalog' defined in class path resource [org/springframework/cloud/function/context/config/ContextFunctionCatalogAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.function.context.FunctionRegistry]: Factory method 'functionCatalog' threw exception; nested exception is java.lang.NullPointerException

This _feels_ like it should just work, given examples like `RouterFunctions` for WebFlux:
```Java
@Configuration
public class TypeRoute {

    @Bean
    public static RouterFunction<ServerResponse> routes(final TypeHandler handler) {
        return nest(path("/type"), nest(accept(APPLICATION_JSON_UTF8),
                route(POST("/").and(contentType(APPLICATION_JSON_UTF8)), handler::create)));
    }
}
```

**Comment by dsyer** [comment]
It works in the POJO sample. Can you create a sample app that shows the issue please? Why is your `@Bean` method static (not that it matters for this issue)?

**Comment by Clockwork-Muse** [comment]
:shrug: `static` was what I initially listed it at.  It doesn't work as an instance method either.

It turns out I was slightly wrong: the problem is dependent on injecting something (I probably didn't `mvn clean package` one time or something).

This works:
```Java
@Configuration
public class Config {
    @Bean
    public static Function<Flux<RequestType>, Flux<ResponseType>> create() {
        return request -> request.flatMap(r -> new ResponseType());
    }
}
```
This does not:

```Java
@Configuration
public class Config {
    @Bean
    public static Function<Flux<RequestType>, Flux<ResponseType>> create(TypeHandler handler) {
        return request -> request.flatMap(handler::create);
    }
}
```

The problem isn't that the injected item isn't provided - it's there, I've verified through debug
 - it's that some part of the loader seems to be discarding the function as viable afterwards.

What's more strange is that if the bean is defined as requiring injection on the Application class it works just fine:

```Java
@SpringBootApplication
public class Config {

	public static void main(String[] args) throws Exception {
		SpringApplication.run(Config.class, args);
	}

	@Bean
	public Function<Flux<Foo>, Flux<Bar>> uppercase(LocalService service) {
		return foo -> foo.map(f -> f.getValue()).map(s -> new Bar(s.toUpperCase()));
	}
}
```

Attaching a "working" [repro](https://github.com/spring-cloud/spring-cloud-function/files/1772563/repro.zip).
