### ISSUE TITLE
Document public API of adapters

### ISSUE THREAD

**Issue by Clockwork-Muse** [spring-cloud/spring-cloud-function#154]
I'm assuming that it's Azure and its runtime that are instantiating `AzureSpringFunctionInitializer`/`AzureSpringBootRequestHandler`, which is also why you're required to have a no-arg constructor.

I'd like to be able to inject dependencies into my handlers, but this currently isn't possible, because the base initializer/handler is instantiated outside of Spring's control.  Neither field injection nor setter injection seem to be used.

(Specifically, I'm trying to do my own JSON de/serialization and validation, because allowing Azure to do it gives you a 500, not a 400, if there are any validation problems.)

**Comment by dsyer** [comment]
We can definitely autowire the handler.

What is your function method signature? How do you ask for raw data to do your own JSON schlepping?

**Comment by Clockwork-Muse** [comment]
I _was_ just having the handler give me a string, but it looks like Azure closed the loophole - it deserializes any JSON object if Content-Type is set, which means it rejects objects before they even get to the runtime (which is kinda nice, in that it wouldn't charge you, but the problem is that currently they return absolutely the wrong status code and a completely unhelpful error message.  And since I never see it, I can't return a standardized message, either).

In any case, given a small wireable dependency:

```Java
@Component
public class LocalWired {
    public int getValue() {
        return 5;
    }
}
```
... and the handler:

```Java
public class FooHandler extends AzureSpringBootRequestHandler<Foo, Bar> {

	@Autowired
	private LocalWired wired;

	public Bar execute(Foo foo, ExecutionContext context) {
		context.getLogger().log(Level.WARNING, wired == null ? "Not wired" : "Correctly autowired");
		return handleRequest(foo, context);
	}

}
```
... then `Not wired` is being logged.

**Comment by Clockwork-Muse** [comment]
....I'm kicking myself, because I just realized this is dependent on the `initialize` method being called, which means the dependency _is_ available.... **after** `handleRequest` is called.  So I need to adjust how I wrote stuff, mostly.  Maybe this just needs to be documented better?

**Comment by dsyer** [comment]
Maybe. I thought of it as an implementation detail though (users shouldn’t need to be aware). Wouldn’t it make more sense to inject the `LocalWired` into your function?

**Comment by Clockwork-Muse** [comment]
I have other stuff I was injecting into my function, what I was using at this layer was the deserialization/error handling.

Deserialization, at least, needed to happen at this point, because since I have multiple functions they all need different signatures so they can be picked up (say, a GET and a POST would most likely return the same object, meaning the difference comes from the parameters).  The moment you do your own deserialization you also need to handle the errors from it, which meant the error handling had to be there as well.

**Comment by dsyer** [comment]
I guess you need to call `initialize()` before the handler then? It would be easier with a concrete sample.

**Comment by tzolov** [comment]
Starting with version `4.0.x`, the SCF `Azure Adapter` uses dependency injections and allows auto-wiring any Spring dependencies in your Azure function handlers.

- [Azure Adapter Docs](https://docs.spring.io/spring-cloud-function/docs/4.0.5-SNAPSHOT/reference/html/azure.html)
- [Azure Adapter Samples](https://docs.spring.io/spring-cloud-function/docs/4.0.5-SNAPSHOT/reference/html/azure.html#_samples)
