### ISSUE TITLE
Spring security and cloud functions

### ISSUE THREAD

**Issue by Nerdkapp** [spring-cloud/spring-cloud-function#155]
I'm wondering if spring-cloud-function should provide some utility to manage the security.

Basically, I created an application based on spring cloud functions which makes use of spring-security, how could we retrieve the logged user in our functions?

**Comment by dsyer** [comment]
In a native spring-cloud-function app with spring-cloud-function-web then Spring Security can be used to authenticate, and we don't really need to do anything here. So what was your use case? How was the user going to be authenticated?

**Comment by Nerdkapp** [comment]
Thanks @dsyer ,

the user is logged in another application and a Bearer token is sent to the cloud function application, which making use of spring security checks the validity of the user token.

Now, in a classic Spring web application, I would add the principal parameter in the controller like this:

`
@RequestMapping(value = { "/{test}" }, method = RequestMethod.POST, produces = MediaType.APPLICATION_JSON_VALUE)
	public ResponseEntity<String> post(@PathVariable String test, Principal principal) {
`

So, how could I achieve something similar using the cloud functions?

**Comment by dsyer** [comment]
Just call `SecurityContextHolder.getContext()` inside your function if it's a simple request-response. Maybe we could add a message header, but it would have to be carefully thought out since it would be an object, not a simple string.

**Comment by Nerdkapp** [comment]
SecurityContextHolder.getContext() is absolutely ok right now, thanks a lot @dsyer it was actually easier than I thought!
