### ISSUE TITLE
Support handling aggregated Kinesis events (AWS adapter)

### ISSUE THREAD

**Issue by grelland** [spring-cloud/spring-cloud-function#164]
In the AWS adapter, there is no support currently for handling aggregated Kinesis events. This is a common use case as events produced by the Kinesis Producer Library (KPL) are aggregated by default.

I have made an implementation in [this PR](https://github.com/spring-cloud/spring-cloud-function/pull/160)

**Comment by dsyer** [comment]
Resolved via #160
