### ISSUE TITLE
Provide access to the Context object

### ISSUE THREAD

**Issue by viniciusccarvalho** [spring-cloud/spring-cloud-function#167]
Most FaaS implementations provide a `Context` object with relevant information to the function execution.

Currently it does not seems to be possible to access that object, it would be nice to have native support, either via some sort of `BiFunction` support of Context,R,T signature or something similar to what spring-security does for SecurityContextHolder.

**Comment by dsyer** [comment]
I think `BiFunction` would be ugly, so either a generic wrapper type, or the subscriber context (as you suggest), or a `Message` header would probably be the best plan. Note that some of the meta data ("context") is already available for some adapters via headers.

**Comment by olegz** [comment]
FWIW, I am leaning on the side of the Message header. It's natural and well understood

**Comment by olegz** [comment]
@viniciusccarvalho I am going to close it for now in favor of advocating the usage of `Message` for such cases. We can certainly revisit it again at some point if there are more concrete/specific requirements
