### ISSUE TITLE
Consider exposing access to argument Type instead of just Class in FunctionInspector

### ISSUE THREAD

**Issue by olegz** [spring-cloud/spring-cloud-function#179]
Technically it's there via ```functionType.getType(). . .``` where one can introspect on `ParameterizedType` etc. But i guess we can make it simpler, perhaps `functionType.getParameterizedType()`
Access to it would help us support more sophisticated argument resolution (i.e., `List<Foo>, Map<Bar, Baz>` etc), similar to what we already have in SCSt.

**Comment by dsyer** [comment]
It might not be a `ParameterizedType` though, so you are stuck with `Type` I think. We might need to keep the signature of the existing methods as well, so let's go carefully here.

**Comment by olegz** [comment]
I agree. And as discussed I am not in the hurry to implement it since I can already do what I want to do and this would be just an additional convenience.

**Comment by olegz** [comment]
I am closing it as "won't fix". In the end the required functionality is there and even though it may require an few extra hops it's all internal. Perhaps we can revisit this again in the future.
