### ISSUE TITLE
Function not splitting objects properly

### ISSUE THREAD

**Issue by javiersvg** [spring-cloud/spring-cloud-function#184]
I have created a function for a stream that should obtain a message with an object that has an array in it and sends back to the stream a message for each one of the objects contained in the array.
Instead the current implementation causes only a single message to be sent down the line, the first element.
The function:
```java
@SpringBootApplication
@FunctionScan
public class App {
    
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
    
    @Bean
    public Function<Flux<ItemList>, Flux<Item>> function() {
        return f -> f.flatMap(l -> Flux.fromArray(l.getItems()));
    }
}
```

I have created a [repo](https://github.com/javiersvg/spring-fn) that reproduces the issue with two Junit tests. One that only tests the function which works fine and one that tests providing a message and obtaining a response which fails.
The the test result can be seen in [travis](https://travis-ci.org/javiersvg/spring-fn/builds/395599709).

Java: Java 1.8.0_151
Cloud dependencies: Finchley.RELEASE
Spring Dependencies:
- spring-boot-starter
- spring-cloud-function-stream
- spring-cloud-stream-binder-rabbit
- spring-boot-starter-test

Please let me know if I need to provide any further information.

**Comment by olegz** [comment]
Actually, splitting is just fine, but it returns the last Item in Flux. Looking . . .

**Comment by olegz** [comment]
Also, keep in mind that while we'll address it as a maintenance issue for 1.x the `spring-cloud-function-stream` module has been removed from the master as we are working on more robust streaming support.

**Comment by javiersvg** [comment]
Thank you very much for the rapid response. Where could I find information on the future ways to work with function and streams?

**Comment by olegz** [comment]
@javiersvg it's not available at the moment, but will be coming shortly. It's related to a new approach to a binder in general where `Flux<Message>` will be bound as close as possible to the actual source instead of via `@StreamListener' (which in your case is partial source of the problem)

**Comment by olegz** [comment]
@javiersvg just an FYI. We've just released 2.1.0.M1 of Spring Cloud Stream and are beginning to work on M2 which will include the initial convergence of spring-cloud-function and spring-cloud-stream, new binder support and few more things. So, please track it's progress both here and [spring-cloud-stream](https://github.com/spring-cloud/spring-cloud-stream).

**Comment by javiersvg** [comment]
I will thank you very much @olegz

**Comment by olegz** [comment]
I believe this has been resolved over time. Please feel free to re-open it or open new issue if you still see problems
