### ISSUE TITLE
HTTP headers conversion not working in 1.0.0.RC2

### ISSUE THREAD

**Issue by tzieleniewski** [spring-cloud/spring-cloud-function#186]
Hi Team,

I was trying to provide a function which would produce a content for HTTP endpoint.
As I needed to return the specific "application/xhtml+xml" content type I declared the function with Message<?> for both input and output.
I added the "Content-Type" header to output message headers.

As the result my HTTP client received the JSON response with "payload" element instead of expected  content type body.

I kindly ask for your support
Tomasz Krzysztof Zieleniewski

```java
    @Bean
    public Function<Message<Example>, Message<String>> function() {
        return exampleMessage -> new Message<>() {

            @Override
            public String getPayload() {
                return rendererService.render("example", exampleMessage.getPayload());
            }

            @Override
            public MessageHeaders getHeaders() {
                Map<String, Object> headers = new HashMap();
                headers.put("Content-Type", "application/xhtml+xml;charset=UTF-8");
                return new MessageHeaders(headers);
            }
        };
    }
```
```json
{
    "payload": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\r\n  ...",
    "headers": {
        "Content-Type": "application/xhtml+xml;charset=UTF-8",
        "id": "26681533-d336-673f-3146-a7b665b06417",
        "timestamp": 1530103083528
    }
}
```

**Comment by tzieleniewski** [comment]
Hi,

I would like to achive the following:

**Request processing**
HTTP POST with JSON body -> request mapped to function and body mapped to Example object

**Response processing**
Function result is mapped to HTTP response which body provided from String and Content-Type header with value of the specified MIME type.

**Comment by tzieleniewski** [comment]
PS. I've updated version to the released one.

**Comment by olegz** [comment]
Also, can you post the stack trace to avoid the confusion?

**Comment by olegz** [comment]
FWIW, here is the complete sample test that demonstrates what I believe you're trying to accomplish
```
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT, properties = {
		"spring.cloud.function.web.path=/functions", "debug" })
public class EmployeeTest {

	@LocalServerPort
	private int port;
	@Autowired
	private TestRestTemplate rest;

	@Test
	public void example() throws Exception {
		ResponseEntity<String> postForEntity = rest.postForEntity(new URI("/functions/employee"), "{\"name\":\"Bob\",\"age\":23}", String.class);
		System.out.println(postForEntity.getBody());
	}

	@EnableAutoConfiguration
	@org.springframework.boot.test.context.TestConfiguration
	protected static class TestConfiguration {
		@Bean({ "employee"})
	    public Function<Message<Employee>, Message<String>> function() {
			return request -> {
				System.out.println("Request: " + request);
				StringBuilder builder = new StringBuilder();
				builder.append("<?xml version=\"1.0\"?><employee><age>");
				builder.append(request.getPayload().getAge());
				builder.append("</age><name>");
				builder.append(request.getPayload().getName());
				builder.append("</name></employee>");
				return MessageBuilder.withPayload(builder.toString()).setHeader(MessageHeaders.CONTENT_TYPE, "application/xhtml+xml;charset=UTF-8").build();
			};
	    }
	}

	public static class Employee {
		private int age;
		private String name;
		public int getAge() {
			return age;
		}
		public void setAge(int age) {
			this.age = age;
		}
		public String getName() {
			return name;
		}
		public void setName(String name) {
			this.name = name;
		}
	}
}
```

**Comment by tzieleniewski** [comment]
I've run the test locally and the result is analogous to my case.
The HTTP response body `postForEntity.getBody()` is in the JSON format.

```json
[{"payload":"<?xml version=\"1.0\"?><employee><age>23</age><name>Bob</name></employee>","headers":{"contentType":"application/xhtml+xml;charset=UTF-8","id":"361e48f5-62cd-d7f8-7691-ae4ec961f03b","timestamp":1530187348751}}]
```

While I need to have the response body taken as `String` from the message payload and `Content-Type` header set as set in message header.

Do you have the same output?
I mean HTTP response body is in JSON format?

I am refering to the [documentation](http://cloud.spring.io/spring-cloud-static/spring-cloud-function/1.0.0.RELEASE/single/spring-cloud-function.html#_standalone_web_applications): 
> Functions and consumers that are declared with input and output in Message<?> will see the request headers on the input messages, and the output message headers will be converted to HTTP headers.

> When POSTing text the response format might be different with Spring Boot 2.0 and older versions, depending on the content negotiation (provide content type and accpt headers for the best results)._

**Comment by olegz** [comment]
@tzieleniewski we've identified the issue and it has to do with Boot 2.0/Spring 5. With previous versions of Boot (i.e., 1.5.*) you should be fine.

**Comment by tzieleniewski** [comment]
@olegz we are working with JDK9.
Are there chances for a near compatibility?

**Comment by tzieleniewski** [comment]
Yes I have overriden the dependencies.
Sorry for the confusion.
I am wondering what is the time perspective for Spring Boot 2.0.* support.

**Comment by dsyer** [comment]
I don't think JDK 9 will have any effect. If someone fixes this bug then message headers will behave the same in Spring Boot 2 apps with the web adapter.

**Comment by olegz** [comment]
Part of the issue is that the new `org.springframework.core.ReactiveAdapter` doesn't do what has been the responsibility of `FluxReturnValueHandler`. Now, that doesn't mean it's a big in webflux, however it does mean that our expectations may have been wrong. 
I am now considering to
1. (Short term) Fix the immediate bug by removing 

`@ConditionalOnMissingClass("org.springframework.core.ReactiveAdapter")` from `FluxReturnValueConfiguration` 
as well as 

```if (!ClassUtils.isPresent("org.springframework.core.ReactiveAdapter", null)) {..}``` 

from `fluxRequestMappingHandlerAdapterProcessor` configuration
2. (long term) Revisit the `org.springframework.core.ReactiveAdapter` and what should we need to do to ensure it performs the work of `FluxReturnValueHandler`.
