### ISSUE TITLE
SpringBootApiGatewayRequestHandler - AWS HTTP GET method support

### ISSUE THREAD

**Issue by ghost** [spring-cloud/spring-cloud-function#189]
When using _SpringBootApiGatewayRequestHandler_ with AWS - **HTTP GET** method throws exception "Cannot convert event". 

This line fails as request body is null.
	_Object body = deserializeBody(event.getBody());_

```
	protected Object convertEvent(APIGatewayProxyRequestEvent event) {
		Object body = deserializeBody(event.getBody());
		if (functionAcceptsMessage()) {
			return new GenericMessage<>(body, getHeaders(event));
		}
		else {
			return body;
		}
	}
```

**Comment by olegz** [comment]
So, you're saying that because of GET you don't have a body. If so what would we use to create Publisher. 
Anyway, can you elaborate a bit on what you're trying to do . . .some code etc.

**Comment by artembilan** [comment]
The `queryParams` map can be used as a default `palyoad`.
This is what we do in Spring Integration for the `WebFluxInboundEndpoint`:
```
return extractRequestBody(exchange)
		.doOnSubscribe(s -> this.activeCount.incrementAndGet())
		.switchIfEmpty(Mono.just(exchange.getRequest().getQueryParams()))
		.map(body -> new HttpEntity<>(body, exchange.getRequest().getHeaders()))
		.flatMap(entity -> buildMessage(entity, exchange))
```

Just an idea to consider...

**Comment by olegz** [comment]
Thanks @artembilan , and yes indeed we need to do something there, yet I am still waiting for @iwejay to communicate what was he trying to accomplish.

**Comment by pfrank13** [comment]
I've hit the same issue and looked at the upcoming 2.0.0.M3 which appears to have the same bug.  Using API Gateway with HTTP GET which results in a null body and ends up with a NPE when trying to be deserialized.  I believe @iwejay has provided enough info but I can too if needed, also thanks to @artembilan as well as @iwejay because that workaround worked for me too.

**Comment by olegz** [comment]
Given the age of this issue and the amount of new features and improvements that went into AWS adapter I am going to close this issue, but please feel free to raise a new one [based on our current support](https://docs.spring.io/spring-cloud-function/docs/3.1.3/reference/html/aws.html).
