### ISSUE TITLE
Add support for function count in FunctionCatalog

### ISSUE THREAD

**Issue by olegz** [spring-cloud/spring-cloud-function#202]
This would be helpful when used by other frameworks. For example in SCSt we could use it to omit function definition property if catalog only has one function, thus making it a default

**Comment by dsyer** [comment]
This can be derived from `FunctionCatalog.getNames()`. I don't like adding convenience methods to interfaces.

**Comment by dsyer** [comment]
I don’t like this change much, I must say. What is the problem it is trying to solve?
