### ISSUE TITLE
website with broken link to openwhisk adapter 

### ISSUE THREAD

**Issue by csantanapr** [spring-cloud/spring-cloud-function#209]
https://cloud.spring.io/spring-cloud-function/#quick-start

If you click on OpenWhisk link is broken:
https://github.com/spring-cloud/spring-cloud-function/tree/master/spring-cloud-function-samples/function-sample-openwhisk

It should point to the adapter folder
https://github.com/spring-cloud/spring-cloud-function/tree/master/spring-cloud-function-adapters/spring-cloud-function-adapter-openwhisk

This looks like a duplicate of #145 

How can I help or submit a PR to update the website?

**Comment by olegz** [comment]
Fixed with https://github.com/spring-cloud/spring-cloud-function/commit/e54187c099cefbf0e77fe5a3204cfd8ed39fc713
