### ISSUE TITLE
Issue running cloud functions locally

### ISSUE THREAD

**Issue by michaelruocco** [spring-cloud/spring-cloud-function#220]
Hi,

I have recently begun experimenting with spring cloud functions and so far have made reasonable headway. I have run into an issue trying to call one of my functions locally and I suspect that I just have something configured incorrectly but I am not 100% what it might be.

I have created an example project that recreates the issue here: https://github.com/michaelruocco/spring-cloud-function. The details are described in the README, but basically I am using serverless to deploy my cloud functions to AWS lambda running behind API Gateway, and when I deploy to AWS everything works perfectly well.

However, when I try to run the same code locally (passing a request that is a cut down version of what is getting sent from the API gateway when running in AWS) I am finding that the request body is not being parsed / populated correctly before being passed into my functions. The issue can be recreated locally, by following the instructions listed in the README of the project linked above.

Any insight or suggestions you can offer would be much appreciated.

Thanks.

**Comment by olegz** [comment]
@michaelruocco I am looking at it now as it doesn't seem right. Thanks for contributing a failing test, should make it easier to diagnose.

**Comment by olegz** [comment]
@michaelruocco while we're looking into this could you please upgrade to the latest version 2.0 (snapshot, the release is coming shortly anyway). Here have been significant changes/enhancements in both boot, and functions, so would be nice to see if problem still exists

**Comment by olegz** [comment]
@michaelruocco while we're looking could you please upgrade to 2.0 latest snapshot and see if the problem persists?

**Comment by olegz** [comment]
@michaelruocco the issue is with the type conversion of the `Message` in _spring-cloud-function-web_ module. If you change your `Greet` and `Reverse` to have a simpler signature (see below)
```java
public class Greeter implements Function<Request, Response> {
    @Override
    public Response apply(Request request) {
        return new Response("Hello " + request.getValue() + ", and welcome to Spring Cloud Function!!!");
    }
}
```
. . . you should be fine.
We will consider addressing it, but I would also recommend to switch to 2.0 branch. I know it's still a snapshot but we're very close to the release.

**Comment by michaelruocco** [comment]
Hi @olegz,

Thanks for the quick response, I will give that change a try, however I am not sure how I would access the request headers or set the response headers using this approach.

When you mention upgrading to the 2.0 snapshot version, do you mean of spring-cloud-starter-function-web, or spring-cloud-function-adapter-aws or both? Do I need to add a different repository to my pom.xml in order to pull the snapshot version? Sorry if the questions are a bit basic, I am more comfortable and familiar with gradle rather than maven, but I could find may spring-cloud-function examples using gradle.

Thanks.

**Comment by michaelruocco** [comment]
Hi @olegz,

I have updated the repo here: https://github.com/michaelruocco/spring-cloud-function to use version 2.0.0.BUILD-SNAPSHOT, however the problem still seems to be persisting I'm afraid.

I have also updated the reverse function to remove the type conversion of message as suggested, however that endpoint is still failing too, I have tried with both the 1.0.1.RELEASE version I was using previously and the 2.0.0.BUILD-SNAPSHOT and both are still not picking up the value field even with the suggested change applied.

If you can point me in the general direction of the classes that may contain the problem I am happy to try and investigate further myself if it helps?

Thanks.

**Comment by michaelruocco** [comment]
Hi @olegz,

Just as an update, I have now updated the example repo with a version that works both locally and AWS.

It has required me to remove the use of the SpringBootApiGatewayRequestHandler and is using  SpringBootRequestHandler<APIGatewayProxyRequestEvent, APIGatewayProxyResponseEvent> instead. Additionally I have created an abstract function that does the translation between the APIGatewayProxyRequest into a simpler request object which returns the body parsed into an object along with and request headers, query string params and path params.

It is a little convoluted and requires a bit more work than I would have liked but it is working for me now, however the original bug still remains. I think I will need to stick to my new approach as I need access to the path params to implement REST API's the spring message class would not give access to these even if it was working correctly locally.

Thanks.

**Comment by dsyer** [comment]
The `SpringBootApiGatewayRequestHandler` should be working. We can try and analyse the problem by going back to an old commit in your repo, if you like.

**Comment by michaelruocco** [comment]
Gah I feel stupid now, you are quite right, I can roll back and it works as expected, and I am able to get at the APIGatewayProxyRequestEvent now as you suggested. Thanks @dsyer!

Last question hopefully, when building a REST API I would often need access to the path parameters to get things like resource IDs. If the message header containing the APIGatewayProxyRequestEvent is null when running locally, is there some other way to access things like path parameters?

**Comment by dsyer** [comment]
What do you mean by "path parameters"? It sounds like an anti-pattern really, tying your function to HTTP, but we can try to accommodate by adding headers to the `Message`. I'm not sure what you need really. What's your use case?

**Comment by michaelruocco** [comment]
The simplest example would be that I have a REST API designed to return a widget in the standard way by resource ID, so the request url would be something like:
```
GET https://3dxfd4c7pd.execute-api.eu-west-1.amazonaws.com/dev/widgets/{id}
```
The in the function I would need to be able to access the {id} value in order to be able to read the details from a database. In the APIGatewayProxyRequestEvent there is a field called pathParameters which stores these values in a map.

Additionally I would also have requirements to be able to access query string parameters in the same way on certain requests too. The work around that I put in place gives me access to both of these if required, but obviously it is a bit more work and a bit messier.

**Comment by olegz** [comment]
I believe this has already been addressed with adding support for `Message` type. Please look at [this test](https://github.com/spring-cloud/spring-cloud-function/blob/master/spring-cloud-function-adapters/spring-cloud-function-adapter-aws/src/test/java/org/springframework/cloud/function/adapter/aws/SpringBootApiGatewayRequestHandlerTests.java#L89) and feel free to reopen or open a new one if you still have issues/questions.
