### ISSUE TITLE
Kotlin function bean is not available in the FunctionRegistry

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-function#224]
I have a kotlin function bean in my configuration and when I try to lookup for this bean by the function `name` and type `Function` it is not available in the FunctionRegistry's `functions`.

I see that the `KotlinLambdaToFunctionAutoConfiguration`'s bean post processor transforms the kotlin lamda into java.util.Function but the registry is not updated with this transformed Function.

Please note that this happens irrespective of whether I have other non-kotlin function beans registered.

**Comment by olegz** [comment]
I did discuss it with @ilayaperumalg and it appears to be ordering issue where kotlin function is registered a bit too late and not available during the composition (e.g., `java_func|kotlin_func`).

**Comment by olegz** [comment]
@ilayaperumalg I just committed a test that validates that everything works as expected. So we need to look closely into what you're doing and see what's going on.
