### ISSUE TITLE
Type conversion does not take content-type into account

### ISSUE THREAD

**Issue by olegz** [spring-cloud/spring-cloud-function#228]
The following will result in the attempt to convert to Map
```
ResponseEntity<String> result = rest.exchange(RequestEntity
				.post(new URI("http://localhost:" + port + "/"))
				.contentType(MediaType.TEXT_PLAIN).body("{\"value\":\"foo\"}"),
				String.class);
```
. . . resulting in something like this
```
java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to java.lang.String
	at org.springframework.cloud.function.core.IsolatedFunction.apply(IsolatedFunction.java:47) ~[classes/:na]
	at org.springframework.cloud.function.core.FluxFunction.lambda$0(FluxFunction.java:47) ~[classes/:na]
	
```

This happens especially when the type can not be determined and remains as `Object`.
Also, based on the logic in `RequestProcessor` it appears json arrays will always be converted regardless of determination of the input type

**Comment by dsyer** [comment]
It's not literally true that content-type is not taken into account - there are several special cases already for form data, multipart, and binary. I think you just mean that in the specific case you were trying the text/plain type was ignored.

**Comment by olegz** [comment]
@dsyer Actually here are several cases:

1. Typeless function
```
@Bean
public Function<?,?> typelessFunction() {
		return value -> value;
}
. . .
rest.exchange(RequestEntity
		.post(new URI("/typelessFunction")).contentType(MediaType.TEXT_PLAIN)
		.body("[{\"value\":\"foo\"},{\"value\":\"bar\"}]"), String.class);
```
In the above case the input to the function will be List (or Map if you pass just a map) even though IMHO it should not be _raw_ body since input type could not be determined.

2. Function with String input
```
@Bean
public Function<String,?> typelessFunction() {
		return value -> value;
}
. . .
rest.exchange(RequestEntity
		.post(new URI("/typelessFunction")).contentType(MediaType.TEXT_PLAIN)
		.body("[{\"value\":\"foo\"},{\"value\":\"bar\"}]"), String.class);
```
In the above case you basically end up with
`java.lang.IllegalArgumentException: Cannot convert JSON [{"value":"foo"},{"value":"bar"}]` 
Also, _content-type_ is completely irrelevant here and can be anything.
However if the input string was not an array, but a map (e.g., `{\"value\":\"foo\"}`), then all is good, so obviously an error. That is actually truly a bug due to the order of `IFs` in `RequestProcessor.post(..)`.

The main point here is that setting an explicit content type should communicate _how/if_ we should perform the conversion as a _supplement_ to knowing (or not) the actual type of the input parameter.  And in the event type can not be determined and CT is explicitly set to `text*` we should   simply pass the raw body which in this particular case is `String'.
