### ISSUE TITLE
how to set response codes or handle errors?

### ISSUE THREAD

**Issue by ssjman** [spring-cloud/spring-cloud-function#230]
How to I send different http response codes based on different errors that occur in the function?

**Comment by dsyer** [comment]
That depends on where the function is deployed. It will be different for AWS than for a natively deployed function with spring-cloud-function-web, for instance.

**Comment by ssjman** [comment]
I am fairly new to this so I am sorry if I don't understand completely.  

I have a spring-cloud-function that returns a Flux<CustomObect>.  When I run this locally or from cloud foundry and I use postman to hit the endpoint that is created for the function I will get my object back.  But if I change my request so that I throw an exception in the function logic I will get a 500 with the error message I pass to the exception.  

I found out I can create a custom exception and use the @ResponseStatus annotation to set the response status to what I want and throw my custom error that I get the response status I would like.  However that does not let me change the body of the response I am sending.

I am not sure how that would change based on where the function is deployed and maybe I am looking at it wrong.  I am thinking of the function as a basic rest endpoint at the end of the day.

**Comment by dsyer** [comment]
If you are using the `spring-cloud-function-web` adapter you are running a Spring Boot application (either MVC or Webflux depending on what you put on the classpath in 2.0) so all the docs on how to change HTTP error responses from the [Spring Boot User Guide](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#boot-features-error-handling) would be applicable.

**Comment by ssjman** [comment]
Thanks I believe that will work for me.  I was looking at https://www.baeldung.com/exception-handling-for-rest-with-spring just before your comment.  

Thanks again!

**Comment by olegz** [comment]
@ssjman I am closing this issue as I believe you got your answer/solution. If it is not correct feel free to reopen it or raise a new one.
