### ISSUE TITLE
Add support for routing/gateway function

### ISSUE THREAD

**Issue by pellyadolfo** [spring-cloud/spring-cloud-function#238]
NOTE: The original title has been modified since this is a feature that goes beyond AWS

Hi,

I am reopening this issue (https://github.com/spring-cloud/spring-cloud-function/issues/203) because it looks that whoever closed it either did not understand the purpose or maybe I am missing something.

The goal would be having multiple functions served in the same AWS Lambda Function. Currently, as far as I know, FUNCTION_NAME can be used to configure the function within the set of functions in the Spring Cloud Function Project. Documentation says:

_If your app has more than one @Bean of type Function etc. then you can choose the one to use by configuring function.name (e.g. as FUNCTION_NAME environment variable in AWS)._

The problem is that only one of them can be configured at a time. So, 2 questions:

* what is the value of having a multi function Spring Cloud Function project if only one of them can be configured in AWS at a time?

* I already have multiple URLs simultaneously configured for a single Lambda Function with a NodeJS project built on ExpressJS. Every URL is a different ExpressJS route and multiple can be served from the same Lambda Function at the same time. It looks NodeJS+ExpressJS technology is beyond Spring Cloud Function?

Thanks,

**Comment by pellyadolfo** [comment]
Here there is a sample of routing mechanism for native AWS Lambda Handlers https://stackoverflow.com/questions/41425511/aws-api-gateway-lambda-multiple-endpoint-functions-vs-single-endpoint/41428226#41428226

**Comment by olegz** [comment]
So would it be true to say that what you're asking is to have a RouterFunction which is a subset of Function that let's say returns the name of the actual function that needs to be invoked?
