### ISSUE TITLE
Error handling and DLQ process does not works in function Consumer<Flux<T>> Sink application

### ISSUE THREAD

**Issue by msshitole** [spring-cloud/spring-cloud-function#239]
This issue is related to the error handling in the **Spring reactive cloud stream**. Please note that, Reactive programming model has been adapted via Spring Cloud Function Supplier/Function/Consumer function methodology.

As per the Error Handling documentation in the Spring cloud stream. The exception must be thrown to the binder and then the failed message must go to the DLQ topic via errorChannel. 

**When error/exception occurs during the reactive stream. The Flux gets cancelled.**
Here the example usecase 
`
@SpringBootApplication
@EnableBinding(Sink.class)
public class ReactiveStreamSinkApplication {

    public static void main(String[] args) {
        SpringApplication.run(ReactiveStreamSinkApplication.class,
                "--spring.cloud.stream.function.definition=myConsumer");
    }

    @Bean
    public Consumer<Flux<String>> myConsumer() {

        return stream -> stream.log()
                               .subscribe(value -> {
            if ("foo".equalsIgnoreCase(value)) {
                throw new RuntimeException("BOOM!");
            }
            System.out.println("Received value: " + value);
        });

    }

    @StreamListener("errorChannel")
    public void error(ErrorMessage message) {
        // log the error
        System.out.println("Handling ERROR: " + message);
    }

    /**
     * Processing msgs from the DLQ
     * @param failedMessage
     */
    @KafkaListener(id= "errId", topics = "dlq-topic")
    public void rePublish(Message failedMessage) {
        //we can write to a database or move to a parking lot queue
        System.out.println("Writing to database: "+failedMessage.getPayload());
    }

}
`
**Here are my config details in the application.properties**

> spring.cloud.stream.kafka.bindings.input.consumer.enableDlq=true
> spring.cloud.stream.kafka.bindings.input.consumer.dlqName=dlq-topic

This is very basic and simple error handling usecase most users wanted and the same approach works fine for the non-reactive pipeline. Kindly request you to prioritise this.

We are expecting to process millions document via the reactive pipeline using Spring Cloud Functions. And hence this error-handling usecase is very important for us.

Just For reference, here is the sample project available in the GitHub. 
 https://github.com/msshitole/spring-cloud-function-sink-app.git

Your help will be highly appreciated. Thank you in advance!

**Comment by olegz** [comment]
@msshitole when you declare your function as `Function<Flux<String>, Flux<String>>` you are essentially taking full control of the invocation, error handling etc. That is different when Spring Cloud Function transforms `Function<String, String>` to `Function<Flux<String>, Flux<String>>`. The same applies to Consumer.

Also, regardless of what I just said this question is not related to Spring Cloud Function; rather Spring Cloud Stream, so if you still think this is an issue please re-open it there.

**Comment by msshitole** [comment]
@olegz Thanks for putting your views on this long pending issue and giving clarity on this.

I agree. Here we need to take care of the error handling since its `<Flux<String>, Flux<String>>`.
And this issue is related to the spring cloud stream. I raised it here because, we have chosen spring cloud function as our reactive cloud stream. 

I will reopen this issue in spring cloud stream. Rather I would say it's new feature request for the reactive stream - "Error handling in reactive stream via simple configurations same like non-reactive stream".

As of now, we are working on the error handling. We will propose the ideas over github and then hopefully this will be considered as feature request. Thank you in anticipation.

**Comment by olegz** [comment]
Actually, let's maintain discussion [here](https://github.com/spring-cloud/spring-cloud-function/issues/243). Basically I am now thinking of introducing a proxy-like wrapper that would allow us some level of lifecycle/error control. Need to spike it up but if you're interested it would be nice to have someone to review the ongoing work
