### ISSUE TITLE
Not able to run the function from AWS lambda

### ISSUE THREAD

**Issue by renjithlalp** [spring-cloud/spring-cloud-function#240]
I deployed the function-sample-aws in AWS lambda, but not able to run 

The error is : 

{
  "errorMessage": "Class org.springframework.cloud.function.adapter.aws.SpringBootRequestHandler does not implement RequestHandler with concrete type parameters: parameter E has no upper bound."
}

**Comment by pellyadolfo** [comment]
You need to create a handler of your own and refer it in the Lambda screen configuration instead of the Spring Cloud Function one, e.g.:

public class MyStringHandlers extends SpringBootRequestHandler<String, String> {}

Look for MyStringHandlers here https://www.baeldung.com/spring-cloud-function

**Comment by olegz** [comment]
This seem to be answered already, but please feel free to reopen providing  additional details if you believe there is still an issue
