### ISSUE TITLE
Consider wrapping Fluxed functions

### ISSUE THREAD

**Issue by olegz** [spring-cloud/spring-cloud-function#243]
Recently and primarily for consistency sake we've added [FluxedConsumerWrapper](https://github.com/spring-cloud/spring-cloud-stream/commit/1a7548fcf045e9082cb8f086ebb905fa88875652) wrapper for` Consumer<Flux>` in Spring Cloud Stream (SCSt). 
While it provided certain conveniences in SCSt there are other possible implications which we probably need to spike out. For example, if you look at this discussion, due to the fact that are typically do almost nothing if user declares fluxed function there are potential for lifecycle issues. 
So, providing some type of light weight wrapper may help to expose certain spring hooks to Flux

**Comment by msshitole** [comment]
Sure! That would be nice. In fact, I was also thinking on the same line of putting some wrapper so we can have better control in case of error handling.

To make it simple, currently, we will be working on in hand in hand with the Flux's API's onErrorContinue and SCSt's error channels and kafkaListneres. Let's do our best and make reactive cloud stream great again via SCF :) Let us work together. Hope for the best!
