### ISSUE TITLE
Provide a way to set a main bean/handler for a SCFn Boot web app

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-function#247]
Looking for a way to specify a bean name to use as the main function mapped to the root path `/` for the web app. It would also be nice to support composition so I could set the main handler to be a chain of functions like `square,format,upper`.

**Comment by olegz** [comment]
We have something similar already in stream. In fact the entire support in stream is based on pointing to a single function which itself could be single or composed.

**Comment by dsyer** [comment]
We need to clarify, but I expect this is intended to be a main handler on the default (root or "/") path. Also, note that the "fat" (non-functional) forms of spring-cloud-function-web also already support serving a single *unique* function from the root path. So this new feature is just to support a specific non-unique function on the same path.

The "functional" form of web apps also already has this, as does the "deployer" (both of which were ideas copied from Riff). The configuration property name there is `function.handler`, but arguably it should be `spring.cloud.function.handler`.

**Comment by olegz** [comment]
Right and just as an example in stream we have `spring.cloud.stream.function.definition=foo|bar|baz`. 

I like `definition` since it makes more sense in the context of composition.
