### ISSUE TITLE
Azure function validation 

### ISSUE THREAD

**Issue by abhinav-jain09** [spring-cloud/spring-cloud-function#248]
Hello Guys,

I am trying to implement Azure function with spring boot adaptor but do not understand how can I validate the Request parameters. what is the way to validate if request parameters or not null or another validation

**Comment by dsyer** [comment]
What are "Request parameters" in this case precisely? Did you know you can access the AWS native request event via `Message` headers? I think the HTTP query parameters are in there, if that's what you mean.

**Comment by dsyer** [comment]
Update: I misread your description. The Azure (as opposed to AWS) adapter does not automatically convert the input to a `Message`. It probably could if anyone wants to implement that, and then the HTTP request properties could be added as headers.

**Comment by olegz** [comment]
There have been many improvements and [documentation updates for Azure](https://docs.spring.io/spring-cloud-function/docs/3.1.2/reference/html/azure.html), so I'll close this given its age but feel free to try and raise new issues as you discover them.
