### ISSUE TITLE
aws Lambda slow start

### ISSUE THREAD

**Issue by lramamoo** [spring-cloud/spring-cloud-function#254]
I am running a spring cloud function in aws lambda. But the startup time of the function is high around 15s.

When I increase the lambda  memory size to 2000MB, function starts in max 4s.

Is there any way to reduce this cold start time?

**Comment by dsyer** [comment]
Use functional bean definitions. Increase the memory allocation (AWS gives you more CPU then). See here for more detail: https://spring.io/blog/2018/10/22/functional-bean-registrations-in-spring-cloud-function

**Comment by olegz** [comment]
I think we can close this given that [Function Bean Definitions](https://cloud.spring.io/spring-cloud-static/spring-cloud-function/2.1.0.M1/spring-cloud-function.html#_functional_bean_definitions) are pretty well covered in the user guide. 
Please let us know if you believe something is still missing
