### ISSUE TITLE
Guidance: HTTP GET, PUT, DELETE support

### ISSUE THREAD

**Issue by ncoonghe** [spring-cloud/spring-cloud-function#255]
I wasn't able to use HTTP GET to call a function, especially using the Supplier. It didn't seem to work. I was only able to get "functions" to work with HTTP POST. There is no proper documentation nohow Supplier interface can be used. I created a Supplier implementing the get interface, but was not able to invoke the get interface using HTTP GET. Any information on how to enable the Supplier mode with HTTP GET will be appreciated. Also, there seems to be no support for PUT and DELETE.

**Comment by markusgulden** [comment]
@ncoonghe, I had the same problem (actually, I just wanted to try whether my functions implemented for AWS Lambda would also run as Spring Boot app without modifications).
What you would have to do is to implement your custom versions of [https://github.com/spring-cloud/spring-cloud-function/blob/v2.0.0.RELEASE/spring-cloud-function-web/src/main/java/org/springframework/cloud/function/web/mvc/FunctionController.java](FunctionController) and [https://github.com/spring-cloud/spring-cloud-function/blob/v2.0.0.RELEASE/spring-cloud-function-web/src/main/java/org/springframework/cloud/function/web/mvc/FunctionHandlerMapping.java](FunctionHandlerMapping).
I created a quick tutorial [here](https://masteringaws.blogspot.com/2019/02/spring-cloud-functions-spring-boot.html).

**Comment by ncoonghe** [comment]
@markusgulden Thanks. Hopefully, it can be provided as standard functionality

**Comment by olegz** [comment]
Actually I am not quite sure what this is about. We certainly support  GET and POST and there are plenty of samples for it. I must be missing something, am I?

**Comment by markusgulden** [comment]
@olegz , my comment above mainly referred to the missing support of PUT and DELETE.
However, I also was not able to call a Function via GET request (which actually is required if I want to pass something like HTTP path parameters to the function). This is why I hacked the [FunctionController](https://github.com/markusgulden/aws-tutorials/blob/master/spring-cloud-function/spring-cloud-function-spring-boot/src/main/java/de/margul/awstutorials/springcloudfunction/springboot/RestfulFunctionController.java#L73).

On the other points, the issue author should provide more information.

**Comment by ncoonghe** [comment]
@markusgulden @olegz 
is there support for path parameters with POST and GET ?

**Comment by chaudharydeepak** [comment]
It is 2021 and I am the only 1 looking for full-fledged REST API support with spring cloud functions? With spring native getting mature, I think more developers will be more interested in the option to writing REST API's [ with classic support for GET PUT POST PATCH DELETE ] using spring cloud functions. I am happy to open new thread if this is too old. Thank for your wonderful work.

**Comment by Premier** [comment]
Do we have updates?
Is there a way to get the HTTP method used to hit the function?

Thank you
