### ISSUE TITLE
Support for function composition in functional bean definitions

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-function#261]
Related to #246. The functional style uses an `InMemoryFunctionCatalog` which doesn't have support for composition. Not sure why (probably just didn't get round to it).

**Comment by olegz** [comment]
@dsyer I'll take it as it is related to the conversation you and i had recently and some of the recent changes I did. Some of those changes could be considered in preparation to doing exactly what this issue requests
