### ISSUE TITLE
On sam local/aws, I got "No Function Defined" with Supplier defined and function.name set to my Supplier's bean name

### ISSUE THREAD

**Issue by kleung** [spring-cloud/spring-cloud-function#263]
I got "No Function Defined" where I deploy my code to sam local.  I made sure there is only 1 bean that implements java.util.Supplier, and have the function.name pointing to this bean's name.

(On a side note, when I run it as stand alone web project with spring-cloud-starter-function-web, everything is fine)

I tried to debug it under sam local, I think its org.springframework.cloud.function.adapter.aws.SpringFunctionInitializer line 98 to 104 and 
org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration's lookup method (line 130 to 151)
where the framework is trying to look for java.util.Function type with the given bean name, while my bean is a java.util.Supplier.

I hope somebody can help me on this and please correct me if I am mistaken.

Thanks in advance!

**Comment by olegz** [comment]
Hey @kleung could you please try it again with the latest master snapshot? 
The `org.springframework.cloud.function.adapter.aws.SpringFunctionInitializer` has had some major surgery lately, so the problem may no longer be there.
Please let us know

**Comment by kleung** [comment]
Hi @olegz , got it, will test it out these few days and get back to you.  Thanks a lot!

**Comment by kleung** [comment]
Hi @olegz ,

Unfortunately, I cannot test the adapter on aws, there are 2 problems I found:

1. org.springframework.cloud.function.adapter.aws.CustomRuntimeInitializer depends on org.springframework.cloud.function.web.source.DestinationResolver, which is from spring cloud function web - may cause tomcat to start if users are not aware of it

2. I get the following stacktrace from aws response even I added dependencies and shaded the jar, am I missing something in the pom.xml?
{
  "errorMessage": "Error creating bean with name 'org.springframework.cloud.function.adapter.aws.CustomRuntimeAutoConfiguration': Initialization of bean failed; nested exception is java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy",
  "errorType": "org.springframework.beans.factory.BeanCreationException",
  "stackTrace": [
    "org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:601)",
    "org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)",
    "org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)",
    "org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)",
    "org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)",
    "org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)",
    "org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:849)",
    "org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)",
    "org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)",
    "org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)",
    "org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)",
    "org.springframework.boot.SpringApplication.run(SpringApplication.java:316)",
    "org.springframework.cloud.function.context.AbstractSpringFunctionAdapterInitializer.initialize(AbstractSpringFunctionAdapterInitializer.java:114)",
    "org.springframework.cloud.function.adapter.aws.SpringBootRequestHandler.handleRequest(SpringBootRequestHandler.java:49)",
    "org.springframework.cloud.function.adapter.aws.SpringBootApiGatewayRequestHandler.handleRequest(SpringBootApiGatewayRequestHandler.java:130)",
    "org.springframework.cloud.function.adapter.aws.SpringBootApiGatewayRequestHandler.handleRequest(SpringBootApiGatewayRequestHandler.java:40)"
  ],
  "cause": {
    "errorMessage": "sun.reflect.annotation.TypeNotPresentExceptionProxy",
    "errorType": "java.lang.ArrayStoreException",
    "stackTrace": [
      "sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)",
      "sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)",
      "sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)",
      "sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)",
      "sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)",
      "sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)",
      "java.lang.Class.createAnnotationData(Class.java:3521)",
      "java.lang.Class.annotationData(Class.java:3510)",
      "java.lang.Class.createAnnotationData(Class.java:3526)",
      "java.lang.Class.annotationData(Class.java:3510)",
      "java.lang.Class.getAnnotation(Class.java:3415)",
      "java.lang.reflect.AnnotatedElement.isAnnotationPresent(AnnotatedElement.java:258)",
      "java.lang.Class.isAnnotationPresent(Class.java:3425)",
      "org.springframework.core.annotation.AnnotatedElementUtils.hasAnnotation(AnnotatedElementUtils.java:599)",
      "org.springframework.aop.support.annotation.AnnotationClassFilter.matches(AnnotationClassFilter.java:65)",
      "org.springframework.aop.support.AopUtils.canApply(AopUtils.java:225)",
      "org.springframework.aop.support.AopUtils.canApply(AopUtils.java:288)",
      "org.springframework.aop.support.AopUtils.canApply(AopUtils.java:269)",
      "org.springframework.aop.framework.AbstractAdvisingBeanPostProcessor.isEligible(AbstractAdvisingBeanPostProcessor.java:133)",
      "org.springframework.aop.framework.AbstractAdvisingBeanPostProcessor.isEligible(AbstractAdvisingBeanPostProcessor.java:115)",
      "org.springframework.aop.framework.autoproxy.AbstractBeanFactoryAwareAdvisingPostProcessor.isEligible(AbstractBeanFactoryAwareAdvisingPostProcessor.java:70)",
      "org.springframework.aop.framework.AbstractAdvisingBeanPostProcessor.postProcessAfterInitialization(AbstractAdvisingBeanPostProcessor.java:85)",
      "org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:429)",
      "org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766)",
      "org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)",
      "org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)",
      "org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)",
      "org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)",
      "org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)",
      "org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)",
      "org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:849)",
      "org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)",
      "org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)",
      "org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)",
      "org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)",
      "org.springframework.boot.SpringApplication.run(SpringApplication.java:316)",
      "org.springframework.cloud.function.context.AbstractSpringFunctionAdapterInitializer.initialize(AbstractSpringFunctionAdapterInitializer.java:114)",
      "org.springframework.cloud.function.adapter.aws.SpringBootRequestHandler.handleRequest(SpringBootRequestHandler.java:49)",
      "org.springframework.cloud.function.adapter.aws.SpringBootApiGatewayRequestHandler.handleRequest(SpringBootApiGatewayRequestHandler.java:130)",
      "org.springframework.cloud.function.adapter.aws.SpringBootApiGatewayRequestHandler.handleRequest(SpringBootApiGatewayRequestHandler.java:40)"
    ]
  }
}

**Comment by olegz** [comment]
The exceptions seems to point to some incompatibilities. Could you please your dependency tree?

**Comment by kleung** [comment]
Most likely, this is my first time working with non-RELEASE builds, should I simply checkout the entire repo, build it locally and use the 2.1.0-BUILD-SNAPSHOT starters?

**Comment by olegz** [comment]
Yes, that is what I would do. 
That said, pointing to the latest snapshot should work as well, hence my question about seeing your dependency tree

**Comment by kleung** [comment]
Hi @olegz ,
I tested all Supplier, Function and Consumer, and these are the following results:

Supplier: works as expected

Function<String, String>: works when I post a json body to aws api gateway

Function<TestData, String>: works when I post the following to aws api gateway
{
	"strVal":"test for consumer"
}

Consumer<TestData>: fails when I post a json body the following(consumer takes a serializable bean and store to dynamodb):
{
	"strVal":"test for consumer"
}
with the following stacktrace:

Cannot convert event: java.lang.IllegalStateException
java.lang.IllegalStateException: Cannot convert event
	at org.springframework.cloud.function.adapter.aws.SpringBootApiGatewayRequestHandler.deserializeBody(SpringBootApiGatewayRequestHandler.java:77)
	at org.springframework.cloud.function.adapter.aws.SpringBootApiGatewayRequestHandler.convertEvent(SpringBootApiGatewayRequestHandler.java:59)
	at org.springframework.cloud.function.adapter.aws.SpringBootApiGatewayRequestHandler.convertEvent(SpringBootApiGatewayRequestHandler.java:40)
	at org.springframework.cloud.function.adapter.aws.SpringBootRequestHandler.handleRequest(SpringBootRequestHandler.java:50)
	at org.springframework.cloud.function.adapter.aws.SpringBootApiGatewayRequestHandler.handleRequest(SpringBootApiGatewayRequestHandler.java:130)
	at org.springframework.cloud.function.adapter.aws.SpringBootApiGatewayRequestHandler.handleRequest(SpringBootApiGatewayRequestHandler.java:40)
Caused by: java.lang.NullPointerException
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:889)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
	at org.springframework.cloud.function.adapter.aws.SpringBootApiGatewayRequestHandler.deserializeBody(SpringBootApiGatewayRequestHandler.java:74)
	... 5 more

**Comment by olegz** [comment]
Well, that's a good news I suppose. You certainly not getting _No Function Defined_ anymore but we need to fix the _Consumer_ issue

**Comment by cbuehler** [comment]
After having another close look, I could remove the workaround by adding the following to my `build.gradle`:
```groovy
import com.github.jengelman.gradle.plugins.shadow.transformers.*
shadowJar {
    transform(PropertiesFileTransformer) {
        paths = ['META-INF/spring.factories']
    }
}
```

**Comment by olegz** [comment]
@cbuehler That is actually correct since it uses `ApplicationInitializer`, essentially registering smaller subset of beans while nothing gets picked up from auto-configutration (intentionally).

Also, could you possibly post a link to your app that reproduces the issue. I'd love to compare few things.

**Comment by kleung** [comment]
Hi both,

Sorry I had been very busy and couldn't respond... I just want to point out that, my testes were done in SpringBootApplication instead of ApplicationInitializer, so bean subset registration shouldn't be the cause of my situation.

**Comment by olegz** [comment]
I've added additional tests for Supplier and Consumer and everything seems to be working as expected. 

Feel free to reopen it with additional details if you believe there is still an issue.
