### ISSUE TITLE
Support mapping Supplier and Consumer to Azure function

### ISSUE THREAD

**Issue by hagaic** [spring-cloud/spring-cloud-function#264]
Please add support for mapping a Supplier/Consumer Bean to an Azure function using Spring Cloud Function 2.0. 
There is no clear way of mapping a Bean like:
```
@Bean
public Supplier<List<String>> foo() {
    return () -> Arrays.asList("foo1", "foo2");
}
```
class AzureSpringBootRequestHandler has two type parameters: input and output, and AzureSpringBootRequestHandler.handleRequest() signature also expects the input parameter.

see also https://stackoverflow.com/questions/54788858/spring-cloud-function-how-to-map-a-supplier-to-azure-function

P.S Ideally I would also like to be able to use a Runnable Bean (no input or output), but this seems completely unsupported.

**Comment by olegz** [comment]
Initial support was added so basically you can do the following:

```
@Test
public void supplierNonFluxBean() {
	AzureSpringBootRequestHandler<Void, List<String>> handler = handler(NonFluxSupplierConfig.class);
	List<String> result = handler.handleRequest(new TestExecutionContext("supplier"));

	assertThat(result).isNotEmpty();
	assertThat(result.toString()).isEqualTo("[foo1, foo2]");
}
```

Similar approach goes for the Consumer

We can probably consider improving signature to avoid explicitly mentioning `Void`, but I wanted to get something out there to try before getting too deep
