### ISSUE TITLE
Support Logging in Spring Cloud Function deployed as Azure function

### ISSUE THREAD

**Issue by hagaic** [spring-cloud/spring-cloud-function#265]
Please add support for logging in spring cloud function deployed as Azure function.
There seems to be no way to get hold of the Azure context logger, once in the Function Bean.
Using slf4j the logging seems to work only locally, but when deploying to Azure and running from Azure portal - the logging doesn't appear in the Azure console.

**Comment by olegz** [comment]
Now you can simply do this:
```
@Bean
public Function<Foo, Bar> uppercase(ExecutionContext targetContext) {
	return foo -> {
		targetContext.getLogger().info("Invoking 'uppercase' on " + foo.getValue());
		return new Bar(foo.getValue().toUpperCase());
	};
}
```

**Comment by hagaic** [comment]
@olegz I tried that and I get:

 UnsatisfiedDependencyException: Error creating bean ... Unsatisfied dependency expressed through method ... parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.microsoft.azure.functions.ExecutionContext' available: expected at least 1 bean which qualifies as autowire candidate.

Do I need to update maven version of spring-cloud-function-adapter-azure-version or anything else?

**Comment by hagaic** [comment]
@olegz It seems the execution context injection is supposed to work as of 2.1.0.RELEASE, but unfortunately these versions seem to suffer from a problem with finding the start-class.

Exception: IllegalArgumentException: Failed to locate main class
Stack: java.lang.IllegalStateException: Failed to discover main class. An attempt was made to discover main class as 'MAIN_CLASS' environment variable, system property as well as entry in META-INF/MANIFEST.MF (in that order).

...

at org.springframework.cloud.function.context.AbstractSpringFunctionAdapterInitializer.getStartClass(AbstractSpringFunctionAdapterInitializer.java:279)

see also: 
https://stackoverflow.com/questions/55621375/azure-function-with-spring-boot-spring-cloud-function-unable-to-locate-main-cl

any advice?

**Comment by olegz** [comment]
@hagaic Can you please upgrade to 2.1.1.RELEASE as I believe there were some changes related to that.
Also, would it be possible to post a sample somewhere in github with instructions so I can reproduce it?

**Comment by hagaic** [comment]
@olegz 2.1.1.RELEASE also causes "Failed to locate main class".
Please see the following sample:
https://github.com/hagaic/hello-spring-function-azure

See instructions in the README

Note that unit tests pass, but testing manually as follows fails with the above error:
curl http://localhost:7071/api/hello -d "{"name":"Azure"}"

**Comment by chaitanya-mittapalli** [comment]
Any Update on this I am still getting the Same Error as the @hagaic  here.

**Comment by olegz** [comment]
@chaitanya-mittapalli please stop commenting on the closed issue. It is resolved as of March 1, 2019. There is nothing to update.
If you feel there is an issue, please raise a new one with detailed steps on how to reproduce, versions of framework used, stack traces etc.
