### ISSUE TITLE
Extend SpringBootKinesisEventHandler

### ISSUE THREAD

**Issue by dnellutla** [spring-cloud/spring-cloud-function#271]
Error message:  "Hierarchy of the KinesisLambdaFunctionHandler" is inconsistent when class extends SpringBootKinesisEventHandler<KinesisEvent, String>

public class KinesisLambdaFunctionHandler extends SpringBootKinesisEventHandler<String, String> {
}

**Comment by olegz** [comment]
I am not sure what are you trying to say here. Extending `SpringBootKinesisEventHandler` as you did did not result in any errors (compile or otherwise), so please provide additional details and most importantly how to reproduce

**Comment by dnellutla** [comment]
I am working on a Lambda function to listen to Kinesis Events on AWS
Implementing spring-cloud-function as a part of which I wrote a Handler with the below:
public class KinesisLambdaFunctionHandler extends SpringBootKinesisEventHandler<String, String> {
}

and it gives me an error message: "Hierarchy of the KinesisLambdaFunctionHandler" is inconsistent

**Comment by olegz** [comment]
I would suggest checking your classpath for inconsistencies
Based on limited information you have provided I am not able to reproduce the issue after extending  `SpringBootKinesisEventHandler`

**Comment by dnellutla** [comment]
Thank you.
