### ISSUE TITLE
Abstraction function for SpringBootStreamHandler with custom input json

### ISSUE THREAD

**Issue by mengjiann** [spring-cloud/spring-cloud-function#349]
This is based on the question which is asked on [stackoverflow](https://stackoverflow.com/questions/55157644/extending-springbootstreamhandler-for-springcloudfunction?noredirect=1#comment97464000_55157644).

My project has a requirement where the input json object is random. Thus, it is not possible for me to define a Java class, which is mandatory for the SpringBootRequestHandler implementation. 

Currently, my handler class extending SpringBootStreamHandler looks something like below:
```
public class CustomHandler extends SpringBootStreamHandler {

  @Autowired
  private BeanA beanA;

  @Override
  public void handleRequest(InputStream input, OutputStream output, Context context) throws IOException {
    // Call initialize to autowire beanA
    this.initialize(); 
    // Business logic to parse partial of json input into an object.
    ....
  }
}

```

But, is there a way which I can abstract the business logic to another class extending Function<?,?> which is similar to the SpringBootRequestHandler implementation?

```
@Component
public class CustomFunction extend Function<?,?> {
  // Business logic
  ........
}

```

**Comment by olegz** [comment]
Ok, I am not sure I fully understand. The current parsing logic delegates to a private method `Object value = convertStream(input);`, which use `ObjectMapper` to do the conversion. The `ObjectMapper` itself is autowired, so presumable you can provide your own. The _type` to which ObjectMapper will convert to is extracted from the actual function signature.

So for example if you have a function `Function<String, Foo>` then the incoming `InputStream` will be converted to `String` and then your function will be invoked.

Are you saying that you actually want an ability to handle functions where signature is a wild card - `Function<?, ?>`? If so wouldn't that actually mean that you want direct access to `InputStream input, OutputStream output`?

**Comment by mengjiann** [comment]
I'm currently handling the parsing logic in the override method `handleRequest` of SpringBootStreamHandler. Since the input json object to the cloud function cant be serialized into a fixed POJO, is there any better way of handling the object parsing code within the `handleRequest` override method.

Having access to the InputStream might work for my case but the object parsing code might probably be the same within the implemented `apply` function. Any ways to not deal with the deserialization within the method?

**Comment by olegz** [comment]
You are answering my question, so let's try again. 

Parsing and type conversion is handled by the framework already providing the type (the signature) is known. So there is no need for you to do it manually or override anything. And if we are missing _something_ then let's clearly state what that _something_ is, so we can address it.

The only area where i see you may need to do some manual work is when dealing with the signature of a function where types can not be determined (e.g.  `Function<?, ?>`). Is that what we're talking about?

**Comment by mengjiann** [comment]
> You are not answering my question, so let's try again.
> 
> Parsing and type conversion is handled by the framework already providing the type (the signature) is known. So there is no need for you to do it manually or override anything. And if we are missing _something_ then let's clearly state what that _something_ is, so we can address it.

Agree

> 
> The only area where i see you may need to do some manual work is when dealing with the signature of a function where types can not be determined (e.g. `Function<?, ?>`). Is that what we're talking about?

Yes. That is my concern.

**Comment by olegz** [comment]
Ok, so I guess it's more about exposing conversion call where you can pass a type. In other words as you said _"... object parsing code might probably be the same ..."_

**Comment by mengjiann** [comment]
is expose conversion call possible? i think that will be great.

**Comment by olegz** [comment]
Yes, it's possible. Hoping to address it for 2.1 release

**Comment by olegz** [comment]
So basically what I am doing is bypassing the conversion all together for a wild card function (`Function<?,?>`). This means you will get an `InputStream` - raw input. All you need to do is autowire `ObjectMapper` which will be the same `ObjectMapper` instance used by `SpringBootStreamHandler` and call it in your function.
```
@Autowired
private ObjectMapper mapper;

@Bean
public Function<?, ?> function() {
	return value -> {
		try {
			Foo foo = this.mapper.readValue((InputStream)value, Foo.class);
			return new Bar(foo.getValue().toUpperCase());
		}
		catch (Exception e) {
			throw new IllegalStateException("Failed test");
		}
	};
}
```
So the only fix is to avoid conversion which was creating a `Map`. 

But here is the question. . . What is wrong with `Map` and why would you prefer `InputStream` over `Map`? I mean there is one valid reason; If you are not interested in Map and instead only interested in some domain specific type then you would have to convert again somehow using your own mechanism. With the above approach you are saving the double conversion effectively. 
That is good enough reason, but i wanted to ask before I push.

**Comment by mengjiann** [comment]
> But here is the question. . . What is wrong with `Map` and why would you prefer `InputStream` over `Map`? I mean there is one valid reason; If you are not interested in Map and instead only interested in some domain specific type then you would have to convert again somehow using your own mechanism. With the above approach you are saving the double conversion effectively.
> That is good enough reason, but i wanted to ask before I push.

Yea, you have already answered it! Thanks for the prompt update.

**Comment by olegz** [comment]
Ok, so I just pushed a fix with test where we can meet in the middle. Basically we're not comfortable to _assume_ user wants InputStream for typeless functions (e.g., `Function<?,?>`), yet we recognise that some user may want just that. So instead of having a typeless function, make it `Function<InputStream,?>`. This way the default conversion mechanism would work as follows:
- Type is known - convert to POJO
- Type is not known - convert to generic `Map`
- Type is InputStream - pass through the raw `InputStream`
