### ISSUE TITLE
Stop expecting ConfigurationBeanFactoryMetadata to be a bean

### ISSUE THREAD

**Issue by wilkinsona** [spring-cloud/spring-cloud-function#351]
In Spring Boot 2.2, `ConfigurationBeanFactoryMetadata` is [no longer a bean](https://github.com/spring-projects/spring-boot/commit/0872eb0dd92129266c3bf396829c3f91e0ec740c#diff-6f4a21fd21213974be90765e541a69e1). It's also now a stateless adapter on top of some internal improvements in Framework. If SCF is calling `ConfigurationBeanFactoryMetadata` directly, it should stop doing so as we don't really want `ConfigurationBeanFactoryMetadata` to be public API.

**Comment by dsyer** [comment]
SCF doesn't use `ConfigurationBeanFactoryMetadata` directly - just copied some bean definitions from `ConfigurationPropertiesBindingPostProcessorRegistrar` that are used by Spring Boot. We can fix this easily by just using the registrar (on the understanding that it doesn't use the `AnnotationMetadata`).
