### ISSUE TITLE
Expose function through RSocket

### ISSUE THREAD

**Issue by linux-china** [spring-cloud/spring-cloud-function#366]
Now spring-cloud-function use HTTP to expose service, and any plan to use RSocket to expose services too? 
For example with following code:

```
 @Bean
  public Function<String, String> uppercase() {
    return value -> value.toUpperCase();
  }
```
and REST API like following: 
```
curl -H "Content-Type: text/plain" localhost:8080/uppercase -d Hello
```

and with Spring Messaging RSocket, and "uppercase" is the routing key, and we can invoke as following:

```
rsocket-cli --dataFormat "application/text" --request -m "uppercase"  -i "hello" --debug ws://localhost:8088/rsocket
```

**Comment by olegz** [comment]
@linux-china Your timing could not be more perfect. Yes we are working on it and it is high on our priority list. Stayed tuned. . .

**Comment by olegz** [comment]
The initial RSocket support has been added recently - https://github.com/spring-cloud/spring-cloud-function/tree/master/spring-cloud-function-rsocket and the more will be added shortly as well as documentation.
So, please give it a shot and feel free to raise individual issues related to RSocket support
