### ISSUE TITLE
Support  for S3EventHandler 

### ISSUE THREAD

**Issue by daveRanjan** [spring-cloud/spring-cloud-function#370]
As a developer I should be able to create a `RequestHandler` by extending `SpringBootS3EventHandler` similar to `SpringBootKinesisEventHandler` and `SpringBootApiGatewayEventHandler`

**Comment by olegz** [comment]
Actually i don't believe you should extend any handler. Implementing a simple function and annotating it as a bean should be enough and the framework should take care of the rest. I'll be merging something shortly to that extent where and then we can see how S3 fits in here.

**Comment by olegz** [comment]
I believe this is already supported with a single `FunctionInvoker` - https://github.com/spring-cloud/spring-cloud-function/blob/b245812c6bd93507cd7b8912169d46404b0853f3/spring-cloud-function-adapters/spring-cloud-function-adapter-aws/src/main/java/org/springframework/cloud/function/adapter/aws/FunctionInvoker.java#L207

And here is how you use it - https://docs.spring.io/spring-cloud-function/docs/3.0.8.RELEASE/reference/html/aws.html#_getting_started
