### ISSUE TITLE
Support flexible method invokers

### ISSUE THREAD

**Issue by sdeleuze** [spring-cloud/spring-cloud-function#387]
From the beginning, Spring has provided a popular programming model based on flexible method invokers via the `@RequestMapping` programming model in Spring MVC / Spring WebFlux or `@MessageMapping` in Spring messaging with STOMP or now RSocket protocols.

That's maybe a matter of taste, but while I find the `java.util.function.*` beans programming model useful, it sounds like to me more a useful feature (that could be potentially supported at Spring Framework level, issue to be created) rather than the cornerstone and mandatory way Spring Cloud Function should be exposed to developers.

I think supporting flexible method invokers programming model in Spring Cloud Function, in addition to the `java.util.function.*` beans one, would be great since it would provide a consistent programming model across the Spring portfolio and make it possible to define functions in a more concise en readable way, especially  in Java.

For example, it could be possible to define `String foo(String bar, String baz)` as an equivalent of `Function<Tuple<String, String>,String> foo()`. Or `Flux<String> foo(Flux<String> bar, Flux<String> baz)` as an equivalent of `Function<Tuple<Flux<String>,Flux<String>>, Flux<String> foo()`. We could even support Kotlin Coroutines with methods like `suspend foo(String bar, String baz): String` that would translates internally to `Mono` thanks to the use of the `ReactiveAdapterRegistry`.

How these methods are resolved and the potential limitations to avoid issues related to stateful classes needs to be defined.

**Comment by olegz** [comment]
Ironically that is exactly what I am currently working on as part of this issue - https://github.com/spring-cloud/spring-cloud-function/issues/378

**Comment by olegz** [comment]
Just for my own sake wanted to create few tasks and add a bit more context as I see it:

- [ ] - Add initial support for "anything" that looks like function (e.g., POJO function)

For example:
```
public class MyFunction {
    public String uppercase(String v) { return v.toUpperCase();}
}
```
While not the implementation of a Function it is a function  and should/can be treated as such and is consistent with the historical POJO message of Spring. This will allow for flexibility that is best demonstrated with the tests in ongoing work
```
MyFunction f1 = catalog.lookup("myFunction");
assertThat(f1.uppercase("foo")).isEqualTo("FOO");

Function<String, String> f2 = catalog.lookup("myFunction");
assertThat(f2.apply("foo")).isEqualTo("FOO");

Function<Flux<String>, Flux<String>> f3 = catalog.lookup("myFunction");
assertThat(f3.apply(Flux.just("foo")).blockFirst()).isEqualTo("FOO");
```
As you can see `MyFunction` could be accessed _as is_ as well as `Function<String, String>` and `Function<Flux<String>, Flux<String>>` and few other variations.

- [ ] - Add the same support for multi-in/out as described in the original issue

**Comment by linux-china** [comment]
Now I use following code: 

```
@Controller
@Qualifier(NAME)
public class Greeter implements Function<String, Mono<String>> {
    public final static String NAME = "greeter";

    @Override
    @MessageMapping(NAME)
    public Mono<String> apply(String s) {
        return Mono.just("Hello " + s);
    }
}
```
