### ISSUE TITLE
Classloader issue when using Java 11 and autoconfiguring conditional on presence of 'javax.activation.MimeType'

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-function#391]
The classloading changed here https://github.com/spring-cloud/spring-cloud-function/commit/de73c514628bacd9685baf4f141468b091398aaf#diff-c5b8338951ddb63c071c53261b9bcbce

This prevents functions using `JavaMailSender` and `spring-boot-starter-mail` from getting autoconfigured:
```
default/notifier-lvjt7-deployment-578c79d8bd-dhhzx[user-container]:    MailSenderAutoConfiguration:
default/notifier-lvjt7-deployment-578c79d8bd-dhhzx[user-container]:       Did not match:
default/notifier-lvjt7-deployment-578c79d8bd-dhhzx[user-container]:          - @ConditionalOnClass did not find required class 'javax.activation.MimeType' (OnClassCondition)
```

See corresponding riff issue: https://github.com/projectriff/java-function-invoker/issues/132

**Comment by olegz** [comment]
This was resolved with the newly revamped deployer and test has been added that reproduces the issue. See this commit https://github.com/spring-cloud/spring-cloud-function/commit/3bc03a640a9966a56a5edbe4a376a0bdefc5230c
