### ISSUE TITLE
AWS: Initialization outside handleRequest

### ISSUE THREAD

**Issue by akhanal** [spring-cloud/spring-cloud-function#399]
Initialize spring context outside
com.amazonaws.services.lambda.runtime.RequestHandler.handleRequest()

This makes startup time faster as AWS will provide CPU boost for code outside handleRequest() method, that is code in class constructor or static blocks.

**Comment by olegz** [comment]
I am not sure I understand. Is this a request for feature, enhancement? Can you provide some relevant info, details?

**Comment by akhanal** [comment]
Request for enhancement . If we initialize everything outside the handler method , we can take advantage of CPU burst, no billing and  and make cold startup faster.

**Comment by olegz** [comment]
So, i fixed it for new implementation of the request handler called `org.springframework.cloud.function.adapter.aws.FunctionInvoker`

Docs were updated as well, bu here is the snippet. The bottom line you no longer have to provide an empty implementation of AWS request handler

======
One of the goals of Spring Cloud Function framework is to provide necessary infrastructure elements to enable a _simple function application_
to interact in a certain way in a particular environment.
A simple function application (in context or Spring) is an application that contains beans of type Supplier, Function or Consumer.
So, with AWS it means that a simple function bean should somehow be recognised and executed in AWS Lambda environment.

Let’s look at the example:

```
@SpringBootApplication
public class FunctionConfiguration {

	public static void main(String[] args) {
		SpringApplication.run(FunctionConfiguration.class, args);
	}

	@Bean
	public Function<String, String> uppercase() {
		return value -> value.toUpperCase();
	}
}
```

It shows a complete Spring Boot application with a function bean defined in it. What’s interesting is that on the surface this is just
another boot app, but in the context of AWS Adapter it is also a perfectly valid AWS Lambda application. No other code or configuration
is required. All you need to do is package it and deploy it, so let’s look how we can do that.

To make things simpler we’ve provided a sample project ready to be built and deployed and you can access it [here](https://github.com/spring-cloud/spring-cloud-function/tree/master/spring-cloud-function-samples/function-sample-aws).

You simply execute `./mvnw clean package` to generate JAR file. All the necessary maven plugins have already been setup to generate
appropriate AWS deployable JAR file. (You can read more details about JAR layout in <<Notes on JAR Layout>>).

Then you have to upload the JAR file (via AWS dashboard or AWS CLI) to AWS.

When ask about _handler_ you specify `org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest` which is a generic request handler.

=====

**Comment by olegz** [comment]
The good part about new handler is that it can be used in place of 4 handlers  (API Gateway, Kinesis, streaming etc) we currently provide which I hope to deprecate soon, hence my reluctance to fix them
