### ISSUE TITLE
Process JSON array for POST in the function once

### ISSUE THREAD

**Issue by steven-chou** [spring-cloud/spring-cloud-function#402]
Hi, 
I tried to implement a simple POST function in AWS Lambda with Spring Cloud Function. The POST body will be JSON array, e.g. user object
`[
	{
		"userName": "foo",
                 ...
	}, 
	{
		"userName": "bar",
               ...
	}
]`

After some experiment, I realized I just need to define a function bean that has the POJO representing this JSON as input and Spring Cloud Function will recognize this is an array of the specified object and apply the function on each one of them.

However, because the logic we want to perform on the POST is the user insertion to the DB, and we want to do one batch insertion for all the submitted users. Applying function to every item one by one is very inefficient, so I'm wondering if there is any alternative way to handle this use case or it is the limitation of the current programming model in the Spring Cloud Function.

Thanks.

**Comment by olegz** [comment]
This is an interesting request and ironically we just debated something similar on the Supplier case. Basically you want the following:

```
public Function<List<I>, O> func() {..}

public Function<Flux<I>, O> funcFlux() {..}
```
. . . correct?
In other words if we see that the actual input is a collection(iterable) and the input type of the function is iterable as well we should not be clever and give you the iterable (perhaps with converted into individual POJOs.

**Comment by steven-chou** [comment]
@olegz Yes, this is what I'm asking for. The Spring web MVC has supported the collection/iterable as  argument type in the controller method, so I think this should be also supported by the Spring Cloud Function here.

**Comment by olegz** [comment]
@steven-chou understood. We'll take care of it for M3

**Comment by olegz** [comment]
Actually it s now supported  and was fixed as part of several other issues primarily originated in spring-cloud-stream.
Please give it a shot with 3.0.8 and above and feel free to reopen it if you still see the issue.
