### ISSUE TITLE
Trigger and Deployment Enhancement

### ISSUE THREAD

**Issue by a3nz3g** [spring-cloud/spring-cloud-function#407]
Seems currently the spring cloud function framework does not cover the 2 issues. 1. Trigger binding for public cloud. 2. fine-grained deployment control, aggregate multiple functions as one function on the public cloud.

I wrote a demo. @CloudFunction marks a class as an aggregate for a group of functions. Subclass of @Trigger marks trigger binding for public cloud trigger.

https://github.com/a3nz3g/function-sample-scf/blob/master/src/main/java/com/a3nz3g/example/function/BarFunction.java

Does the Spring Cloud Function has a plan to cover function deployment orchestration?

**Comment by olegz** [comment]
I am not sure I follow. . .
1. Triggering binding for public cloud. Have you looked at spring-cloud-function-web module as well as spring-cloud-function-adapters that currently cover AWS, Azure etc. Are you asking something different? Also with regard to triggering we have other frameworks such as spring-cloud-stream which uses spring-cloud-function programming model while providing bindings to Kafka, Rabbit and more.
2. With regard to aggregate/orchestration we currently provide function composition. . . sort of `func1.andThen(func2)`. Are you asking/proposing for something different?

**Comment by olegz** [comment]
Closing it as the issue went stale. Please feel free to reopen it if you can share more details
