### ISSUE TITLE
FunctionChannelBindingInitializer desires an "output" bean defined in the Spring Context.

### ISSUE THREAD

**Issue by Macrame** [spring-cloud/spring-cloud-function#430]
**Describe the bug**
Fail to start the spring cloud config-server after upgrading to spring-cloud Hoxton.RELEASE.

**Sample**

I have an application using Spring Cloud Config with the following dependencies.

Spring Boot 2.2.2.RELEASE
Spring Cloud Dependencies Hoxton.RELEASE
dependencies {
    compile("org.springframework.boot:spring-boot-starter-actuator")
    compile("org.springframework.cloud:spring-cloud-config-server")
    compile("org.springframework.cloud:spring-cloud-config-monitor")
    compile("org.springframework.cloud:spring-cloud-starter-bus-amqp")
    compile("org.springframework.cloud:spring-cloud-bus")
    compile("org.springframework.cloud:spring-cloud-starter-netflix-eureka-client")
    compile('org.springframework.cloud:spring-cloud-starter-kubernetes')
    compile("org.springframework.boot:spring-boot-starter-actuator")
    testCompile("org.springframework.boot:spring-boot-starter-test")
}

Now I receive the following error:
Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'functionInitializer' defined in class path resource [org/springframework/cloud/stream/function/FunctionConfiguration.class]: Invocation of init method failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'output' available
2019-12-10 11:07:35.794  INFO 69908 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2019-12-10 11:07:35.796  INFO 69908 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
2019-12-10 11:07:35.800  INFO 69908 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2019-12-10 11:07:35.823  INFO 69908 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-12-10 11:07:35.918 ERROR 69908 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

A component required a bean named 'output' that could not be found.

Action:

Consider defining a bean named 'output' in your configuration.

> Task :peony-config-server:bootRun FAILED

---------------------------------------------------------------------------------------------
I tried to debug to address this issue and found that KubernetesDiscoveryClientAutoConfiguration defineds a bean named KubernetesClientServicesFunction, which extends Function. BeanFactoryAwareFunctionRegistry discovers this functional Bean but FunctionConfiguration initializes it and tries to bind with stream chanel.  FunctionChannelBindingInitializer determines the subscribable channel who desires an "output" bean defined in the Spring Context.

I don't known who to define this "output" bean. Please help me.
Thanks a lot to your team!

**Comment by olegz** [comment]
This is the wrong repository for this issue, since `FunctionChannelBindingInitializer` is part of [spring-cloud-stream](https://github.com/spring-cloud/spring-cloud-stream).

Also, this has already been addressed - https://github.com/spring-cloud/spring-cloud-stream/issues/1852

**Comment by Macrame** [comment]
Thank you very much.
