### ISSUE TITLE
Ignored SQSEvent when testing locally but not when deploying and testing in AWS

### ISSUE THREAD

**Issue by DVader666** [spring-cloud/spring-cloud-function#435]
When sending JSON for an AWS SQS event to a function running locally (via spring-cloud-starter-function-web dependency), the received SQSEvent is always empty (not null).

When the same function is deployed and tested in AWS, the same received SQS event contains the expected data.

Versions used:
- Spring Boot 2.2.2.RELEASE
- Spring Cloud Function 3.0.0.RELEASE (also tried 3.0.1.BUILD-SNAPSHOT)
- AWS Java SDK 1.11.689
- AWS Lambda Java Events 2.2.7
- AWS lambda Java Core 1.2.0

The attached demo app illustrates the issue.

[demo.zip](https://github.com/spring-cloud/spring-cloud-function/files/3963088/demo.zip)

Once the Spring Boot app is running (locally), I test it like:

    curl -v -H "Content-Type: application/json" localhost:8080/sqsEvent -d @src/main/resources/sqs-event.json

... but the the logged SQSEvent is empty. Its records list is null.

Notice that the same *does not happen* when trying an S3 event instead:

    curl -v -H "Content-Type: application/json" localhost:8080/s3Event -d @src/main/resources/s3-event-put.json

... data for the received S3Event is logged to stdout.

Having a simple POJO input also works:

    curl -v -H "Content-Type: application/json" localhost:8080/customEvent -d '{"id": 123456789, "name": "some dude"}'

So, is this a bug or am I doing something wrong?

Here are the defined functions in `DemoApplication` (inside the attached ZIP file) for quick reference:

    @Bean
    public Consumer<SomeEvent> customEvent() {
        return someEvent -> System.out.println(someEvent.toString());
    }

    @Bean
    public Consumer<S3Event> s3Event() {
        return s3Event -> System.out.println(s3Event.toJson());
    }

    @Bean
    public Consumer<SQSEvent> sqsEvent() {
        return sqsEvent -> System.out.println(sqsEvent.getRecords());
    }

**Comment by DVader666** [comment]
If this is a "false positive", someone please let me know and, if possible, why.

**Comment by DVader666** [comment]
Did I create this issue with the "wrong format" or said anything wrong? It's over a month now and not a single response.

**Comment by olegz** [comment]
No, just didn't get a chance to look into it yet, but PRs are always welcome!

**Comment by olegz** [comment]
My initial suspicion is that we don't do anything specific to SQS in spring-cloud-function. in other words here is no code that would create/convert some incoming request to `SQSEvent`.
It's AWS that produces it, hence it works when running in AWS. 

That said, we probably need to throw some type of conversion exception. In any event, i'll take a look when I get a min.

**Comment by DVader666** [comment]
Really appreciated. Glad to be of help in any way if this report results in eliminating a bug.

**Comment by olegz** [comment]
@DVader666 there was some major work in FunctionInvoker and aside from additional events individual tests were added for each event including SQS, so we are going to be releasing 3.0.9 tomorrow, so feel free to try and let us know.
I'll close it for now, but feel free to reopen or raise a new one if you feel you still have issues,
