### ISSUE TITLE
reactor.core.publisher.FluxJust cannot be cast to com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent

### ISSUE THREAD

**Issue by gbhosal** [spring-cloud/spring-cloud-function#436]
I must confess that I am new to Spring Cloud Function. I am unable to figure out why my test program is running into "reactor.core.publisher.FluxJust cannot be cast to com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent" problem.  

This handler configured for this AWS lambda is "org.springframework.cloud.function.adapter.aws.SpringBootApiGatewayRequestHandler". I even tried with one of my own Custom Handler but still it runs into the error.

You can take a look at my test application here -
https://github.com/gbhosal/my-user-backend.git

**Comment by olegz** [comment]
@gbhosal there were some recent enhancements done to adapters including AWS. We've also updated the user guide. All of it will be released as 3.0.1.RELEASE in the next few days, but here is the link to the updated documentation - https://cloud.spring.io/spring-cloud-function/reference/html/aws.html which contains _Getting Started_ and pointer to the working example. After you go through this let us know if you still have any issues as a separate issue.
