### ISSUE TITLE
Support Application Load Balancer Request Event 

### ISSUE THREAD

**Issue by dotekien** [spring-cloud/spring-cloud-function#438]
**Is your feature request related to a problem? Please describe.**
ALB request event differs from APIGateway payload. Should we have different handler to handle ALB event?
https://aws.amazon.com/blogs/networking-and-content-delivery/lambda-functions-as-targets-for-application-load-balancers/

**Describe the solution you'd like**
public class SpringBootALBRequestHandler extends
		SpringBootRequestHandler<ALBRequestEvent, ALBResponseEvent> {
}

**Comment by olegz** [comment]
As of 3.0.1 you don't need to implement any handlers at all. We can handle pretty much all events with a single handler - https://cloud.spring.io/spring-cloud-static/spring-cloud-function/3.0.1.RELEASE/reference/html/aws.html. Give it a shot and let us know.

**Comment by dotekien** [comment]
https://github.com/spring-cloud/spring-cloud-function/blob/b8c356525182416a1cd94ede5268d8fe41787a0e/spring-cloud-function-adapters/spring-cloud-function-adapter-aws/src/main/java/org/springframework/cloud/function/adapter/aws/FunctionInvoker.java#L83
From line 83, the response will set values for isBase64Encoded, statusCode, body and headers. 
I have a few questions here:
1) the respose to ALB must have "statusDescription" from this document https://docs.aws.amazon.com/elasticloadbalancing/latest/application/lambda-functions.html#respond-to-load-balancer. Where are sprint-cloud-function setting that field?
2) There is no way to set the headers value. Am I right?
3) There is no way to set my own status code?

I also have another question for FunctionInvoker during converting current RestController requests/responses to lambda requests/responses. How to capture the lambda requests/responses and forward them to DispatcherServlet with HttpRequest/HttpResponse?

Thanks!

**Comment by olegz** [comment]
So I am addressing 1, 2 and 3 (the 2 with `foo/bar` was an accident). As for 4, i'd suggest opening up a separate issue as it needs a bit more investigation.
