### ISSUE TITLE
spring.cloud.function.definition function composition not working with function-web

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-function#444]
For Hoxton.SR1, according to the documentation (https://cloud.spring.io/spring-cloud-function/reference/html/spring-cloud-function.html#_standalone_web_applications) 

> For cases where there is more then a single function in catalog and you want to map a specific function to the root path (e.g., "/"), or you want to compose several functions and then map to the root path you can do so by providing spring.cloud.function.definition property which essentially used by spring-cloud-function-web module to provide default mapping for cases where there is some type of a conflict (e.g., more then one function available etc).
>
> For example,
>
> ```
--spring.cloud.function.definition=foo|bar
```
> The above property will compose 'foo' and 'bar' function and map the composed function to the "/" path.

If I create the following beans

```java
@Bean
	Function<String, String> lowercase() {
		return s -> {
			String response = s.toLowerCase();
			System.out.println("Sending a response [" + response + "]");
			return response;
		};
	}

	@Bean
	Function<String, String> replace() {
		return s -> s.replace("a", "4");
	}

	@Bean
	Function<String, String> reverse() {
		return s -> new StringBuilder(s).reverse().toString();
	}
```

and then set the property 

```
spring.cloud.function.definition: lowercase|replace|reverse
```

and curl the `/` 

```
$ curl -H "Content-Type: text/plain" localhost:9081/ -d HELLO
```

I get 

```
{"timestamp":"2020-01-13T15:26:45.994+0000","status":404,"error":"Not Found","message":"No message available","path":"/"}%                                                                 
```

and the logs contain

```
2020-01-13 16:42:17.775  INFO 10599 --- [nio-9081-exec-1] c.f.c.c.BeanFactoryAwareFunctionRegistry : Found more then one function beans in BeanFactory: [lowercase, replace, reverse, consumer, supplier]. If you did not intend to use functions, ignore this message. However, if you did intend to use functions in the context of spring-cloud-function, consider providing 'spring.cloud.function.definition' property pointing to a function bean(s) you intend to use. For example, 'spring.cloud.function.definition=myFunction'
```

**Comment by nguyenminhtuanfit** [comment]
@olegz if i have 
definition: lowercase|replace|reverse;lowercase
do we support any rest endpoint mapping to /lowercasereplacereverse?  how can i call via rest to this pipe: lowercase|replace|reverse

i am not seeing any rest endpoint expose under   GET: .../actuator/functions

**Comment by nguyenminhtuanfit** [comment]
https://cloud.spring.io/spring-cloud-function/reference/html/spring-cloud-function.html#_function_mapping_rules
i found it: just calling lowercase**,**replace**,**reverse
