### ISSUE TITLE
Single consumer name will not be correctly resolved from catalog

### ISSUE THREAD

**Issue by aropop** [spring-cloud/spring-cloud-function#454]
**Describe the bug**
Application with a single consumer will not resolve the name of the function correctly due to missing consumer branch in AbstractSpringFunctionAdapterInitializer.initFunctionConsumerOrSupplierFromContext.

The part of the code will try to retrieve the name of the function, if only 1 function is present in a function catalog. However it only checks for suppliers and functions, not for consumers. Therefor consumers will not be correctly called.

**Sample**
```
    @Bean(name = "some-consumer")
    public Consumer<String> someConsumer() {
        return (input) -> {
            doStuff(input);
        };
    }
```

**Comment by olegz** [comment]
Resolved with 013e714
