### ISSUE TITLE
Ability to register more than one functional class when using the deployer to load a non spring-boot archive

### ISSUE THREAD

**Issue by jamesmmchugh** [spring-cloud/spring-cloud-function#461]
**Is your feature request related to a problem? Please describe.**
It's great that spring-cloud-function's deployer allows you to write very small and compact jars containing pure buisness logic, with no dependencies including spring/boot itself, which can be deployed in a separate runtime. 

It's concievable in some cases that you might want to package multiple functions together if there is some degree of unavoidable coupling required, and this is supported by the deployer for spring-boot archives.  However with non spring-boot archives you can only specify a single functional class (either as a property or in the jar's manifest) to be registered.

It looks like the `FunctionArchiveDeployer` class could be extended relatively easily to handle registering multiple functions from a non spring-boot archive.

**Describe the solution you'd like**
Allow a comma separated list of class names to be defined (either as property, or manifest entry) that is used to register multiple functions from a single non spring-boot jar.

**Describe alternatives you've considered**
Packaging the functions within one non spring-boot jar and loading the jar, using the deployer, multiple times. Obivously this works, but it is inefficient in terms of both loading times and memory usage due to the same classes being loaded multiple times by each function's isolated class loader.

**Additional context**
N/A

**Comment by olegz** [comment]
Was thinking about it the other day actually. Definitely something that we should support since for standard cases we do support multiple functions so we should do the same for 'class'

**Comment by olegz** [comment]
So, now you can specify multiple classes delimiting them by `;`
Here is modified test case
```
@Test
public void testWithMainAndStartClassNoSpringConfiguration() throws Exception {
	String[] args = new String[] {
				"--spring.cloud.function.location=target/it/bootjar/target/bootjar-1.0.0.RELEASE-exec.jar",
				"--spring.cloud.function.function-class=function.example.UpperCaseFunction;function.example.ReverseFunction" };

	ApplicationContext context = SpringApplication.run(DeployerApplication.class, args);
	FunctionCatalog catalog = context.getBean(FunctionCatalog.class);
	Function<String, String> function = catalog.lookup("upperCaseFunction");

	assertThat(function.apply("bob")).isEqualTo("BOB");
	assertThat(function.apply("stacy")).isEqualTo("STACY");

	function = catalog.lookup("reverseFunction");

	assertThat(function.apply("bob")).isEqualTo("bob");
	assertThat(function.apply("stacy")).isEqualTo("ycats");

	Function<Flux<String>, Flux<String>> functionAsFlux = catalog.lookup("upperCaseFunction");

	List<String> results = functionAsFlux.apply(Flux.just("bob", "stacy")).collectList().block();
	assertThat(results.get(0)).isEqualTo("BOB");
	assertThat(results.get(1)).isEqualTo("STACY");

	functionAsFlux = catalog.lookup("reverseFunction");

	results = functionAsFlux.apply(Flux.just("bob", "stacy")).collectList().block();

	assertThat(results.get(0)).isEqualTo("bob");
	assertThat(results.get(1)).isEqualTo("ycats");
}
```
