### ISSUE TITLE
Add support for GET method to FunctionEndpointInitializer.

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-function#467]
If you define a `@Bean` of type `Supplier<String>` in a regular `@SpringBootApplication` it shows up on the home page of the app when you run it (i.e. GET /). If you use `FunctionalSpringApplication` and  a `ApplicationContextInitializer` you get a 404 NOT FOUND.

Example:

```java
@SpringBootApplication(proxyBeanMethods = false)
public class FunctionApplication implements 
  ApplicationContextInitializer<GenericApplicationContext> {

	public static void main(String[] args) {
		FunctionalSpringApplication.run(FunctionApplication.class, args);
	}

	@Override
	public void initialize(GenericApplicationContext app) {
		app.registerBean("home", FunctionRegistration.class,
		() -> new FunctionRegistration<>(new Home()).type(FunctionType.supplier(String.class)));
	}
}

class Home implements Supplier<String> {

	@Override
	public String get() {
		return "Fred";
	}

}
```

BTW it works for a `Function<String,String>` (i.e. you can POST to / with functional bean registrations).

**Comment by olegz** [comment]
We should probably revisit the whole FunctionalSpringApplication approach in function-web since as discussed [here](https://github.com/spring-cloud/spring-cloud-function/issues/459) it's pretty tightly coupled with webflux.

**Comment by dsyer** [comment]
`FunctionalSpringApplication` isn't supposed to be tied to webflux (it wasn't to start with anyway). It's in the spring-cloud-function-context jar right? The approach might need some revisiting, but I think we should continue to support it (i.e. fix it).

**Comment by olegz** [comment]
Well, it is tied to webflux via `FunctionExporterAutoConfiguration` not 's-c-f-context` - see https://github.com/spring-cloud/spring-cloud-function/issues/459.

I'll see what I can do to address the immediate issue for 3.0.4, but I suspect a more intrusive surgery would be required for a propper fix

**Comment by olegz** [comment]
The culprit is this:
FunctionExporterInitializer has this code:
```
context.registerBean(FunctionExporterAutoConfiguration.class,
				() -> new FunctionExporterAutoConfiguration(context.getBean(ExporterProperties.class)));
```
while `FunctionExporterAutoConfiguration` is declared with @ConditionalOnClass(WebClient.class) which no longer has any effect.
```
@Configuration(proxyBeanMethods = false)
@ConditionalOnClass(WebClient.class)
@Conditional(SourceActiveCondition.class)
@EnableConfigurationProperties(ExporterProperties.class)
public class FunctionExporterAutoConfiguration {
```
So, that's webflux dependency whieh is effectively a #459 issue. 

Still need to look at Supplier export.

**Comment by dsyer** [comment]
Maybe we need to encode those `@Conditionals` into the initializer? It's just a test for a class on the classpath. Not sure what you mean by "intrusive".

**Comment by olegz** [comment]
`. . .what you mean by "intrusive". . .` - me neither, just not sure at the moment how much work is involved and if it may break anything

**Comment by dsyer** [comment]
Also `WebClient` isn't webflux. Just saying.

**Comment by olegz** [comment]
Changing the description and label to `enhancement`, since it is not a bug as it really never worked. We never had support for anything other than POST in `FunctionEndpointInitializer`.
