### ISSUE TITLE
type discovery for generic parameters not fixed yet

### ISSUE THREAD

**Issue by xiazuojie** [spring-cloud/spring-cloud-function#474]
**Describe the bug**
https://github.com/spring-cloud/spring-cloud-function/commit/86d12f3a84f92eb7515af4e30d8c159e77ed0d8c only partially fixes the https://github.com/spring-cloud/spring-cloud-function/issues/473. 
It works when function bean implements `Function<S, T>`, but not when it implements `Function<Flux<S>, Flux<T>>`. 

The issue is related to org.springframework.cloud.function.context.catalog.FunctionTypeUtils#discoverFunctionTypeFromClass not resolving all type variables and wildcard types with concrete types with inheritance.

It works after borrowing code from https://github.com/jhalterman/typetools
```java
	public static Type discoverFunctionTypeFromClass(Class<?> functionalClass) {
		Assert.isTrue(isFunctional(functionalClass), "Type must be one of Supplier, Function or Consumer");
		
		if (Function.class.isAssignableFrom(functionalClass)) {
			return TypeResolver.reify(Function.class, (Class<Function>)functionalClass);
		} else if (Consumer.class.isAssignableFrom(functionalClass)) {
			return TypeResolver.reify(Consumer.class, (Class<Consumer>)functionalClass);
		} else if (Supplier.class.isAssignableFrom(functionalClass)) {
			return TypeResolver.reify(Supplier.class, (Class<Supplier>)functionalClass);
		}
		return null;
	}
```

**Sample**
The following example results in error "java.lang.ClassCastException: HttpRequest cannot be cast to reactor.core.publisher.Flux" after commit https://github.com/spring-cloud/spring-cloud-function/commit/86d12f3a84f92eb7515af4e30d8c159e77ed0d8c.
```java
public interface ScfRxFn<S, T> extends Function<Flux<S>, Flux<T>> {

    default Flux<T> apply(Flux<S> requests) {
        return requests.next().flatMap(this::handle).flux();
    }

    Mono<T> handle(S request);
}

@Component
public class HttpHelloWorld implements ScfRxFn<HttpRequest, HttpResponse> {

    @Override
    public Mono<HttpResponse> handle(HttpRequest request) {
        ...
    }
}
```

**Comment by olegz** [comment]
Not sure I follow, the new test tests exactly what you are asking
```
public interface ReactiveFunction<S, T> extends Function<Flux<S>, Flux<T>> {

}

public static class ReactiveFunctionImpl implements ReactiveFunction<String, Integer> {

	@Override
	public Flux<Integer> apply(Flux<String> inFlux) {
		return inFlux.map(v -> Integer.parseInt(v));
	}
}
```

Am I missing something?

**Comment by olegz** [comment]
Actually i see it now

**Comment by xiazuojie** [comment]
Use pojo as input type, not built-in types such as String, Integer, Map
