### ISSUE TITLE
spring-cloud-function-web unable to resolve List<?> input type

### ISSUE THREAD

**Issue by xiazuojie** [spring-cloud/spring-cloud-function#475]
**Describe the bug**
After https://github.com/spring-cloud/spring-cloud-function/commit/1ec107abbd1c067d70f6846472e7a764d5ce48f7, itemType [here](https://github.com/spring-cloud/spring-cloud-function/blob/1ec107abbd1c067d70f6846472e7a764d5ce48f7/spring-cloud-function-web/src/main/java/org/springframework/cloud/function/web/RequestProcessor.java#L146) has  all  info required to deserialize generic input type. The following ~~"pretty ugly"~~ code does not work for `List<?>` input type as it force cast itemType, which can be `ParameterizedType`, to `Class<?>`, which throws `java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to java.lang.Class`. It should be replaced.
```java
			if (this.shouldUseJsonConversion((String) input, wrapper.headers.getContentType())) {
				Type jsonType = body.startsWith("[")
						&& Collection.class.isAssignableFrom(inputType)
						|| body.startsWith("{") ? inputType : Collection.class;
				if (body.startsWith("[")) {
					jsonType = ResolvableType.forClassWithGenerics((Class<?>) jsonType,
							(Class<?>) itemType).getType();
				}
				input = this.mapper.toObject((String) input, jsonType);
			}
```
Should be replaced with
```java
			if (this.shouldUseJsonConversion((String) input, wrapper.headers.getContentType())) {
				input = this.mapper.toObject((String) input, itemType);
			}
```

**Sample**
```java
public class ListStringInputFunction implements Function<Flux<List<String>>, Flux<String>> {
      public Flux<String> apply(Flux<List<String>> requests) {
      ...
      }
}
```

**Comment by olegz** [comment]
Pleas refrain from comments such as "pretty ugly` especially without knowing all the reasons why things may be the way they are. 
If you have something to contribute, feel free to do so, PRs are always welcome, otherwise state the issue on its technical merits and let someone handle it.

**Comment by xiazuojie** [comment]
> Pleas refrain from comments such as "pretty ugly` especially without knowing all the reasons why things may be the way they are.
> If you have something to contribute, feel free to do so, PRs are always welcome, otherwise state the issue on its technical merits and let someone handle it.

I was quoting from the comment in the existing [source code](https://github.com/spring-cloud/spring-cloud-function/blob/1ec107abbd1c067d70f6846472e7a764d5ce48f7/spring-cloud-function-web/src/main/java/org/springframework/cloud/function/web/RequestProcessor.java#L143). That's why I used double quote.

**Comment by olegz** [comment]
Fair enough, but still, including the code snippet is enough

**Comment by xiazuojie** [comment]
Mean no disrespect. It's a simple misunderstanding.

**Comment by olegz** [comment]
Unfortunately the above suggestion breaks many tests, will look for better solution
