### ISSUE TITLE
 webflux POST FLUX as flux not as object

### ISSUE THREAD

**Issue by jianran** [spring-cloud/spring-cloud-function#485]
post flux as object:

client.post().uri("/lowercase").accept(MediaType.TEXT_EVENT_STREAM).body(Flux.just("FOO", "BAR"), String.class)
			.exchange().expectBodyList(String.class).isEqualTo(Lists.newArrayList("foobar"));

but I expect the function know post is flux, and the result should be "foo" and "bar", post flux as flux:
client.post().uri("/lowercase").accept(MediaType.TEXT_EVENT_STREAM).body(Flux.just("FOO", "BAR"), String.class)
				.exchange().expectBodyList(String.class).isEqualTo(Lists.newArrayList("foo", "bar"));

**Comment by olegz** [comment]
I don't even understand what you are trying to say, so I am closing it. 
In the future if you want to raise the issue please follow [one of the provided guidelines](https://github.com/spring-cloud/spring-cloud-function/issues/new/choose)
