### ISSUE TITLE
AWS custom runtime doesn't work with POJO

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-function#496]
The sample we have works, but if you try to use a POJO type instead of `Function<String,String>` it fails silently. If you turn up the logging you can see it doing the GET to fetch data, but it never does the POST to send back the result. My guess is it never even converts the input string and calls the function. The thing that is broken is probably the `HttpSupplier` or `SupplierExporter` (not AWS per se).

**Comment by dsyer** [comment]
I tried using a POJO in the `FunctionAutoConfigurationIntegrationTests` and that worked OK. But `FunctionalExporterTests` did not. So it's something in the functional form that is broken.

**Comment by dsyer** [comment]
I think the difference might be that the `ContextFunctionCatalogInitializer` creates a `FunctionCatalog` that is simply an `InMemoryFunctionCatalog` whereas the `ContextFunctionCatalogAutoConfiguration` creates a `BeanFactoryAwareFunctionRegistry`.

**Comment by olegz** [comment]
I meant to jump in earlier. . . You are correct, that is the difference. We basically need to align InMemoryFunctionCatalog with BeanFactoryAwareFunctionRegistry. This shouldn't be difficult, basically remove the `BeanFactoryAware` part

**Comment by dsyer** [comment]
This is now fixed on master. Oleg said he'd backport to 3.0.5 as well.
