### ISSUE TITLE
SupplierExporter doesn't have a way to control the output content-type

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-function#498]
`SupplierExporter` does a great job of accepting text/plain from the initial GET, but then if it converts it to a POJO for the `Function` invocation, it forgets the output type might not be `application/json`. A sensible default would be the same as the input type. It would also be nice to have an configuration override.

I believe projectriff already had this issue and solved it, so the code is there in Spring Cloud Function, just not yet being put to use in `SupplierExporter`.

**Comment by olegz** [comment]
You can now control it with `spring.cloud.function.web.export.sink.contentType=text/plain`

**Comment by olegz** [comment]
Resolved with 7bd84c79a26c9ea13e98ad1fd26d56565192b4f6
