### ISSUE TITLE
Clarify the AWS RequestHandlers in the documentation

### ISSUE THREAD

**Issue by rieckpil** [spring-cloud/spring-cloud-function#524]
**Describe the bug**
I'm using Spring Cloud Function 3.0.6.RELEASE and am referring to the [documentation](https://cloud.spring.io/spring-cloud-static/spring-cloud-function/3.0.6.RELEASE/reference/html/aws.html#_aws_request_handlers) about the AWS Request Handlers. For both the `FunctionInvoke` and the `SpringBootRequestStreamHandler` it states that both are *the most generic* ones:

> The most generic is ...

In the same section, there is also a hint about the environment variable of `FUNCTION_NAME` to specify the function name if you have multiple beans of type `Function`. While trying to develop a Lambda function with Spring Cloud Function AWS I realized that this environment variable is not working with the `FunctionInvoke` (here only `SPRING_CLOUD_FUNCTION_DEFINITION` works) handler but only with `SpringBootRequestStreamHandler`.

Is my assumption correct and can I file a PR to maybe clarify this section for other (new) developers?

**Comment by olegz** [comment]
I see your point

**Comment by rieckpil** [comment]
thanks for the fast fix 👍
