### ISSUE TITLE
spring-cloud-function-adapter-gcp (latest currently release available version 3.0.7.RELEASE) is incompatible with spring-boot-starter-parent

### ISSUE THREAD

**Issue by AndrewPonyk** [spring-cloud/spring-cloud-function#533]
spring-cloud-function-adapter-gcp (latest currently release available version 3.0.7.RELEASE) is incompatible with spring-boot-starter-parent (neither 2.0.3.RELEASE, 2.0.2.RELEASE, 2.0.0.RELEASE)

Project from samples folder (function-sample-gcp-http) - can be run locally or in GCP only if adapter version is <version>3.1.0-SNAPSHOT</version>

Changing version to LAST RELEASE version (3.0.7.RELEASE) causes ERROR (see attached file).
Running is performed by maven command mvn function:run

Rules inside our company does not allow to use Spring Maven Repositories, we can use only PROXY to Public Maven Repo, so this issue is blocker for us

[gcp-cloud-adapter-stacktrace.txt](https://github.com/spring-cloud/spring-cloud-function/files/4740138/gcp-cloud-adapter-stacktrace.txt)

[pom.xml.txt](https://github.com/spring-cloud/spring-cloud-function/files/4740159/pom.xml.txt)

**Comment by dzou** [comment]
Thanks for reporting, I'll try to contribute a fix for this.

**Comment by dzou** [comment]
Hey @AndrewPonyk - I just sent out a fix for this in #534 

To move forward I would suggest trying to do your development off the 3.1.0-SNAPSHOT version and then when the fix is officially released you can switch back.

**Comment by AndrewPonyk** [comment]
Thank you, @dzou . 
Very promptly.

**Comment by olegz** [comment]
Resolved with #534
