### ISSUE TITLE
Bug in conditional configuration for Gson

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-function#537]
The `GsonMapper` is only installed if `Gson.class` is available _and_ `spring.http.converters.preferred-json-mapper=gson`. So even if `Gson` is the only possibility the user still has to provide the flag, which seems dumb.

**Comment by olegz** [comment]
I agree, and it also looks like we really don't need `spring.http.converters.preferred-json-mapper=gson`. Right?
Also, i don't think it's a bug, rather enhancement

**Comment by dsyer** [comment]
You would need the flag to disambiguate if `Gson` and `ObjectMapper` were both on the classpath.
