### ISSUE TITLE
GCP Adapter - ability to set a response code

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-function#540]
**Describe the bug**
User needs a way to return a specific response code from the function, e.g., 404 not found, or 400 bad request.

If this can already be done, need to document.

**Comment by olegz** [comment]
I just left [this comment](https://github.com/spring-cloud/spring-cloud-function/issues/539#issuecomment-642950054) which i believe is related to this issue

**Comment by saturnism** [comment]
I feel this one is trickier than #539.. #539 is simply the contract w/ our functions (which are all http-based, and success/failures of the function is communicated via response code). 

For this one, it's because user was asking for a way to do this, because the underlying functions framework's HttpFunction handler does allow user to set status code. (it exposes the entire http request/response)

**Comment by saturnism** [comment]
From the user, it looks like that status code and headers can be set and propagated back to http, from the AWS adapter, by using the `Message` headers, along the lines of:

```
header.put("statusCode", ...);
header.put("X-Custom-Header", "...");
```

**Comment by dzou** [comment]
Yeah we can do [something similar to what AWS does](https://github.com/spring-cloud/spring-cloud-function/blob/master/spring-cloud-function-adapters/spring-cloud-function-adapter-aws/src/main/java/org/springframework/cloud/function/adapter/aws/FunctionInvoker.java#L91), with the user specifying the status code through a custom header i.e.:

```
MessageHeaders headers = responseMessage.getHeaders();
int statusCode = headers.containsKey("statusCode")
		? (int) headers.get("statusCode") : 200;
httpResponse.setStatus(statusCode);
```

**Comment by saturnism** [comment]
can the custom headers be propagated too?

i.e., in the vanilla function frameworks, user can write the header back in response.

**Comment by AndrewPonyk** [comment]
@dzou Yep, would be fantastic to have control which response code to use.

And BTW, maybe you know when 3.1.0 Release would be available approximately ?

**Comment by dzou** [comment]
Sure, we can add this shortly.

Unfortunately I do not know when the 3.1.0 release will occur - maybe @olegz knows?

**Comment by olegz** [comment]
@meltsufin @saturnism @dzou 
Hi guys! There are quite a few GCP issues out there. Are there any plans to do follow up on them?

Cheers
Oleg

**Comment by meltsufin** [comment]
Hey @olegz!
Thanks for the heads up! Yes, we'll take a look soon.

**Comment by elefeint** [comment]
This issue is a valid feature request.

@ddixit14 -- please look into implementing the GCF/SCF adapter setting a response code based on a message header returned from the user function.
