### ISSUE TITLE
GCP Adapter - Is it possible to avoid manual adding MANIFEST.MF?

### ISSUE THREAD

**Issue by dzou** [spring-cloud/spring-cloud-function#541]
One of the requirements to using the GCP adapter is to manually specify the main class in a `manifest.mf` file. Is this still necessary after the addition of the `GcfJarLauncher` which writes the format of the JAR?

**Comment by manishbansal8843** [comment]
I am not an expert, but `GcfJarLauncher` is merely initializing `FunctionInvoker` class and delegating all the GCP function calls to `FunctionInvoker`. Now, to initialize `FunctionInvoker`, It is required to know the main class of your spring boot application. Therefore inside constructor call of the `AbstractSpringFunctionAdapterInitializer` class which is parent of `FunctionInvoker`, it determines the main class by calling `FunctionClassUtils.getStartClass()`.  There, we actually try to find out the main class to bootstrap the application. There are several ways to specify the main class. one of them is `manifest.mf` as you specified. Others are like mentioning system property. 

So to answer your question, it is optional. you can use other methods as well. Look at [this ](https://github.com/spring-cloud/spring-cloud-function/blob/c4dfffe0bac5b0d6924d0a868d5757c3c32debee/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/utils/FunctionClassUtils.java#L58) code for more details.
