### ISSUE TITLE
AWS SQSEvent broken since 3.0.7.RELEASE

### ISSUE THREAD

**Issue by Mike-Petersen** [spring-cloud/spring-cloud-function#551]
**Describe the bug**

The additional Kinesis handling in 3.0.7.RELEASE breaks the SQSEvent handling.

The problem is that the SQSEvent also has the Records field and due to that it is handled as Kinesis Event although it is an SQSEvent.

**Sample**

SQSEvent:
`{
  "Records": [
    {
      "messageId": "19dd0b57-b21e-4ac1-bd88-01bbb068cb78",
      "receiptHandle": "MessageReceiptHandle",
      "body": "Hello from SQS!",
      "attributes": {
        "ApproximateReceiveCount": "1",
        "SentTimestamp": "1523232000000",
        "SenderId": "123456789012",
        "ApproximateFirstReceiveTimestamp": "1523232000001"
      },
      "messageAttributes": {},
      "md5OfBody": "7b270e59b47ff90a553787216d55d91d",
      "eventSource": "aws:sqs",
      "eventSourceARN": "arn:aws:sqs:eu-central-1:123456789012:MyQueue",
      "awsRegion": "eu-central-1"
    }
  ]
}`

KinesisEvent (Stream):

`{
  "Records": [
    {
      "kinesis": {
        "partitionKey": "partitionKey-03",
        "kinesisSchemaVersion": "1.0",
        "data": "SGVsbG8sIHRoaXMgaXMgYSB0ZXN0IDEyMy4=",
        "sequenceNumber": "49545115243490985018280067714973144582180062593244200961",
        "approximateArrivalTimestamp": 1428537600
      },
      "eventSource": "aws:kinesis",
      "eventID": "shardId-000000000000:49545115243490985018280067714973144582180062593244200961",
      "invokeIdentityArn": "arn:aws:iam::EXAMPLE",
      "eventVersion": "1.0",
      "eventName": "aws:kinesis:record",
      "eventSourceARN": "arn:aws:kinesis:EXAMPLE",
      "awsRegion": "eu-central-1"
    }
  ]
}`

**Comment by olegz** [comment]
Glad you raised it now as we are approaching a release. Will certainly fix for 3.0.8.
Thanks!
