### ISSUE TITLE
NPE when testing Supplier-backed aws lambda

### ISSUE THREAD

**Issue by danielburrell** [spring-cloud/spring-cloud-function#552]
```
<dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-function-dependencies</artifactId>
                <version>3.1.0-SNAPSHOT</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
```

I have successfully created a Spring Boot Lambda function, as a Function<>, and also as a Consumer<> (The function returns a value, while the consumer appears to return 'null' when the logs are read).

```
    @Bean
    public Supplier<String> supplier() {
        return () -> "worked";
    }
```

`org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler`

```
FUNCTION_NAME | supplier
MAIN_CLASS | uk.co.package.Masked
```

However the documentation suggests that Suppliers can also be used. When I tried using a valid supplier I got the following in the lambda console when hitting the test button:

```
{
  "errorMessage": "value",
  "errorType": "java.lang.NullPointerException",
  "stackTrace": [
    "java.base/java.util.Objects.requireNonNull(Unknown Source)",
    "reactor.core.publisher.FluxJust.<init>(FluxJust.java:60)",
    "reactor.core.publisher.Flux.just(Flux.java:1214)",
    "org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler.extract(SpringBootStreamHandler.java:71)",
    "org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler.handleRequest(SpringBootStreamHandler.java:55)"
  ]
}
```

I note that it's not possible to invoke the lambda using a empty test message in the lambda creation UI (a blank message results in not being able to save the test message for later use). So I have tried invoking the supplier with an empty json node `{}`, this does not work either. Though you can send an empty message via the step function ui (which results in empty json node being used `{}`)

Can anyone advise what the issue is here? Is a supplier a valid concept in the lambda world? Can you invoke a lambda backed by a supplier?

**Comment by olegz** [comment]
The SpringBootStreamHandler is all but deprecated as we now have a new way of bootstrapping AWS Lambdas with functions - https://docs.spring.io/spring-cloud-function/docs/3.0.10.RELEASE/reference/html/aws.html#_getting_started
Can you please give it a try and see if this issue is still a valid issue?

**Comment by skiley22** [comment]
@olegz I have encountered a similar issue when exposing a Consumer to be invoked via Lambda. It appears that FunctionInvoker is always expecting a response (which would not be available from a Consumer):

```		
Message<byte[]> responseMessage = (Message<byte[]>) this.function.apply(requestMessage);

byte[] responseBytes = responseMessage.getPayload();
```
 An NPE is thrown when `getPayload()` is invoked. This is in version 3.1.0. Please let me know what other information I can provide that might be useful.

**Comment by olegz** [comment]
Thank you @skiley22. Now it makes sense. Just pushed a fix

**Comment by skiley22** [comment]
Awesome!
