### ISSUE TITLE
Spring cloud `Hoxton.SR5` is not compatible with spring boot `2.2.1.RELEASE`

### ISSUE THREAD

**Issue by mohammedalics** [spring-cloud/spring-cloud-function#553]
**Describe the bug**
In spring cloud [Hoxton.SR5 documentation](https://cloud.spring.io/spring-cloud-static/Hoxton.SR5/reference/html/), it mentions the compatibility with spring boot 2.2.1.RELEASE, but it is not. 

By using 
```
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-bus-amqp</artifactId>
		</dependency>
```

It gives below error. 
 
```
***************************
APPLICATION FAILED TO START
***************************
Description:
An attempt was made to call a method that does not exist. The attempt was made from the following location:
    org.springframework.cloud.function.context.config.JsonMessageConverter.<init>(JsonMessageConverter.java:43)
The following method did not exist:
    org.springframework.messaging.converter.AbstractMessageConverter.<init>([Lorg/springframework/util/MimeType;)V
The method's class, org.springframework.messaging.converter.AbstractMessageConverter, is available from the following locations:
    jar:file:/Users/mohammed.ali/.m2/repository/org/springframework/spring-messaging/5.2.1.RELEASE/spring-messaging-5.2.1.RELEASE.jar!/org/springframework/messaging/converter/AbstractMessageConverter.class
It was loaded from the following location:
    file:/Users/mohammed.ali/.m2/repository/org/springframework/spring-messaging/5.2.1.RELEASE/spring-messaging-5.2.1.RELEASE.jar
Action:
Correct the classpath of your application so that it contains a single, compatible version of org.springframework.messaging.converter.AbstractMessageConverter
2020-06-30 09:04:21.909 ERROR 24445 --- [           main] o.s.test.context.TestContextManager      : Caught exception while allowing TestExecutionListener [org.springframework.test.context.web.ServletTestExecutionListener@55634720] to prepare test instance [com.example.demo.DemoApplicationTests@28a6e171]
java.lang.IllegalStateException: Failed to load ApplicationContext
```

**More details** 

The constructor https://github.com/spring-cloud/spring-cloud-function/blob/ec5d929a6599d33c6c27ce3a35034fe7ecef5797/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/context/config/JsonMessageConverter.java#L43 uses the super constructor `protected AbstractMessageConverter(MimeType... supportedMimeTypes)` which is added since org.springframework:spring-messaging:jar:5.2.2.RELEASE but spring boot 2.2.1.RELEASE uses org.springframework:spring-messaging:jar:5.2.1.RELEASE in it is transitive dependencies.  

I open this bug here because I'm not sure if it is a documentation bug or the spring-cloud-function library is using the wrong dependency by using the `AbstractMessageConverter(MimeType... supportedMimeTypes)` constructor. 

**Sample**
Please run the test in https://github.com/mohammedalics/hoxton-sr5-compatibility.git

**Comment by olegz** [comment]
Actually, i believe it should say 2.2.4 of boot. Technically, Hoxton.SR5 and above (we're at SR6) is based on boot 2.3.x while maintaining backward compatibility with the latest 2.2.x

**Comment by mohammedalics** [comment]
@olegz How can the documentation be fixed?

**Comment by olegz** [comment]
I have raised it internally with spring-cloud team

**Comment by olegz** [comment]
Resolved with https://github.com/spring-cloud/spring-cloud-static/commit/74b0f0094ba70c5527deb0cc0940a0e53fdb809e
