### ISSUE TITLE
Spring Cloud Function Deployer with maven location

### ISSUE THREAD

**Issue by PatrickVanbrabant** [spring-cloud/spring-cloud-function#555]
Dear all,

First of all, let me apologize upfront if this is not the right place to ask this question.
In the documentation of SpringCloudFunction, the following is mentioned: 

> At a minimum the user has to provide a spring.cloud.function.location which is a URL or resource location for the archive containing the functions. It can optionally use a maven: prefix to locate the artifact via a dependency lookup (see FunctionProperties for complete details).

When looking for a unit or integration test, in the Spring Cloud Function deployer component, I could not find any example where a function jar is being deployed from a location prefixed with maven:

Also looking at the code, did not reveal much to me.

Could you please explain what the format of this location (with the maven prefix) must be.
Does this maven dependency already have to be defined/present in the pom file, or can it be any valid reference to a maven artifact.
When resolving that artifact dependency, would it be possible to use an enterprise maven repo for the resolving (something like nexus or artifactory).
If so I assume that somewhere a settings.xml file needs to be present.

If maven prefix is not supported (anymore), would it be possible to provide an "http(s)" url to the artifact, or are only file urls allowed?

Many thanks for pointing me into the right direction.

Patrick

**Comment by olegz** [comment]
I think we may have had something in the earlier versions or perhaps docs went ahead of implementation (some times it happiness as well).
In any event I am about to push a fix which has both test and updated docs

Here is the doc fragement

================
And here is the example using Maven URI (taken from one of the tests in `FunctionDeployerTests`):

```java
@SpringBootApplication
public class DeployFunctionDemo {

	public static void main(String[] args) {
		String[] args = new String[] {
				"--spring.cloud.function.location=maven://oz.demo:demo-uppercase:0.0.1-SNAPSHOT",
				"--spring.cloud.function.function-class=oz.demo.uppercase.MyFunction" };

		ApplicationContext context = SpringApplication.run(DeployerApplication.class, args);
		FunctionCatalog catalog = context.getBean(FunctionCatalog.class);
		Function<String, String> function = catalog.lookup("myFunction");

		assertThat(function.apply("bob")).isEqualTo("BOB");
	}
}
```

Keep in mind that Maven resource such as local and remote repositories, user, password and more are resolved using default MavenProperties which 
effectively use local defaults and will work for majority of cases. However if you need to customize you can simply provide a bean of type 
`MavenProperties` where you can set additional properties (see example below).

```java
@Bean
public MavenProperties mavenProperties() {
	MavenProperties properties = new MavenProperties();
	properties.setLocalRepository("target/it/");
	return properties;
}
```

================

We'll be releasing 3.0.9 next week
