### ISSUE TITLE
openwhisk examples of Kamesh are outdated

### ISSUE THREAD

**Issue by cmoulliard** [spring-cloud/spring-cloud-function#556]
**Issue**

 The 2 openwhisk example of Kamesh are outdated as they rely on a old snapshot vesion of the spring cloud function project `<spring-cloud-function.version>1.0.0.BUILD-SNAPSHOT</spring-cloud-function.version>` and use `spring-boot = 1.5`

See: https://github.com/redhat-developer-demos/ow-scf-fruiteason/blob/master/pom.xml#L12-L26

**Comment by olegz** [comment]
@cmoulliard Not sure what does it have to do with this project. Consider rasing the issue with the project owner/maintainer (Kamesh?)
