### ISSUE TITLE
NegotiatingMessageConverterWrapper wrong MimeType inclusion check.

### ISSUE THREAD

**Issue by tzolov** [spring-cloud/spring-cloud-function#557]
**Describe the bug**
The MimeType inclusion check implemented in [NegotiatingMessageConverterWrapper#toMessage](https://github.com/spring-cloud/spring-cloud-function/blob/master/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/context/config/NegotiatingMessageConverterWrapper.java#L122) is incorrect. It is in an inverse order. Instead of `accepted.includes(supportedConcreteType)` the check should be `supportedConcreteType.includes(accepted)`.

**Comment by garyrussell** [comment]
That code is pretty brittle - it assumes converters only return concrete supported types (and then goes ahead and modifies the header - ugh).

```java
		if (accepted != null) {
			for (MimeType supportedConcreteType : delegate.getSupportedMimeTypes()) {
				if (accepted.includes(supportedConcreteType)) {
					// Note the use of setHeader() which will set the value even if already present.
					accessor.setHeader(MessageHeaders.CONTENT_TYPE, supportedConcreteType);
					Message<?> result = delegate.toMessage(payload, accessor.toMessageHeaders(), conversionHint);
					if (result != null) {
						return result;
					}
				}
			}
		}
```

But reading the comment of the commit, I see why it's needed (if the `accepted` type contains a wildcard).

I think we need something like...

```java
		if (accepted != null) {
			Message<?> result = null;
			for (MimeType supportedConcreteType : delegate.getSupportedMimeTypes()) {
				if (supportedConcreteType.isWIldcardType() || supportedConcreteType.isWildcardSubtype()) {
					result = delegate.toMessage(payload, accessor.toMessageHeaders(), conversionHint);
				}
				if (result == null && accepted.includes(supportedConcreteType)) {
					// Note the use of setHeader() which will set the value even if already present.
					accessor.setHeader(MessageHeaders.CONTENT_TYPE, supportedConcreteType);
					result = delegate.toMessage(payload, accessor.toMessageHeaders(), conversionHint);
				}
				if (result != null) {
					return result;
				}
			}
		}
```

That will support converters that can handle wildcards, while retaining the current functionality.

cc/ @tzolov @artembilan @olegz

**Comment by artembilan** [comment]
Yes, I agree. We definitely can't have `MessageHeaders.CONTENT_TYPE` as a `MediaType.ALL`.
