### ISSUE TITLE
Debug SpringBootRequestHandler

### ISSUE THREAD

**Issue by shero1111** [spring-cloud/spring-cloud-function#559]
Hello,

I have an custom SpringBootRequestHandler, but it doesn´t get invoked when testing with Postman...whereas my function gets invoced properly.

```
public class MySpringBootApiGatewayRequestHandler extends SpringBootRequestHandler<APIGatewayProxyRequestEvent, APIGatewayProxyResponseEvent> {

    private static final Logger LOGGER = LoggerFactory.getLogger(MySpringBootApiGatewayRequestHandler.class);
	
    @Autowired
    private ObjectMapper mapper;

    @Autowired
    private FunctionInspector inspector;

    @Autowired
    ApplicationContext ctx;

    // Constructors
    @Override
    protected Object convertEvent(APIGatewayProxyRequestEvent event) {

        Object body = "";

        if (event.getBody() != null) {
            body = deserializeBody(event.getBody());
        }
//        if (functionAcceptsMessage()) {
//            return new GenericMessage<Object>(body, getHeaders(event));
//        } else {
//            return body;
//        }
        
        LOGGER.debug("**My Request event output: " + event.toString());
        return body;
    }

    private Object deserializeBody(String body) {
    	System.out.println(); //TODO: use ObjectMapper
		return body;
	}

//	private boolean functionAcceptsMessage() {
//    	Object bean = ctx.getBean(ctx.getDisplayName());
//		Boolean isMessage = inspector.isMessage(bean);
//		return isMessage;
//	}

	private MessageHeaders getHeaders(APIGatewayProxyRequestEvent event) {
        LOGGER.debug("**My Request event output: " + event.toString());
		
        Map<String, Object> headers = new HashMap<String, Object>();
        if (event.getHeaders() != null) {
            headers.putAll(event.getHeaders());
        }
        if (event.getQueryStringParameters() != null) {
            headers.putAll(event.getQueryStringParameters());
        }
        if (event.getPathParameters() != null) {
            headers.putAll(event.getPathParameters());
        }
        headers.put("httpMethod", event.getHttpMethod());
        headers.put("request", event);
        
        return new MessageHeaders(headers);
    }
	
}
```

How can I test my implementation and when gets the SpringBootRequestHandler triggered?

**Comment by olegz** [comment]
SpringBootRequestHandler  is a bit outdated and soon to be deprecated. Have you looked at a new way of working with AWS Lambdas - https://docs.spring.io/spring-cloud-function/docs/3.0.8.RELEASE/reference/html/aws.html#_getting_started. Basically you don't have to do any of the above and instead use the new `FunctionInvoker` and only write your function and spring-cloud-function will take care of the rest.
You can also look at https://github.com/spring-cloud/spring-cloud-function/blob/master/spring-cloud-function-adapters/spring-cloud-function-adapter-aws/src/test/java/org/springframework/cloud/function/adapter/aws/FunctionInvokerTests.java for more details on how to test

**Comment by AjitDas** [comment]
@olegz `FunctionInvoker` is nice but it doesn't support many of the events and many limitation on parsing the input/output to custom POJOs. I have created couple of issues with details #563 #562 please take a look at it.

Unfortunately we can implement all the missing events using extension of this `SpringBootRequestHandler`, if we are planning to deprecate this then we should extend `FunctionInvoker` to support all those possible event types AWS lambda can support.

**Comment by olegz** [comment]
@AjitDas i just commented on that issues but yes, S3 is already supported (as of last week) and the rest i am hoping to fit into the next 3.0.9 release. Thank you for raising these issues.

**Comment by olegz** [comment]
@AjitDas I am going to close this one as there is no action to be taken and S3 is already part of the master and 3.0.x branch. 
Feel free to raise individual issue per event
