### ISSUE TITLE
Support FunctionInvoker to allow override convertEvent and convertOutput

### ISSUE THREAD

**Issue by AjitDas** [spring-cloud/spring-cloud-function#562]
I am using generic `org.springframework.cloud.function.adapter.aws.FunctionInvoker` of `spring-cloud-function-adaptor-aws-3.0.8.RELEASE.jar` as request handler to invoke my function. But this class ties APIs and models to be AWS specific events rather than simple POJO based input/output for functions.

For example am trying to use SQS Event to trigger the lambda and using this class expects my function to be having input as `com.amazonaws.services.lambda.runtime.events.SQSEvent` instead of my simple POJO class. There is nothing wrong with this approach other than it creates a hard dependencies on my functions which could have been simpler, my tests (junit and integration tests) could be much simpler to have domain POJO based implementation. If this class can expose the methods as `protected` for input/ouput conversion (currently it's put under private method) then we can subclass and override it with as per need and use it effectively.

Having said that it's also worth to note that I can very well do this by extending `org.springframework.cloud.function.adapter.aws.SpringBootRequestHandler` with my own input/output conversion. With my extended class/handler am converting `SQSEvent` to my POJO by overriding `convertEvent` method. It also allows me to define a generic output object which wraps my function output with adding some more context information (like correlation-id etc).

I will be happy to share further code details if it would help to understand the issue. Please let me know.

**Comment by olegz** [comment]
The `.aws.FunctionInvoker` is by design specific to AWS. We have the same in Google etc.
What you're looking for is conversion of inputs and outputs from raw representation to POJO which is also supported already in Spring Cloud Function and is one of the extension points. 
That said, i'll keep this issue open with the idea to provide clear documentation on how to do it as well as add tests that would aside from validation would serve as an example.

**Comment by AjitDas** [comment]
thank you !!! @olegz for the details, sounds like a plan.

**Comment by olegz** [comment]
You can see details from commit message, but basically I've added documentation on type conversion and how to extend it (user defined converters)
There is also a test and few fixes went into the actual FunctionInvoker
