### ISSUE TITLE
Ass support for SNSEvent  (AWS)

### ISSUE THREAD

**Issue by AjitDas** [spring-cloud/spring-cloud-function#563]
Currently `org.springframework.cloud.function.adapter.aws.FunctionInvoker.generateMessage()` supports only `KinesisEvent`, `SQSEvent` and `APIGatewayProxyRequestEvent` to process, can we add more event types to support to this list. For example few common event types used to trigger AWS lambda are `S3Event` and `SNSEvent`.

There is also a wrong text saying incoming JSON payload as ApiGateway Event, even though it could be of any of the event type. Mostly this is a typo and was overlooked not meant to be represented like this.

```
if (logger.isInfoEnabled()) {
	logger.info("Incoming JSON for ApiGateway Event: " + new String(payload));
}
```

**Comment by olegz** [comment]
Just an FYI, S3Event is also supported with the latest 3.1.0-M2 and is back ported to 3.0.9 which will be released next week.
