### ISSUE TITLE
Make spring-cloud-function-deployer's FunctionArchiveDeployer public

### ISSUE THREAD

**Issue by jamesmmchugh** [spring-cloud/spring-cloud-function#564]
It would be great if the FunctionArchiveDeployer class could be made public so that it can be instantiated programtically.

Obviously this would move lifecycle management of the FunctionArchiveDeployer into the instantiator's hands (as it would exist outside of the autoconfiguration), but conceptually this could allow someone to write customised deployer that could load multiple external jars into the same spring context, by instantiating and managing multiple FunctionArchiveDeployers in a single context (whereas the autoconfiguration only allows for one instance).

**Comment by olegz** [comment]
I would rather hear about the customization you may be looking for, since `FunctionArchiveDeployer` was definitely designed as an internal implementation

**Comment by jamesmmchugh** [comment]
@olegz - I have a use case where I want to host multiple functions from a single deployer for performance and routing reasons, and I don't want to package those functions in the same jar for isolation purposes. This can be achieved by writing an app that creates multiple child application contexts (with the necessary properties defined), each which runs their own deployer autoconfigruation and loads a corresponding jar.

The overhead of loading a new application context for each function isn't massive, but it would be nice to be able to remove it. I've tested this by placing a class in the spring packages that extends FunctionArchiveDeployer and makes it (and the deploy/undeploy methods) public. Which then allowed me to write a simple SmartLifecycle bean that manages multiple FunctionArchiveDeployer. It's basically a copy of the existing auto configuration, but accepts and manages a list of functions (properties and their corresponding FunctionArchiveDeployer).

It would be a very small change (i.e. make class public, and the deploy/undeploy methods) to provide added flexibility, but I appreciate it might not be a common use case and has other conotations. Interested to hear your thoughts.

**Comment by olegz** [comment]
> The overhead of loading a new application context for each function isn't massive, but it would be nice to be able to remove it. I've tested this by placing a class in the spring packages that extends FunctionArchiveDeployer and makes it (and the deploy/undeploy methods) public. Which then allowed me to write a simple SmartLifecycle bean that manages multiple FunctionArchiveDeployer. It's basically a copy of the existing auto configuration, but accepts and manages a list of functions (properties and their corresponding FunctionArchiveDeployer).

I hear you. . .
But given that we already create an instance of `FunctionArchiveDeployer`, what happens to it?

**Comment by olegz** [comment]
I guess I would be more interested in providing support for this within the framework instead of exposing something public which would create an extra maintenance overhead.   

So how do you know that you need to create more than one `FunctionArchiveDeployer`? Do you supply somehow multiple URLs?

Would it be possible for you to create a small project and push it to github so we can better understand what you're doing and see if we could bring this idea into the franework?

**Comment by jamesmmchugh** [comment]
I'll try and find time to put a small sample together, unfortunately I can't share what I have as it's on a confidential project. 

As a basic description I have a custom class that implements `SmartLifecycle`, and keeps a map of a `String` key -> `(Public)FunctionArchiveDeployer`.

I'm using it so that I can load multiple functions (from separate jars) in, at runtime (rather than startup), and then switch which function is executed based on some conditions within the application.

I'm not sure if this is a sensible use-case for spring-cloud-function, i've been looking at other options like https://pf4j.org/ that share many concepts with the spring-cloud-function-deployer (like isolated classloaders etc.) but isn't aimed solely at functions, and without some of the added benefits of the deployer like type resolution etc.

**Comment by olegz** [comment]
@jamesmmchugh would it be simpler if we were to allow you to specify multiple locations (e.g., multiple JARs)?

**Comment by olegz** [comment]
@jamesmmchugh any updates?

**Comment by olegz** [comment]
I am going to close this due to inactivity. Feel free to reopen or raise a new one
