### ISSUE TITLE
Jackson-module-kotlin is not used automatically to de-serialize  kotlin classes

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-function#567]
@tobske commented on [Fri Jul 17 2020](https://github.com/spring-cloud/spring-cloud-stream/issues/2008)

**Describe the issue**
If you have jackson-module-kotlin on your classpath it gets automatically registered as described in [spring framework documentation](https://docs.spring.io/spring/docs/5.2.7.RELEASE/spring-framework-reference/languages.html#kotlin-classes-interfaces). The ObjectMapper with the registered kotlin module should then be used by Spring Cloud Stream to de-serialize incoming JSON but another ObjectMapper seems to be used. The ObjectMapper that is used gets constructed in `MappingJackson2MessageConverter::initObjectMapper`. The result is that a kotlin data class without any additional annotations can't be de-serialized successfully.

**To Reproduce**
1. Write a kotlin data class without any annotations
`data class Message(val header: String)`
2. Write functional consumer bean using that data class
```
@Bean
    fun messageConsumer(): Consumer<Message> {
        return Consumer { msg -> println(msg) }
    }
```
3. Send some valid JSON in a test to that consumer
```
    InputDestination inputDestination = context.getBean(InputDestination.class);
    inputDestination.send(new GenericMessage<>(data));
```
4. Receiving following error
`Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `io.aviatar.ebas.acms.AcmsMessage` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
`

**Version of the framework**
Hoxton.SR5 and 2.3.1.RELEASE

**Expected behavior**
Data class gets de-serialized without any further configuration.

**Comment by myhelloos** [comment]
my workaround: copy the bean definition in `JacksonAutoConfiguration` and add the `KotlinModule`


```kotlin
@Bean
    @Scope("prototype")
    fun jacksonObjectMapperBuilder(applicationContext: ApplicationContext, customizers: List<Jackson2ObjectMapperBuilderCustomizer>): Jackson2ObjectMapperBuilder {
        val builder = Jackson2ObjectMapperBuilder()
        builder.applicationContext(applicationContext)
        customizers.forEach {customizer->
            customizer.customize(builder)
        }
        // workaround：手动加入kotlin module
        builder.modulesToInstall(KotlinModule::class.java)

        return builder
    }
```

**Comment by dplusic** [comment]
[This commit](https://github.com/spring-cloud/spring-cloud-function/commit/03babc429d8306b739f88862714d1efcb1d08478) doesn't seem to fully address the issue. When using only Spring Cloud Stream, the additional code in the commit may not work since it requires Spring Web, which is not being used. Can you please work on this part further?
