### ISSUE TITLE
Special handling of functions that produce Optional output

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-function#57]
A function that maps `Foo` to `Optional<Bar>` is like a shorthand for a `Flux.filter()` on the output of the flux function.

**Comment by olegz** [comment]
I have spiked it recently and can't seem to see much value at the moment. 
For example, if user provides a signature of `Function<Foo, Optional<Bar>>`, then even if we filter implicitly, the signature of the function won't change and user will still receive Optional which (if he/she doesn't know about "our" filtering) then would still be interrogated/filtered by such user. 

Anyway, i think it needs more time to bake.

**Comment by olegz** [comment]
I am going to close it as part of the clean up of old issue that get no traction. Feel free to reopen or open new one with more details
