### ISSUE TITLE
Allow GCF Adaptor to use Jackson?

### ISSUE THREAD

**Issue by sappenin** [spring-cloud/spring-cloud-function#570]
**Is your feature request related to a problem? Please describe.**
When using [Google Cloud Functions](https://cloud.spring.io/spring-cloud-function/reference/html/gcp.html#_http_functions), I'm unable to get Jackson to become registered as the preferred JsonMessageConverter. In [FunctionInvoker.java](https://github.com/spring-cloud/spring-cloud-function/blob/master/spring-cloud-function-adapters/spring-cloud-function-adapter-gcp/src/main/java/org/springframework/cloud/function/adapter/gcp/FunctionInvoker.java#L69) it seems Gson is hard-coded, and there doesn't seem to be a way to override this setting.

**Describe the solution you'd like**
I'd like to be able to simply set `spring.cloud.function.definition` to `jackson` (or better yet, merely add fasterxml deps to the classpath and have Jackson get picked up by default via [ContextFunctionCatalogAutoConfiguration](https://github.com/spring-cloud/spring-cloud-function/blob/f0ef8791a84377e4f015dc94903209db52f96fed/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/context/config/ContextFunctionCatalogAutoConfiguration.java#L156)).

**Describe alternatives you've considered**
I've considered GSON but would prefer to use Jackson.

**Question**: _Does deploying a Spring Cloud function to GCP require GSON for some reason that I'm unaware of?_

**Comment by meltsufin** [comment]
@olegz Do you remember why we hard-coded that setting for GSON?
I think if we allow Jackson, it should work too.

**Comment by sappenin** [comment]
One other thing I noticed over the weekend while experimenting with Jackson in the GFC adaptor -- [this piece of code](https://github.com/spring-cloud/spring-cloud-function/blob/master/spring-cloud-function-adapters/spring-cloud-function-adapter-gcp/src/main/java/org/springframework/cloud/function/adapter/gcp/FunctionInvoker.java#L97) errantly emits the Content Type header using the Spring Messaging header-name (i.e., `contentType`) but the actual HTTP header name should be `content-type`. When the function is actually deployed to Google, the google proxy will think the response is of type `octet-stream` instead of JSON because the proxy doesn't understand `contentType` as a header.

At first I thought this was maybe due to me missing a `org.springframework.messaging.converter.MessageConverter`in my project, but it turns out the FunctionInvoker seems to be setting the content type incorrectly (see above). Maybe I'm missing something, or perhaps that particular problem should be filed as a separate issue.

**Comment by olegz** [comment]
It may be as easy as injecting JsonMapper for which we provide two implementations at the moment which could be configured.
I'll take a crack at it next week

**Comment by sappenin** [comment]
@olegz thanks for fixing this one. Do you know if the error described in [my comment above](https://github.com/spring-cloud/spring-cloud-function/issues/570#issuecomment-668298222) about the `contentType` was fixed? I haven't verified it yet, but wanted to double check if there was perhaps another GH issue created for that one?

**Comment by olegz** [comment]
Actually, I didn't do anything specific for that header. I certainly would not have any issues duplicating a header for GCF case if that is what's needed, but given that 95% code is actually written and mostly maintained by Google guys, I would think that that is somehow taken care of. Any chance you can try and see if you still have that issue?

Also, I don't think I've provided details, but in case you have both Gson and Jackson on the classpath and you want to explicitly use Jackson, set `spring.cloud.function.preferred-json-mapper=jackson`.
