### ISSUE TITLE
GraalVM support

### ISSUE THREAD

**Issue by AlexanderSchiff** [spring-cloud/spring-cloud-function#586]
The slow boot time of the JVM is magnified in the Serverless environment. Java lags behind NodeJS and Python significantly in cold-start times in AWS Lambda in particular. 

GraalVM is an alternative to the traditional JVM, it uses AOT compilation to significantly speed up boot times.

Spring and Oracle are collaborating to get fully-fledged GraalVM support in Spring. Maybe the Spring Cloud Function team could implement GraalVM support, as it is more narrow than the whole of Spring Framework.

On my team, we are considering switching to Micronaut or NodeJS in order to speed up boot times. I'm a big Spring fan, so I'm hoping we won't have to do this.

AWS Lambda Runtime Benchmarks: https://medium.com/the-theam-journey/benchmarking-aws-lambda-runtimes-in-2019-part-i-b1ee459a293d
GraalVM: https://www.graalvm.org/
Spring GraalVM project: https://github.com/spring-projects-experimental/spring-graalvm-native
Spring-related GraalVM Issues: https://github.com/oracle/graal/labels/spring

**Comment by SaikatCool** [comment]
I too have the same concern. 
Can the authors of Spring guide us here?

**Comment by olegz** [comment]
@AlexanderSchiff So, I am not sure what exactly is expected from this issue as you have already included most of the relevant information.
The repo for Spring GraalVM project includes [3 function samples](https://github.com/spring-projects-experimental/spring-graalvm-native/tree/master/spring-graalvm-native-samples):
- function-aws
- function-netty-fun
- function-netty

May be that part was not clear.

Also, there is a blog from @dsyer on this [Spring Cloud Function Native Images](https://spring.io/blog/2020/05/04/spring-cloud-function-native-images)

Anyway, please let us know if anything is missing

**Comment by olegz** [comment]
Closing it due to inactivity after a provided answer. Feel free to reopen or raise a new one if you still believe there is an issue
