### ISSUE TITLE
Logging Improvements.

### ISSUE THREAD

**Issue by garyrussell** [spring-cloud/spring-cloud-function#592]
- `SimpleFunctionRegistry.logger` is hard-coded with the class name; should use `getClass()` so subclasses get the right logger name.

- Several places where `debug()` log strings are unconditionally assembled.

e.g.:

```java
logger.debug("Failed to discover function '" + definition + "' in function catalog. "
	+ "Function available in catalog are: " + this.getNames(null) + ". This is generally "
		+ "acceptable for cases where there was no intention to use functions.");
```

This should be under `isDebugEnabled()` to avoid the message assembly when it is not enabled. Or, consider using Spring's `LogAccessor`, which takes a supplier:

```java
logger.debug(() -> "Failed to discover function '" + definition + "' in function catalog. "
	+ "Function available in catalog are: " + this.getNames(null) + ". This is generally "
		+ "acceptable for cases where there was no intention to use functions.");
```

**Comment by olegz** [comment]
This seem to be relevant to 3.0.x only since master has a completely re-written implementation of FunctionRegistry. But I'll check anyway.
