### ISSUE TITLE
Spring Cloud Function can not deserealize mulitpart file types

### ISSUE THREAD

**Issue by SwapnilKhante** [spring-cloud/spring-cloud-function#597]
**Describe the bug**

Trying to write a function like following 

```
  @Bean
  public Function <MultipartFile, String> uppercase() {
    return value -> value.getOriginalFilename();
  }
```
This function will be deployed as AWS lambda which will be triggered by API gateway. API gateway end point is exposing a post request with type multipart/form-data type.

Getting following error :
```
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: 
Cannot construct instance of org.springframework.web.multipart.MultipartFile` 
(no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, 
have custom deserializer, or contain additional type information

```

**Comment by SwapnilKhante** [comment]
Hi, Is there any update on this issue ?

**Comment by olegz** [comment]
The support for MultipartFile has been fixed. You can get more details from the two test cases that are part of the fix. Please let us know if you believe something is missing>
