### ISSUE TITLE
type parameter discovery for beans that are not registered by component scan

### ISSUE THREAD

**Issue by xiazuojie** [spring-cloud/spring-cloud-function#601]
**Describe the bug**
There is an issue in discovering type parameters (`S` and `T`) of `Function<Flux<S>, Flux<T>>` beans if they are not registered by component scan **and** their declaringClassNames are not `Function<Flux<S>, Flux<T>>`.

When beans are registered by component scan, their type parameters can be accurately discovered (thanks to this [fix](https://github.com/spring-cloud/spring-cloud-function/issues/474)).
This issue is for beans that have been registered by other means.

Unlike [this](https://github.com/spring-cloud/spring-cloud-function/issues/474), it simply uses declaringClassName, not doing deep type discovery. [code](https://github.com/spring-cloud/spring-cloud-function/blob/a7104e489ec1f608dc7229b9faad12ca6eedf460/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/context/config/FunctionContextUtils.java#L76). 
```java
		if (source instanceof MethodMetadata) {
			param = findBeanType(definition, ((MethodMetadata) source).getDeclaringClassName(), ((MethodMetadata) source).getMethodName());
		}
```
**Sample**
A ``Function<Flux<S>, Flux<T>>`` class.
```java
public class HelloWorld implements Function<Flux<String>, Flux<JSONObject>> {

    @Override
    public Flux<JSONObject> handle(Flux<String> s) {
        ...
    }
}
```
Issue: a bean registered by java config and its declaringClassName is ``HelloWorld``, not ``Function<Flux<S>, Flux<T>>``. Having issue discovering its reactive type parameters.
```java
@Configuration
public class FunctionalBeans {

    @Bean
    public HelloWorld helloWorld() {
        return new HelloWorld();
    }
}

```
When invoking the function, the framework throws ``java.lang.ClassCastException: java.lang.String cannot be cast to reactor.core.publisher.Flux`` due to its type parameter being lost.
**Workaround**
The issue can be worked around by changing the bean's declaringClassName to ``Function<Flux<S>, Flux<T>>``
```java
@Configuration
public class FunctionalBeans {

    @Bean
    public Function<Flux<String>, Flux<JSONObject>> helloWorld() {
        return new HelloWorld();
    }
}
```

**Comment by olegz** [comment]
Actually this may have ben fixed prior as I could not reproduce it, but do remember similar issue from a while back. In any event, I've added a test to validate this scenario. The test is also back ported to 3.0.x branch
