### ISSUE TITLE
In batch-mode consumer, for messages with collection payload, NegotiatingMessageConverterWrapper cannot divide headers for each element.

### ISSUE THREAD

**Issue by miki1029** [spring-cloud/spring-cloud-function#603]
**Is your feature request related to a problem? Please describe.**
I used spring-cloud-stream `3.0.3.RELEASE` and recently upgraded to spring-cloud-stream `3.0.8.RELEASE`.

I am using a custom message converter that inherits AbstractMessageConverter and the stream function signature is `Function<Flux<List<MyClass>>, Flux<Message<MyResultClass>>>`.

I found my message being converted through the `SimpleFunctionRegistry` class. And I could find that my payload is split into each element in the part of the link below.

<https://github.com/spring-cloud/spring-cloud-function/blob/v3.0.8.RELEASE/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/context/config/NegotiatingMessageConverterWrapper.java#L84>

However, the header information was not split into each element.
I needed the header information (for kafka key) when converting my message. However, the header contained multiple elements of information, and the payload had a single element of information, so I couldn't convert the message correctly.

**Describe the solution you'd like**
* Solution 1 : The header of the message should contain only the header of a single element.
* Solution 2 : Or, in order to know what index to refer to in the multiple elements header, the index of the message must be provided in the header.

**Describe alternatives you've considered**
* Solution 1 : Since the message contains only the header of a single element, the custom message converter can access the specific message header correctly.
* Solution 2 : Custom message converter can correctly access their own header using index.

**Additional context**
![image](https://user-images.githubusercontent.com/4443853/98241397-3cd08080-1fae-11eb-97c0-cfc155593d6b.png)

**Comment by olegz** [comment]
I am not sure I follow. Based on your description you need to convert message in some "special way" and chose to implement custom MessageConverter. We're giving you all the headers and you can do what you need to do. We are not aware of any semantics with regard to Kafka or anything else. That would have to be done by user.
Please let me know if I am missing something

**Comment by olegz** [comment]
I am closing it due to lack of follow up from the original reporter. Feel free to reopen it and provide more detals
