### ISSUE TITLE
CloudEvent responses should try harder to be valid / semantically correct in the output messages

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-function#606]
Copying headers from input to output of a `Function` is incredibly useful as a default, but as we know from experience with HTTP headers, the output sometimes needs to be sanitized or massaged to prevent issues. A `Function` that transforms a `CloudEvent` into another `CloudEvent` is really easy to write, but the output by default has some issues at present, mainly caused by copying headers without paying attention to their semantics. Let's look at the 4 mandatory headers (attributes) in a `CloudEvent`:

1. The `ce-source` is safe to copy, but the user might want to change it quite commonly.

2. The combination of `ce-source` and `ce-id` is supposed to be unique (globally). We could implement this easily just by copying the `Messsage` id over into the `ce-id` header.

3. The `ce-type` is often going to be used by the consumer to route the message to the next consumer. If we just blindly copy it, then you end up in an infinite loop, potentially. So copying `ce-type` is a bad default, but `CloudEvents` have to have a type. So we need a better default. E.g. appending the incoming type with the name of the function or something.

4. The `ce-specversion` is safe to copy, but the user might want a convenient way to flip it.

Where the user probably cares about things, providing a simple programming or configuration model for function registrations or implementations would make sense.

**Comment by olegz** [comment]
Related to #422

**Comment by olegz** [comment]
This has been addressed by defining `CloudEventAttributesProvider` which when configured as `@Bean` will be called by the framework to set Cloud Event attributes(headers) on the outgoing `Message`. The default strategy is also provided with the following rules.

- id - generated UUID
- type - name of the payload type
- specversion - 1.0
- source - the name of the application
```
@FunctionalInterface
public interface CloudEventAttributesProvider {
	/**
	 *
	 * @param attributes instance of {@link CloudEventAttributes}
	 */
	void generateDefaultCloudEventHeaders(CloudEventAttributes attributes);
}
```
