### ISSUE TITLE
SimpleFunctionRegistry failing to deserialise JSON for a Flux of non-Collection when using MappingJackson2MessageConverter

### ISSUE THREAD

**Issue by 0x006EA1E5** [spring-cloud/spring-cloud-function#612]
**Describe the bug**
Since 3.0.11, we get a JSON deserialisation problem when working with `MappingJackson2MessageConverter` and a FunctionRegistration `Flux<MyClass>` where `MyClass` is not a `Collection`

There is an existed test case at `SimpleFunctionRegistryTests#testReactiveFunctionMessages` which tests `Function<Flux<Message<List<Person>>>` but not `Function<Flux<Message<Person>>`, and only with GSON, not Jackson

It looks like this causes `convertWithHint = true` in `FunctionInvocationWrapper#convertInputValueIfNecessary`, and therefore we deserialise in `MappingJackson2MessageConverter#convertFromInternal` using `this.objectMapper.readerWithView(view).forType(javaType).readValue((byte[]) payload)`

This ends up with an object of the required type being instanced, but none of the setters being called, so we get `null` values for the fields.

**Sample**
I have a PR ready that I will link here later.

The test looks more or less like 
```
	@SuppressWarnings({ "rawtypes", "unchecked" })
	@Test
	public void testReactiveFunctionMessageJackson() {
		FunctionRegistration<ReactiveFunction> registration = new FunctionRegistration<>(new ReactiveFunction(), "reactive")
			.type(FunctionType.of(ReactiveFunction.class));

		SimpleFunctionRegistry catalog = new SimpleFunctionRegistry(this.conversionService,
			new CompositeMessageConverter(Collections.singletonList(new MappingJackson2MessageConverter())));
		catalog.register(registration);

		Function lookedUpFunction = catalog.lookup("reactive");

		assertThat(lookedUpFunction).isNotNull();
		Flux<String> result = (Flux<String>) lookedUpFunction
			.apply(Flux.just(MessageBuilder
				.withPayload("{\"name\":\"item\"}")
				.setHeader(MessageHeaders.CONTENT_TYPE, "application/json")
				.build()
			));
		Assertions.assertEquals(result.blockFirst(), "item");
	}

	private static class ReactiveFunction implements Function<Flux<Message<Person>>, Flux<String>> {

		@Override
		public Flux<String> apply(Flux<Message<Person>> flux) {
			return flux
				.map(Message::getPayload)
				.map(Person::getName);
		}
	}
```

**Comment by aidoan** [comment]
I think it's had been fixed in #608

**Comment by 0x006EA1E5** [comment]
I am not sure, as my issue seems to go through the `if (value instanceof Message<?>) { ` path, which #602 appears not to touch.  I will look further this week 🤔

**Comment by 0x006EA1E5** [comment]
I have a better fix and test for this now, will push shortly

**Comment by 0x006EA1E5** [comment]
Maybe be related to https://github.com/spring-cloud/spring-cloud-stream/issues/2054

**Comment by olegz** [comment]
Resolves with https://github.com/olegz/spring-cloud-function/commit/995b3425a8fdbac9c98b1b543f313906eb1ccf00

**Comment by 0x006EA1E5** [comment]
Hi @olegz it looks like this isn't released yet in 3.0.x

When were you planning to release it?

Unreleased code: https://github.com/spring-cloud/spring-cloud-function/blob/3.0.x/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/context/catalog/SimpleFunctionRegistry.java#L828

Latest 3.0.x (3.0.12.RELEASE) https://github.com/spring-cloud/spring-cloud-function/blob/v3.0.12.RELEASE/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/context/catalog/SimpleFunctionRegistry.java#L831

**Comment by singulart** [comment]
In which version have this been fixed, please? Facing the same issue..

**Comment by olegz** [comment]
The latest version for 3.0.* is 3.0.14.RELEASE, so please upgrade and let me know
