### ISSUE TITLE
Autowiring not working in sample: HelloHandler

### ISSUE THREAD

**Issue by Telamon-m** [spring-cloud/spring-cloud-function#614]
**Describe the bug**
- in the azure sample with HelloHandler it is not possible to get injected with any component. If you e. g. want to get any service through @Autowired it will not work.
- For me it looks like this class is not managed at all by spring boot
- I'm using version 2.3.4.RELEASE of spring boot

Should it work at all?

**Comment by olegz** [comment]
Please provide more details as to what you are trying t inject and where

**Comment by olegz** [comment]
Closing it due to lack of follow up from the reporter
