### ISSUE TITLE
GCP Adapter and Maven Multi module projects

### ISSUE THREAD

**Issue by bpenergy** [spring-cloud/spring-cloud-function#615]
Hello,

I have a maven multi module project and I'm not able to use function-maven-plugin.

I have two modules: core and function.

function module contains core module as dependency and have the following plugin configuration:

`<plugin>
   <groupId>com.google.cloud.functions</groupId>
   <artifactId>function-maven-plugin</artifactId>
   <version>0.9.5</version>
   <configuration>
      <functionTarget>org.springframework.cloud.function.adapter.gcp.GcfJarLauncher</functionTarget>
      <port>8080</port>
   </configuration>
</plugin>
`

When I run the function plugin, I have a dependency error:

Failure to find core:pom:0.0.1-SNAPSHOT in https://repo.spring.io/libs-snapshot-local was cached in the local repository..

How can I debug the function?

Thanks,

Phil.

**Comment by meltsufin** [comment]
Would you be able to provide a sample project that reproduces the issue?
cc/  @eamonnmcmanus

**Comment by eamonnmcmanus** [comment]
(Or at least the `pom.xml` from the problematic project.)

**Comment by bpenergy** [comment]
In fact, it was the parent pom.xml that causes an issue.

I reproduced a project from scratch without any issues.

**Comment by scorsi** [comment]
@bpenergy did you know what should cause that issue ? I have exactly the same error...
