### ISSUE TITLE
AWS Lambda does not work

### ISSUE THREAD

**Issue by kitkars** [spring-cloud/spring-cloud-function#618]
I just cloned aws sample project. packaged as jar.

https://github.com/spring-cloud/spring-cloud-function/tree/master/spring-cloud-function-samples/function-sample-aws

```
	@Bean
	public Function<String, String> uppercase() {
		return value -> value.toUpperCase();
	}
```
This is what I get when I use the handler as `org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest`

```
FunctionInspector is deprecated. There is no need to access FunctionRegistration directly since you can interogate the actual looked-up function (see FunctionInvocationWrapper.: java.lang.UnsupportedOperationException
java.lang.UnsupportedOperationException: FunctionInspector is deprecated. There is no need to access FunctionRegistration directly since you can interogate the actual looked-up function (see FunctionInvocationWrapper.
    at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry.getRegistration(SimpleFunctionRegistry.java:138)
    at org.springframework.cloud.function.adapter.aws.FunctionInvoker.start(FunctionInvoker.java:137)
```

- What is the alternative for `SpringBootRequestHandler` ? It says deprecated. but does not provide info what else to use?
- It would be great if the doc provides detailed steps. I can also update the doc If I know the steps!! :(
` it will be deployable in AWS if you get the JAR file laid out right. `

**Comment by olegz** [comment]
This is actually a regression on the master due to the recent improvements in FunctionCatalog implementation. We will address it before the release. That said you should not have any issues 3.0.12.RELEASE

**Comment by kitkars** [comment]
@olegz i am really sorry to say this - take a look at this https://github.com/spring-cloud/spring-cloud-function/issues/619
It still does not work.
Please do not mistake me with my question. Have you tried running yourself in recent times? Can you share the dependencies and sample code you had used.
