### ISSUE TITLE
FunctionTypeUtils.getGenericType reporting wrong generic type for  Message

### ISSUE THREAD

**Issue by ncheema** [spring-cloud/spring-cloud-function#625]
**Describe the bug**

 [FunctionTypeUtils.getGenericType](https://github.com/spring-cloud/spring-cloud-function/blob/master/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/context/catalog/FunctionTypeUtils.java#L90) is   invoking `getImmediateGenericType` **twice** , when type is a `Message<T>`

This side-effect was introduced as part of refactor PR https://github.com/spring-cloud/spring-cloud-function/commit/4936a8676dfc48db884c3456681b16958a47bcc8, where we attempted to refactor changes for  `FunctionTypeUtils.getGenericType` which were introduced  via [PR](https://github.com/spring-cloud/spring-cloud-function/pull/543/files#diff-06be5c997416a32fc667fe38a845882b3c1e7b5577521ea85f67f963214bdba6R72-R80).

During the refactor we combined the condition for the `publisher` and `message` but forgot to remove  the original condition for the `message`. 

**Side effect: In CloudStream  `List<Message<T>>` are being converted to  `List<T>`**

### Original 
```java
public static Type getPayloadType(Type type) {
  if (isPublisher(type)) {
	  type = getImmediateGenericType(type, 0);
  }
  if (isMessage(type)) {
	  type = getImmediateGenericType(type, 0);
  }
  return type;
}
```
### Post Refactor
```java
public static Type getGenericType(Type type) {
  if (isPublisher(type) || isMessage(type)) {
	  type = getImmediateGenericType(type, 0);
  }
  if (isMessage(type)) {    // <<<<<<<<< forgot to remove this condition >>>>>>>>>
	  type = getImmediateGenericType(type, 0);
  }
  return TypeResolver.reify(type instanceof GenericArrayType ? type : TypeResolver.reify(type));
}
```

### Fix: 
```java
public static Type getGenericType(Type type) {
    if (isPublisher(type) || isMessage(type)) {
	    type = getImmediateGenericType(type, 0);
    }
  
   return TypeResolver.reify(type instanceof GenericArrayType ? type : TypeResolver.reify(type));
}
```

**Sample/PR**
PR with fix and updated tests.
https://github.com/spring-cloud/spring-cloud-function/pull/624

**Comment by olegz** [comment]
Resolved with 9bbb86be2d10a99d1545b9cab86298c3722a36cc and d9a0add8b8fa823d175f6508e8be3bd240eb202d
