### ISSUE TITLE
Add support for kotlin coroutines

### ISSUE THREAD

**Issue by apoupardsmartb** [spring-cloud/spring-cloud-function#634]
It would be great to be able to declare suspend function like:

```
@Bean
suspend fun uppercase(value: String): String {
	return value.toUpperCase()
}
```

**Comment by olegz** [comment]
Please feel free to contribute

**Comment by apoupardsmartb** [comment]
I have done an adapter in on one of my project but it's the good way to integrate it in spring-cloud-function.
To find the best way to do it, I should probably start by looking at how coroutine was integrated in spring boot webflux.

Do you know where coroutine's integration is done in spring boot webflux?

**Comment by olegz** [comment]
I do not, but perhaps @sdeleuze can point you in the right direction.

**Comment by sdeleuze** [comment]
@olegz You could maybe try to leverage [`CoroutinesUtils#invokeSuspendingFunction`](https://github.com/spring-projects/spring-framework/blob/master/spring-core/kotlin-coroutines/src/main/kotlin/org/springframework/core/CoroutinesUtils.kt#L61).

**Comment by apoupardsmartb** [comment]
HI @olegz, I have started working on this feature: [WIP Pull request on my repo](https://github.com/apoupard/spring-cloud-function/pulls)

I have start by implementing the possibility to declare suspend function as `suspend (String) -> String`. 
I map it as (Function<Flux<*>, Flux<*>>) and call it for for each item of the `Flux`

But as with Flux, we can only use `Function<Flux<*>, Flux<*>>`, should I do the same with suspend function and only implement the mapping for `suspend (Flow<String>) -> Flow<String>` ?

**Comment by olegz** [comment]
I believe this has been [addressed](https://github.com/spring-cloud/spring-cloud-function/pull/655)

**Comment by tarjanik** [comment]
Could you provide a working example with the new version, that is a suspended consumer? I couldn't get it working, and the documentation only mentiones non suspended examples. Thanks

**Comment by apoupard** [comment]
Hi @tarjanik,

I told @olegz I would work on the documentation, but I didn't took the time to do. 
I will try to work on i it this weekend.

**Comment by tarjanik** [comment]
Hi @apoupard 

Thanks. One more question: is it supposed to work with Rabbitmq messaging, or only for controllers?
