### ISSUE TITLE
Strategy for Stream Listener Function Mapping

### ISSUE THREAD

**Issue by markfisher** [spring-cloud/spring-cloud-function#65]

**Comment by dsyer** [comment]
There kind of is a strategy (since 1.0.0.M1 probably) to do with headers. Messages are passed to a function that equals the `stream_routekey` if it exists. Not sure if that was what you meant.

**Comment by olegz** [comment]
I think with [SCSt 2.0.0.M1](https://spring.io/blog/2018/08/28/spring-cloud-stream-fishtown-m2-2-1-0-m2-release-announcement) we no longer need it, but please reopen it if I've missed something.
