### ISSUE TITLE
Grammatical mistake in the file spring-cloud-function.adoc

### ISSUE THREAD

**Issue by KSVarun** [spring-cloud/spring-cloud-function#657]
**Describe the bug**
Grammatical mistake in the *Note* section of **Message Headers**

This is the current statement
>SpEL evaluation context’s root object is the actual input argument, so in he case of Message<?> you can construct expression that has access to both payload and headers (e.g., spring.cloud.function.routing-expression=headers.function_name).

This is the corrected one
>SpEL evaluation context’s root object is the actual input argument, so in the case of Message<?> you can construct expression that has access to both payload and headers (e.g., spring.cloud.function.routing-expression=headers.function_name).

```diff
-so in he case...
+so in the case...
```

**Comment by KSVarun** [comment]
A pull request #658 has been created, please approve.

**Comment by olegz** [comment]
For the future if you intend to submit the PR for a non-existing issue, you can just submit it, no need to open a separate issue
