### ISSUE TITLE
Map incoming header to more refined customer header

### ISSUE THREAD

**Issue by Mrc0113** [spring-cloud/spring-cloud-function#676]
It would be nice if the Cloud Stream framework would provide a way to map incoming headers to a more refined custom header. I'd imagine this would probably use a combination of SPEL and existing header enricher capabilities in Spring Integration? And it would be ideal if this could take place completely via configuration (if possible) to prevent the developer from having messaging specific code. 

This would enable developers to do many things, but one example would be to extract parts of a destination as separate header variables as requested in a Solace Binder enhancement here: https://github.com/SolaceProducts/solace-spring-cloud/pull/45. It would be great if this functionality could be achieved at the framework level so everyone can benefit from it. Note that this would also assist with folks discovering Spring Cloud Stream via AsyncAPI since it has the concept (like OpenAPI) of variables that can exist in channels. 

FYI @olegz this is one of the enhancements we discussed earlier.

**Comment by olegz** [comment]
Actually it's even simpler then I thought (still needs to be documented), but here is the short of it. You can achieve it via simple function composition.

```java
@Bean
public Function<Message<?>, Message<?>> enrich() {
    return message -> MessageBuilder.fromMessage(message).setHeader("foo", "bar").build();
}

@Bean
public Function<Message<?>, Message<?>> myBusinessFunction() {
    // do whatever
}
```
Your _spring.cloud.function.definition_ will be `spring.cloud.function.definition=enrich|myBusinessFunction`

Here is the complete app that you can cut/paste

```java
@SpringBootApplication
public class DemoStreamApplication {

	public static void main(String[] args) {
		SpringApplication.run(DemoStreamApplication.class,
				"--spring.cloud.function.definition=enrich|echo",
				"--spring.cloud.stream.function.bindings.enrich|echo-in-0=myInput",
				"--spring.cloud.stream.bindings.myInput.destination=myDestination",
				"--spring.cloud.stream.bindings.myInput.group=myGroup");

	}

	@Bean
	public Function<Message<String>, Message<String>> enrich() {
		return message -> {
			Assert.isTrue(!message.getHeaders().containsKey("foo"), "Should NOT contain 'foo' header");
			return MessageBuilder.fromMessage(message).setHeader("foo", "bar").build();
		};
	}

	@Bean
	public Function<Message<String>, Message<String>> echo() {
		return message -> {
			Assert.isTrue(message.getHeaders().containsKey("foo"), "Should contain 'foo' header");
			System.out.println("Incoming message " + message);
			return message;
		};
	}
}
```

Note how I am simplifying the composed function name with `spring.cloud.stream.function.bindings.enrich|echo-in-0=myInput`, so now you can refer to the input binding as `myInput` and use it with other standard stream properties (as shown in the example)

Anyway, i'll document it in both stream and function before closing it

**Comment by Mrc0113** [comment]
@olegz, I agree this is one approach to doing it and would work as a generic way to enrich a message. But do you think we can come up with something that exposes this via configuration? Maybe using SPEL and a generic impl of something like the `headerMapperBeanName` that Gary mentioned above? 

I'm trying to get closer to the proposal made [here](https://github.com/SolaceProducts/solace-spring-cloud/pull/45) where just via a few simple config changes in the yaml/json the developer/devops team can create new headers without having to write code if possible. (Note the IMPL of that specific use case is basically take the `destination` header on a Solace message and extract the topic levels specified between the angle brackets as variables)  

In general adding this functionality via configuration would also allow for function re-use without needing to re-compile at deployment time. For example, a developer wrote a function bean to handle a REST request expecting header "foo" and an "order" POJO payload and now at some time later I, who may be on the devops team, want to re-use that function bean and expose it via Rabbit/Kafka/Solace...I have a message coming in that includes the proper "order" POJO and just need to create the "foo" header who's value is in a different header of the message already. If I can do that via config then I don't need to modify any code.

**Comment by olegz** [comment]
Marc, I just pushed initial support for it. It is not yet documented (i'll follow up), but wanted to give it to you as quick as possible to try.
Here is an example (it also uses composed function for added complexity)
```
@SpringBootApplication
public class DemoStreamApplication {

	public static void main(String[] args) {
		SpringApplication.run(DemoStreamApplication.class,
				"--spring.cloud.stream.function.autodetect=false",
				"--spring.cloud.function.definition=echo|foo",
//				"--spring.cloud.function.configuration.echo.input-header-mapping-expression[0].key1=hello",
//				"--spring.cloud.function.configuration.echo.input-header-mapping-expression[0].key2=blahblah",
				"--spring.cloud.function.configuration.echo|foo.input-header-mapping-expression.key1=headers.key3",
				"--spring.cloud.function.configuration.echo|foo.input-header-mapping-expression.key2='blahblah'"
				);
	}

	@Bean
	public Function<String, String> echo() {
		return p -> p;
	}

	@Bean
	public Function<String, String> foo() {
		return p -> p;
	}
}
```

Note how I commented `input-header-mapping-expression[0].key2`. Basically if you're only dealing with conventional function, indexing input with 0 is optional.

Anyway, give i a shot and let me know

**Comment by Mrc0113** [comment]
Hey @olegz, 

Sorry for the delay but I finally got a chance to try this out and I can't seem to get it working. 
I pulled the latest on the `main` branch in this project, did a `mvn install` locally and added the below to my pom
```
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-function-context</artifactId>
			<version>3.1.3-SNAPSHOT</version>
		</dependency>
```

Do I need to do something else to get it to work? 

I'm using the traditional uppercase function below and when I add 
`spring.cloud.function.configuration.uppercase.input-header-mapping-expression.foo=contentType` to my `application.properties` file the `foo` header is empty even though the `contentType` header isn't. 

```
	@Bean
	public Function<Message<String>, String> uppercase(){
	   return v -> {
	      System.out.println("Uppercasing: " + v.getPayload());
	      System.out.println("Headers: " + v.getHeaders());
	      System.out.println("foo: " + v.getHeaders().get("foo"));
	      return v.getPayload().toUpperCase();
	   };
	}
```

Output: 
```
Uppercasing: Hello world!
Headers: {solace_senderTimestamp=1621370220410, solace_expiration=0, deliveryAttempt=1, solace_destination=uppercase-in-0, solace_timeToLive=0, solace_receiveTimestamp=0, target-protocol=kafka, acknowledgmentCallback=com.solace.spring.cloud.stream.binder.util.JCSMPAcknowledgementCallbackFactory$JCSMPAcknowledgementCallback@622016f1, solace_discardIndication=false, solace_dmqEligible=false, solace_priority=-1, solace_redelivered=false, id=4e1963cb-8fc5-d401-020a-fd8704210a49, contentType=application/json, solace_senderId=Try-Me-Pub/solclientjs/chrome-90.0.4430-OSX-10.15.7/2008818482/0002, timestamp=1621370220449}
foo: null
```

thanks!

**Comment by olegz** [comment]
@Mrc0113 I think you may have felt a victim to my bad example. Your SpEL expression is wrong. It should be `spring.cloud.function.configuration.uppercase.input-header-mapping-expression.foo=headers.contentType`.

I am updating tests as we speak, but wanted to give you update ASAP so  you can try

**Comment by olegz** [comment]
Also, @Mrc0113 I just noticed a nasty bug. I guess I was concentrating so much on getting a composed functions work I forgot to include instrumentation for non-composed functions.
Fixing it as we speak

**Comment by GreenRover** [comment]
Would this allow something like this:
spring.cloud.function.configuration.echo.input-header-mapping-expression.key2=header.destination.split(“/“)[4]

**Comment by olegz** [comment]
Yes, Marc and I talked about it. May not be the most efficient way, but that is a whole other story. .  wok in progress. 
Anyway, the above should work, i may even add it to one of the tests.

**Comment by Mrc0113** [comment]
Awesome stuff @olegz! 

I pulled the latest and took it for a spin. It looks to be working for me. I can successfully map headers to other headers. 

A few pieces of feedback:  
1. What should be the default if you are trying to access a header that doesn't exist? or splitting a header on "/" like I do below and accessing an index that doesn't exist? Should it fail (like it does now) or default to a value of null for that header and maybe log a warning? I think we discussed this on one of our calls but I don't remember the outcome. I could see some headers potentially being optional so it might be nice for it not to fail. Thoughts? 
2. Spring Tool Suite doesn't like the index on the end of the `input-header-mapping-expression`. It says you can't use [...] navigation for that property. 
3. Also related to the index, I noticed if I include the index on the first input-header-mapping-expression, but not subsequent ones then the subsequent headers are null, however if I only use the index on the second input-header-mapping-expression then I just get an error when a message is received. It feels a bit inconsistent there. Are you wanting to say you either specify the index on ALL input-header-mapping-expressions or on none? or can I use it on some and not others?  
4. I just wanted to note that it allows me to overwrite an existing header. I think this is fine but wanted to make sure it was an intentional decision. 

FYI, @GreenRover I successfully tested this topic hierarchy & config out which maps different levels of a topic to other headers. Your use case is definitely top of mind and please feel free to provide feedback here as well :) 

![image](https://user-images.githubusercontent.com/1815312/118882376-22168700-b8c2-11eb-815a-2eeb3ca20425.png)
 
```
spring.cloud.function.configuration.uppercase.input-header-mapping-expression.company=headers.solace_destination.getName.split("/")[0]
spring.cloud.function.configuration.uppercase.input-header-mapping-expression.department=headers.solace_destination.getName.split("/")[1]
spring.cloud.function.configuration.uppercase.input-header-mapping-expression.system=headers.solace_destination.getName.split("/")[2]
spring.cloud.function.configuration.uppercase.input-header-mapping-expression.version=headers.solace_destination.getName.split("/")[3]
spring.cloud.function.configuration.uppercase.input-header-mapping-expression.type=headers.solace_destination.getName.split("/")[4]
spring.cloud.function.configuration.uppercase.input-header-mapping-expression.object=headers.solace_destination.getName.split("/")[5]
```

The message had this for headers once it hit the code (You can see the newly mapped headers show up): 
Headers: {solace_senderTimestamp=1621457407602, solace_expiration=0, deliveryAttempt=1, solace_destination=acme/mfg/masterData/v1/change/o-ring, **type=change**, solace_timeToLive=0, **version=v1**, solace_receiveTimestamp=0, target-protocol=kafka, acknowledgmentCallback=com.solace.spring.cloud.stream.binder.util.JCSMPAcknowledgementCallbackFactory$JCSMPAcknowledgementCallback@387cea97, **system=masterData**, solace_discardIndication=false, solace_dmqEligible=false, solace_priority=-1, solace_redelivered=false, **company=acme**, id=93aac5dd-b87a-6333-d5e1-a89cd0542db7, **department=mfg**, contentType=application/json, solace_senderId=Try-Me-Pub/solclientjs/chrome-90.0.4430-OSX-10.15.7/2313035759/0002, **object=o-ring**, timestamp=1621457407659}

**Comment by olegz** [comment]
@Mrc0113 
1. I am struggling myself with the first point, so here are my thoughts. I do not believe it should fail for one simple reason - you really can't control the state of messages coming in, so failing the entire stream just because you had a message which was not fully compatible with your expectations is not a good idea especially given the fact that you can always introduce some filtering function (via composition) that would check for things and would fail explicitly (if that is what you want). So in other words I am advocating for _WARN-AND-CONTINUE_ approach. Thoughts?
2. I am assuming you mean at the end of the value of the property (`headers.solace_destination.getName.split("/")[0]`) right? If so, it is outside of my control since you are providing a valid SpEL expression.
3. Not quite sure what you're saying, perhaps you can provide an example. Also, I just added another test for split so perhaps you can look at it and suggest how to modify it to force this error that you're describing.
4. Yes, it is fine and fits the pattern of header enrichment which implies any modifications (including removal) to Message headers.

**Comment by GreenRover** [comment]
@olegz 
1.) I am with you. Warn and continue seams for also to be the correct solution.

@Mrc0113 
Thanks for the example helps me to understand ho it should work

**Comment by Mrc0113** [comment]
> @Mrc0113
> 
> 1. I am struggling myself with the first point, so here are my thoughts. I do not believe it should fail for one simple reason - you really can't control the state of messages coming in, so failing the entire stream just because you had a message which was not fully compatible with your expectations is not a good idea especially given the fact that you can always introduce some filtering function (via composition) that would check for things and would fail explicitly (if that is what you want). So in other words I am advocating for _WARN-AND-CONTINUE_ approach. Thoughts?
> 2. I am assuming you mean at the end of the value of the property (`headers.solace_destination.getName.split("/")[0]`) right? If so, it is outside of my control since you are providing a valid SpEL expression.
> 3. Not quite sure what you're saying, perhaps you can provide an example. Also, I just added another test for split so perhaps you can look at it and suggest how to modify it to force this error that you're describing.
> 4. Yes, it is fine and fits the pattern of header enrichment which implies any modifications (including removal) to Message headers.

1.  I also agree with the warn & continue approach for the reasons that you stated. 👍
2. I'm actually referring to the index to the left of the '='. See screenshot. Note that it still works, just STS doesn't seem to like it. 
![image](https://user-images.githubusercontent.com/1815312/118985365-62224c00-b94c-11eb-8cb4-2a83f9f5cfe2.png)
![image](https://user-images.githubusercontent.com/1815312/118985930-e379de80-b94c-11eb-8d6c-3ae93aa750a8.png)

3. I created a quick recording to show what I'm talking about, you can download it here: https://tmpfiles.org/37473/screenrecording2021-05-20at09.24.38.mov

**Comment by olegz** [comment]
@Mrc0113 @GreenRover 
Did as discussed and added a failure test to ensure it logs and continues.

Can you please give it one more shot to validate as we are few days away from the release.

Thank you for your patience

**Comment by Mrc0113** [comment]
thanks @olegz! 

Just a heads up that I'll try to kick the tires on it some tomorrow afternoon

**Comment by Mrc0113** [comment]
Hey @olegz, looks good. 

The mapping works for me and I now see the `WARN` log message instead of an error as discussed above. 

I do however still see the issue I described in my previous post, did the video make sense to you and you're okay with that or did you need more info from me? 
> 3\. I created a quick recording to show what I'm talking about, you can download it here: https://youtu.be/rhZtloy7gJU

**Comment by olegz** [comment]
@Mrc0113 sorry, almost missed your video but managed to fix it before kicking off a release - https://github.com/spring-cloud/spring-cloud-function/commit/db6e8ce7b41309aab85c7d86b1af3258ac4603ba

**Comment by Mrc0113** [comment]
Excellent, thanks @olegz 👏
