### ISSUE TITLE
FunctionAroundWrapper is not being called on the producer side

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-function#681]

**Comment by olegz** [comment]
I added a test with https://github.com/spring-cloud/spring-cloud-function/commit/4837efdcca1c35b1cc7fb57db387307ca3608eec so all is working.
Your issue was with sending a POJO instead of a Message, so I also fixed the StreamBridge to ensure that POJOs are wrapped in Message
