### ISSUE TITLE
Missing POM file in Spring Artifactory

### ISSUE THREAD

**Issue by tiegz** [spring-cloud/spring-cloud-function#682]
**Describe the bug**

Hi, I just noticed that the "libs-release-local" Artifactory repo for Spring doesn't include the POM files for the "spring-cloud-function-docs" artifact (even though the ".pom.asc" file is there). 

Was just curious if that's intentional, or a possible bug? TIA.

**Sample**

https://repo.spring.io/webapp/#/artifacts/browse/tree/General/libs-release-local/org/springframework/cloud/spring-cloud-function-docs/3.1.2

**Comment by olegz** [comment]
I see two files `spring-cloud-function-docs-3.1.2.pom.asc` and `spring-cloud-function-docs-3.1.2.zip`. Are yu expecting something else?

**Comment by tiegz** [comment]
Mostly wondering why there'd be a signature file for a pom (".pom.asc") if there's no pom.

**Comment by olegz** [comment]
I guess I don't have a clear answer as it may be a side-effect of some parent configuration (e.g., spring-cloud). 
It is harmless after, so I'll close this PR with no action taken.
If you feel like you can contribute with the fix, feel free to submit a PR.
