### ISSUE TITLE
AWS Function Adapter doesn't support the API Gateway v2 event

### ISSUE THREAD

**Issue by peterjot** [spring-cloud/spring-cloud-function#684]
**Describe the bug**
Currently, `org/springframework/cloud/function/adapter/aws/FunctionInvoker.java` doesn't handle correctly AWS API Gateway v2 events and the body of the event is not parsed before being passed to the function

The problem is the `requestMap.containsKey("httpMethod")` condition in `AWSLambdaUtils::generateMessage`. The `httpMethod` field has been removed from the root level of the event in the new version of the event.

**Sample**
Create a new test case for FunctionInvoker with an API Gateway v2 event
Example event: https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html

**Comment by olegz** [comment]
Understood. Seems to be an easy enough enhancement, especially since there is a `version` filed.

Quick question though. Does it also require upgrade AWS libraries? - https://github.com/spring-cloud/spring-cloud-function/issues/641

**Comment by peterjot** [comment]
Yes, unfortunately, it requires an upgrade of the `aws-lambda-java-events` library.

We need to handle these classes
APIGatewayV2HTTPEvent: https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayV2HTTPEvent.java
APIGatewayV2HTTPResponse: https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayV2HTTPResponse.java

**Comment by olegz** [comment]
NOTE: The fix will be available in the next version of 3.1 as ell as 3.1.
Basically with 3.1.x all you need is to override lambda-event dependencies in your POM (e.g., version 3.9.0) that support v2.

With 3.2 version of s-c-function it will just work but GA release will not be available for a while.
