### ISSUE TITLE
Merge s-c-function-kotlin module to s-c-function-context to make sure Kotlin integration story is consistent with other Spring projects

### ISSUE THREAD

**Issue by olegz** [spring-cloud/spring-cloud-function#685]
Kotlin support comes from Spring Core and a typical (non-s-c-function) user would only have to bring Kotlin libraries to enable such integration. 
In s-c-function however, the user would also need to bring s-c-function-kotlin module which is inconsistent with the rest of Kotlin integration in Spring.

**Comment by sdeleuze** [comment]
Awesome, thanks a lot for working on that.
