### ISSUE TITLE
Unable to get messageId and publishTime of PubSubMessage in Google Cloud Function

### ISSUE THREAD

**Issue by kmmanu** [spring-cloud/spring-cloud-function#695]
I am trying to follow the [Spring Cloud Function GCP adapter example](https://github.com/spring-cloud/spring-cloud-function/tree/master/spring-cloud-function-samples/function-sample-gcp-background/) to receive [Pub/Sub message](https://github.com/spring-cloud/spring-cloud-function/blob/master/spring-cloud-function-samples/function-sample-gcp-background/src/main/java/com/example/PubSubMessage.java)  in Google Cloud Function.  While getting the message payload from the `data` field and the message attributes from 'attributes' field, the values of `messageId` and `publishTime` are coming as `null`.

Version of `spring-cloud-function-adapter-gcp` used is 3.1.2

**Comment by olegz** [comment]
@meltsufin can you please take a look at this?

**Comment by meltsufin** [comment]
@kmmanu I'm able to repro this issue. I think the reason that this is happening is because the event is somehow being processed through `HttpFunction` codepath rather than through `RawBackgroundFunction`. Our `GcfJarLauncher` implements both interfaces, and we would expect `accept(String json, Context context)` to be called rather than `service(HttpRequest httpRequest, HttpResponse httpResponse)`, but that doesn't seem to be happening.

@dzou Can you please look into this more?

**Comment by dzou** [comment]
Sure I will take a look.

**Comment by dzou** [comment]
So it looks like the GCF function receives this as a payload from Pub/Sub: `{"@type":"type.googleapis.com/google.pubsub.v1.PubsubMessage","data":"SGVsbG8gd29ybGQgZWVlZQ\u003d\u003d"}`. There doesn't seem to be any info about timestamp/id.

On the other hand, I found that the `Context` object contains this info. You'll have to change your function to accept `Message` and access the [`Context` that we set here](https://github.com/spring-cloud/spring-cloud-function/blob/main/spring-cloud-function-adapters/spring-cloud-function-adapter-gcp/src/main/java/org/springframework/cloud/function/adapter/gcp/GcfJarLauncher.java#L59). 

Something like this:

```
	@Bean
	public Consumer<Message<PubSubMessage>> pubSubFunction() {
		return message -> {
			// The PubSubMessage data field arrives as a base-64 encoded string and must be decoded.
			// See: https://cloud.google.com/functions/docs/calling/pubsub#event_structure

			PubSubMessage payload = message.getPayload();
			String decodedMessage = new String(
					Base64.getDecoder().decode(message.getPayload().getData()), StandardCharsets.UTF_8);
			System.out.println("Hello!!! Received Pub/Sub message with data: " + decodedMessage);

                        // Print out timestamp and event id
			Context ctx = message.getHeaders().get("gcf_context", Context.class);
			System.out.println(ctx.eventId());
			System.out.println(ctx.timestamp());
		};
	}
```

What is puzzling is that the GCF framework seems to indicate it should be possible to [accept timestamp, attributes, etc. in your Pub/Sub pojo](https://github.com/GoogleCloudPlatform/functions-framework-java#writing-a-typed-background-function). I wonder if something broke/changed underneath.

**Comment by kmmanu** [comment]
Thanks @dzou 
The above code is working and I will use the Message header to get the message-Id and even-time as you suggested.
