### ISSUE TITLE
Could not transfer artifact org.springframework.cloud:spring-cloud-function-adapter-openwhisk:pom:3.1.2

### ISSUE THREAD

**Issue by patpatpat123** [spring-cloud/spring-cloud-function#696]
Hello Spring Cloud Team,

Many thanks for this great project, hope you are safe and sound.
I would like to report the following issue:

```
Could not transfer artifact org.springframework.cloud:spring-cloud-function-adapter-openwhisk:pom:3.1.2 from/to rsocket-snapshots (https://oss.jfrog.org/oss-snapshot-local): Transfer failed for https://oss.jfrog.org/oss-snapshot-local/org/springframework/cloud/spring-cloud-function-adapter-openwhisk/3.1.2/spring-cloud-function-adapter-openwhisk-3.1.2.pom 409
```

This is 100% reproducible on a very basic ```mvn clean site```

I am currently using Spring boot 2.5.0-M3, with latest Ilford.

Could you please help fix this http 409 please?

Thank you

**Comment by olegz** [comment]
Since 3.x, we are no longer supporting openwisk as there was no interest in it. This may be the first ever issue or question about it.
That said we're open to collaborating and resurrecting this component if there is interest and contribution from the community.

**Comment by copbint** [comment]
So maybe we should remove it from dependencies?
https://github.com/spring-cloud/spring-cloud-function/blob/main/spring-cloud-function-dependencies/pom.xml#L65

**Comment by patpatpat123** [comment]
Hello Team,

Just bumping this up.

I am now facing this from the latest SpringBoot 2.6.7 + Jubilee 2021.0.2 (both released very recently)

```
Could not find artifact org.springframework.cloud:spring-cloud-function-adapter-openwhisk:pom:3.2.4 in spring-milestones (https://repo.spring.io/milestone)

```

It seems from something that is "no longer supported", which is perfectly fine, this things keep being bumped up.

Is there a way we could remove it entirely as suggested?

Thank you
