### ISSUE TITLE
Spring cloud function with multiple event functions are not working properly 

### ISSUE THREAD

**Issue by jaganm2018** [spring-cloud/spring-cloud-function#697]
Hi,
Recently started working on spring cloud function with aws lambda. I saw lot examples on sigle function worh lambda. But I wants to implement with multiple function in single aws lambda. After gone through the document, I started looking routerFunction. Facing couple of issues and no proper document in YouTube , google...

My test case scenario: 
I have 2 lambda functions<String, String> : even and odd.

in my local, I ran application and run below post method URL
Http://localhost:8080/even 
Http://localhost:8080/odd
 are working fine and getting proper response..

I ran with below url 
http://localhost:8080/functionRouter
Header: spring.cloud.function.defenation:even

first time I’m getting response if I ran second time again - getting publisher can’t use spring.cloud.function.defenation as a arugument. Should be specified in the application.properties.

if I restart my application, it will work first time then it won’t work. Getting above error. 

Can you please help me on this how to approach it?. 

Is there anyway to setup spring.cloud.header.defenation dynamically to read from header?. 

Please suggest me.. it will great help to me.

**Comment by olegz** [comment]
Can you please post a stack trace? Log snippet?

**Comment by jaganm2018** [comment]
sorry for confuse you.. Please see below log trace is coming like this 
Java.Lang.illegalArgumentException: Routing input of type publisher is not supported per individual values (e.g., message header or POJO). Instead you should use ‘spring.cloud.function.defenation’ or spring.cloud.function.routing-expression’ as applicationproperties.


Application.properties:
Spring.cloud.stream.function.routing.enabled=true
Spring.cloud.function.scan.packages: com.example.demo.functions

let me know if you need any more information.

**Comment by jaganm2018** [comment]
Can you please provide any sample application which is Java spring cloud function handling multiple functions and deploy into AWS lambda?. I was looking for examples but not found any where.

**Comment by jaganm2018** [comment]
Issue resolved after upgrade to spring cloud aws version to 3.1.0 above and spring cloud version is 2020.0.2 version.
