### ISSUE TITLE
Spring cloud vault is not working in aws lambda

### ISSUE THREAD

**Issue by jaganm2018** [spring-cloud/spring-cloud-function#703]
Issue: spring cloud vault is not working in aws lambda with IAM role.
Versions:
Spring boot: 2.4.5
Spring cloud: 2020.0.2
Spring vault aws: 3.0.2

Scenario-1: Normal Java code wise , I’m able to read secretes from vault.

scenario-2: as per the document 3.0.2 spring vault ..
Passing IAM role and aws-path. Authentication and endpoint point URL and server-name.
Deployed into AWS lambda and no build error. But not fetch secrets from vault.

scenario-2: wrongly provided IAM role but even though it ran successfully and not fetch secrets from vault. 

Note: if I specified in bootstrap.yml , it’s not working and throwing vault.token is required.
If I specified in application yml then it’s working but don’t know whether it’s connected to vault successfully or not and not fetching secrets from vault.

can you please help me with any sample? Posted in spring-vault but not one are not responding.

please help me on this with sample in aws.

thanks in advance.

**Comment by olegz** [comment]
What does this have to do with spring-cloud-function?

**Comment by jaganm2018** [comment]
Sorry it's not from spring-cloud-function side. No one are  responding from spring-cloud-vault side.  Can you please provide any help from your side.

**Comment by olegz** [comment]
I am not sure what kind of help you expect for an issue that is  completely unrelated to this project.

I am closing this issue as invalid
