### ISSUE TITLE
Function route is not working from apiGateway after upgrade to spring-cloud-function-adapater-aws: 3.1.3 

### ISSUE THREAD

**Issue by jaganm2018** [spring-cloud/spring-cloud-function#704]
Hi,

earlier I raised one bug :698 and closed. Now updated version as per that and please below spring versions 
1. Spring-boot : 2.5.0
2. Spring-cloud-function-adapater-aws : 3.1.3
3. Aws-lambda-Events: 3.1.0
4. Spring-cloud-function : 3.1.2

please see below test scenarios..
1. Build the application what you provided git repo: https://github.com/spring-cloud/spring-cloud-function/tree/main/spring-cloud-function-samples/function-sample-aws-routing
2. It’s working locally with multi function and same it’s working in lambda with configuration-> environment: spring_cloud_function_definition: upperCase
3. Now I created apiGateway with RestApi type and created resource and method. Passed the http header value as spring _cloud_finction_definition: upperCase. 

Case: 3a
Include step-2 environment variable, it’s working fine.
Case : 3b
note: removed step-2 environment variable
Ran the test case and got below error : errorMessage: failed to lookup function null.

Case:3c
Note: removed step-2 environment variable and change the spring_cloud_function_definition to spring.cloud.function.definition: {function name}

4. In step-3 and added integration proxy and tested .. got same exception as case 3b. 

can you please let me know when I’m doing mistake and spring_cloud_passing function_definition variable is right or wrong? 

thanks in advance.

**Comment by olegz** [comment]
Why is your s-c-function version 3.1.2?
The fix was in 3.1.3 and there is a new [AWS routing example](https://github.com/spring-cloud/spring-cloud-function/tree/main/spring-cloud-function-samples/function-sample-aws-routing) and new [documentation](https://docs.spring.io/spring-cloud-function/docs/3.1.3/reference/html/aws.html#_aws_function_routing) explaining steps, please follow it

**Comment by jaganm2018** [comment]
Got it. I thought upgrade spring-cloud-function-adapater-aws only. Let me check and will let you know .. thanks for quick response.

**Comment by jaganm2018** [comment]
Now it’s working .. really really thanks a lot and quick response from you.  Facing issues with cloud config server and vault. They are not responding at all. Can you please suggest me to whom I need to reach out if possible from your side.

**Comment by olegz** [comment]
I'll pass along, meanwhile I'll close this issue as there is nothing to do

**Comment by jaganm2018** [comment]
Thanks and waiting for below stuff..
1. Spring aws vault integration 
2. Spring config server with aws s3.

really it will be more helpful to me. Thanks a lot.
