### ISSUE TITLE
Look for functions in well known places

### ISSUE THREAD

**Issue by sbawaska** [spring-cloud/spring-cloud-function#714]
**Is your feature request related to a problem? Please describe.**
When using the the spring-cloud-function-deployer, I used the `spring.cloud.function.location` property to point to my simple jar. The jar seems to be successfully deployed, but the function in the jar is not detected unless `spring.cloud.function.function-class` is also provided. For simple jars, we would like not to place additional responsibility on the user to specify an entry in the manifest for the function class.

**Describe the solution you'd like**
If the user puts their function i.e class implementing Function, Supplier, Consumer in a well known package (for example `functions`) then those functions will be detected and registered automatically. If the user chooses to put the function in a different package, they will have to specify `function-class`.

**Comment by spencergibb** [comment]
maybe something in META-INF/spring.factories? conventions can break, but the thing that is setting `spring.cloud.function.location` wouldn't need to know the function.
