### ISSUE TITLE
Can't return 404 with empty payload using spring-cloud-function-adapter-aws

### ISSUE THREAD

**Issue by foyst** [spring-cloud/spring-cloud-function#716]
**Describe the bug**
When using spring-cloud-function-adapter-aws, in the event of requesting a missing REST resource I’m struggling to understand how to return a 404 status code with an empty payload.

I’ve landed on `Function<APIGatewayProxyRequestEvent, Message<String>>` which allows me to specify a "statusCode" header and an empty string as the body, but I’m wondering if there’s a more idiomatic approach to this in spring-cloud-function that allows me to return an empty body (as opposed to an empty string)?

This is what gets returned:
![image](https://user-images.githubusercontent.com/6427939/126716348-f649abfc-fad9-45d0-9b61-006602f247c1.png)

I’ve tried a few options, such as `Function<APIGatewayProxyRequestEvent, Owner>` and `Function<APIGatewayProxyRequestEvent, Message<Owner>>`. The former doesn’t let you control statusCode and headers that are returned, and the latter doesn’t let you return a Message with a null payload.

Ideally, I’d just like to return a APIGatewayProxyResponseEvent, which I’d have full control of and would bypass all post-function response conversion.

This issue was originally raised in SO - [https://stackoverflow.com/questions/68465552/how-to-handle-a-404-response-with-spring-cloud-function-and-aws](https://stackoverflow.com/questions/68465552/how-to-handle-a-404-response-with-spring-cloud-function-and-aws)

**Sample**
I have my example in GitHub, with the function and a test which reproduces the issue 
[Lambda Config](https://github.com/foyst/spring-petclinic-rest-serverless/blob/1-spring-cloud-function/src/main/java/org/springframework/samples/petclinic/lambda/LambdaConfig.java) 
[Lambda Test](https://github.com/foyst/spring-petclinic-rest-serverless/blob/1-spring-cloud-function/src/test/java/org/springframework/samples/petclinic/lambda/LambdaConfigTests.java)

Thanks, Ben

**Comment by olegz** [comment]
So now you can either throw an exception from the function triggering 417 or you can return APIGatewayV2HTTPResponse or APIGatewayProxyResponseEvent with status code set
