### ISSUE TITLE
Cannot start Boot app with SpringBootConfiguration in lambda

### ISSUE THREAD

**Issue by Pilleo** [spring-cloud/spring-cloud-function#718]
**Describe the bug**
Spring Boot app cannot start in lambda if we use @SpringBootConfiguration instead of @SpringBootApplication. 
Can also be tested with 
`    System.setProperty("MAIN_CLASS", Main.class.getCanonicalName());
    FunctionInvoker functionInvoker = new FunctionInvoker();
    System.clearProperty("MAIN_CLASS");`

Dependencies:
`<dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>

        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-lambda-java-events</artifactId>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-lambda-java-core</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-function-adapter-aws</artifactId>
        </dependency>`

The error itself is 
`org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.cloud.function.context.FunctionCatalog' available`

I was trying to use autoconfiguration classes manually to start spring by passing them into FunctionalSpringApplication constructor, but that did not help. 

Thank you

**Comment by olegz** [comment]
There is not enough information to diagnose the issue. 
You can create a sample project with bare minimum that reproduces the issue OR you can start from pone of the working samples available here https://github.com/spring-cloud/spring-cloud-function/tree/main/spring-cloud-function-samples (we actually have 4)

**Comment by Pilleo** [comment]
[sample with bug](https://github.com/Pilleo/springCloudBug)
Please run tests to see actual bug

**Comment by Pilleo** [comment]
the same issue will appear in actual AWS lambda. Please note that the application itself start just fine, but it does not with aws

**Comment by olegz** [comment]
I see you're using 3.9.0 AWS libraries. We just addressed this issue https://github.com/spring-cloud/spring-cloud-function/commit/3666bf73f707c7969d861e2a2545a3ac93d0c713 and there is no release available yet. But ou can certainly try with snapshots

**Comment by Pilleo** [comment]
How can I get a snapshot?

**Comment by Pilleo** [comment]
Please check repo again. Seems like snapshot does not help at all

**Comment by olegz** [comment]
We just released 3.2.0-M1 which contains the support for 3.9.0 event libraries

**Comment by Pilleo** [comment]
Sorry, same issue

**Comment by olegz** [comment]
Then i need to see your entire app. As i stated before, you can start from a working example I shared earlier and track where it breaks (if it does), otherwise I have nothing to go by to diagnose your issue. Based on the error message it appears you have some misconfiguration. So push your project somewhere to github so we can take a look

**Comment by Pilleo** [comment]
https://github.com/Pilleo/springCloudBug - what is wrong with this one?

**Comment by Pilleo** [comment]
Haha, I get it now. org.springframework.cloud.function.context.config.ContextFunctionCatalogInitializer#initialize did not have a chance to work because flag spring.functional.enabled is being set with the help of FunctionalSpringApplication, and because in lambda main method is not executed, then flag is false and initializer just cannot work

**Comment by Pilleo** [comment]
Well, it is still broken. It just does not work with SpringBootConfiguration annotation. It needs two huge dependencies and more configuration, but then it will also break with org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'origin' defined in org.springframework.cloud.function.web.source.FunctionExporterAutoConfiguration:

You can see it for yourself  here https://github.com/Pilleo/springCloudBug 
I would love to use some of your examples, But there are no with functional configuration for aws. 
Please notice that I am talking about about running SpringBootConfiguration  with the help of org.springframework.cloud.function.adapter.aws.FunctionInvoker. Without FunctionInvoker it works just fine

**Comment by olegz** [comment]
Large part of your issue is your POM was missing quite a few entries to generate proper deployment file, hence me asking you to start with one of the existing samples.
That said, I've made some minor improvements and will push in a min.

**Comment by olegz** [comment]
Also, in your code you have actually configured two functions. I am pushing an isolated example so you'll see the difference.

**Comment by olegz** [comment]
The new snapshots (3.2.0-SNAPSHOT) are available in the repository.
The new sample for functional bean definition is also published - https://github.com/spring-cloud/spring-cloud-function/tree/main/spring-cloud-function-samples/function-functional-sample-aws

Let me now if you still have issues
