### ISSUE TITLE
Incorrect routing when FunctionRegistration used (AWS)

### ISSUE THREAD

**Issue by Pilleo** [spring-cloud/spring-cloud-function#725]
**Describe the bug**
If I use FunctionRegistration for functions, than routing function does not actually route, it is using the first function that it used before. No such problem without using FunctionRegistration  class.  Please see tests for example. 

**Sample**
https://github.com/Pilleo/springCloudBug

**Comment by olegz** [comment]
The issue was that while computing available function names in `getNames()` method we were missing FunctionRegistrations, so after the first lookup it appeared that there is only one function in catalog.

**Comment by olegz** [comment]
I am also adding routing sample with functional bean definitions
