### ISSUE TITLE
Routing by type of AWS message ifor spring-cloud-function-adapter-aws

### ISSUE THREAD

**Issue by Pilleo** [spring-cloud/spring-cloud-function#726]
I would like to have routing by type of AWS  message. In this example https://github.com/Pilleo/springCloudBug I am parsing incoming bytes to determine source of event and pick a suitable function for this. But I can see that Spring is doing the same thing before to log type of incoming message. So, we have:
1 Parsing for logging
2 Parsing for routing
3 Actual parsing needed for a function

That smells bad.  I would love to have more efficient solution without repeated parsing and unneeded code. 
Thank you!

**Comment by olegz** [comment]
Can you be a bit more clear as to what do you mean when you say `...Spring is doing the same thing before to log type...`, perhaps link to code snippet. The same for `... Parsing for routing. . .` and most importantly `...parsing needed for a function...`

**Comment by Pilleo** [comment]
For logging this code is not there anymore - https://github.com/spring-cloud/spring-cloud-function/commit/7f667a1067a89cec0c65d29d38351beeac0c25cc#diff-c3541839d4b70d7bf7b3c116f62949cdab0fd8923e1ccf57a6788e6411d67d87L226-L239
It is in version 3.1.3, so nice job! 

Parsing for routing means that if we have different functions for different sources of events, than we need to parse it inside MessageRoutingCallback into smth like map to see the source, just like in the link above. An we cannot reuse that parsed map or tree.

And 
> parsing needed for a function
means that if out function that is going to work have input type, for example, SQSEvent, than Spring is parsing payload of a message into that type for us. But in my example I know the type even before, after parsing inside of MessageRoutingCallback. Maybe this callback could return a type, not a function name. And spring would iterate through available input types and pick suitable. 
Hope it is more clear now:)

**Comment by olegz** [comment]
So, what you're saying (at least what I understand) is that in order to determine where to route you do some parsing in `MessageRoutingCallback` and in fact can also create the required type since by then you'd know, but you have no way of passing your work downstream which means s-c-function will effectively re-do the process that you have already done

Correct?

**Comment by Pilleo** [comment]
Exactly!

**Comment by olegz** [comment]
Working on it, unfortunately this would require breaking changes to the `MessageRoutingCallback` which is relatively new so I hope it won't cause much of an issue for you, but let me know

**Comment by olegz** [comment]
Actually no, no breaking changes

**Comment by Pilleo** [comment]
Haha, glad to hear that

**Comment by olegz** [comment]
So while there is no breaking change, there is a new method on the `MessageRoutingCallback ` that you would need to use to accomplish what you're looking for.
I've added initial test as part of this commit so you can see how to use it and updated the docs.
Snapshots (3.1 and 3.2) will be available shortly, so please let me know if that works for you.

**Comment by olegz** [comment]
Snapshots are available
