### ISSUE TITLE
Consumer<Mono<SomeClass>> support broken

### ISSUE THREAD

**Issue by Marssmart** [spring-cloud/spring-cloud-function#727]
**Describe the bug**

When using function that uses `implements Supplier<Mono<Someclass>>` and  spring-cloud-function-adapter-azure:3.1.3 i found out that the invocations fail on `NullPointerException`. This is due to a fact that **FunctionInvoker**  when functions uses reactive types tries to retrieve the input type regardless of the fact that its using `Supplier` and there is no input type

The error can be found on line 134 of `FunctionInvoker`
```
...
if (output instanceof Publisher) {
	if (FunctionTypeUtils.isMono(function.getOutputType())) {
		return (O) this.convertOutputIfNecessary(input, Mono.from((Publisher) output).blockOptional().get());
	}
	else {
		List resultList = new ArrayList<>();
		for (Object resultItem : Flux.from((Publisher) output).toIterable()) {
			if (resultItem instanceof Collection) {
				resultList.addAll((Collection) resultItem);
			}
			else {
//the FunctionTypeUtils.getRawType(function.getInputType()) is what causes the NPE
				if (Collection.class.isAssignableFrom(FunctionTypeUtils.getRawType(function.getInputType()))
						&& !Collection.class.isAssignableFrom(FunctionTypeUtils.getRawType(function.getOutputType()))) {
					return (O) this.convertOutputIfNecessary(input, resultItem);
				}
				else {
					resultList.add(resultItem);
				}
			}
		}
		return (O) this.convertOutputIfNecessary(input, resultList);
	}
}
...
```

**Comment by olegz** [comment]
Actually i remember something similar to that vaguely and believe it was fixed. What version of spring-cloud-function are you using?

**Comment by Marssmart** [comment]
@olegz 
![image](https://user-images.githubusercontent.com/12251937/130255549-d663cb0a-3b02-477d-a1b9-3ab8882ff76f.png)

**Comment by Marssmart** [comment]
> Actually i remember something similar to that vaguely and believe it was fixed. What version of spring-cloud-function are you using?

**Comment by Marssmart** [comment]
Closed this one by mistake, versions above

**Comment by bajky** [comment]
Hi, @olegz I just checked your [Commit](https://github.com/spring-cloud/spring-cloud-function/commit/4d9cc9bf75e94169724302a5b84ddbb5843e4cf5) and I have a comment  You added the condition within the method convertOutputIfNecessary, and you trying to check if the input is null. The null check is in conjunction with an instance of check which covers the null check. 
What I want to say is that I'm wondering whether the problem was actually solved because it looks like to be the behaviour was not changed by your last commit.

**Comment by olegz** [comment]
@bajky you're right, I didn't spend to much time looking into it, but i just did and the fix is coming. In it was already working for `Supplier<Mono>`, so as you suggested it may have been fixed as part of some other work, but i found few other issues, so the fix is coming shortly
