### ISSUE TITLE
Make context info available when using GCP

### ISSUE THREAD

**Issue by ZR8C** [spring-cloud/spring-cloud-function#730]
I'd like to be able to access context information when using spring-cloud-function with GCP. When writing pure GCP functions you would implement BackgroundFunction<T> which has the method

`accept(T payload, Context context)`
See https://javadoc.io/static/com.google.cloud.functions/functions-framework-api/1.0.1/com/google/cloud/functions/BackgroundFunction.html

The payload is user defined but Context contains extra information including timestamp which I'm interested in using to determine the age of the event. 

Would it be possible to make this information available? Or is it already available and I just missed it?

**Comment by olegz** [comment]
@meltsufin @elefeint can you please take a look at this and other GCF issues?

**Comment by elefeint** [comment]
Blocked by #642. @ddixit14, FYI for after the upgrade.

**Comment by ddixit14** [comment]
Hi @ZR8C, if you use the generic spring framework message type as the parameter in your background function, you can access the GCF context via the headers. 

@olegz, feel free to close this issue.
