### ISSUE TITLE
Spring Cloud Function with Azure

### ISSUE THREAD

**Issue by decifris** [spring-cloud/spring-cloud-function#734]
**Describe the bug**
Running the [example repo](https://github.com/Azure-Samples/hello-spring-function-azure) with Azure Toolkit for Intellij gives me this error:
`Caused by: java.lang.NullPointerException: Cannot invoke "org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(Object)" because "function" is null`

[Video](https://i.imgur.com/KnAvNfH.mp4)
[Log](https://pastebin.com/W2EbkDV4)

**Comment by olegz** [comment]
While I am willing to take a look, keep in mind that that you are reporting about example which we have no control off since we do not maintain it. Please check our official samples - https://github.com/spring-cloud/spring-cloud-function/tree/main/spring-cloud-function-samples/function-sample-azure

**Comment by olegz** [comment]
I just did a fresh clone of Julien's sample (the repo that you provided), followed instructions in README and everything executed successfully.

I am going to close this issue as there is nothing for us to act on. 
Please communicate whatever issues you may have with the owner of the repository (Julien in this case)
