### ISSUE TITLE
Add support for Filter-type function

### ISSUE THREAD

**Issue by olegz** [spring-cloud/spring-cloud-function#736]
Currently we have `RoutingFunction`

It would be nice to have a filtering function especially when encountering cases like [this](https://stackoverflow.com/questions/68986836/spring-kafka-filtering-kafkanull-values-from-payload)

**Comment by emckissick** [comment]
Would this feature allow a user to create a Function that passes the Message to the next function only if it meets a specific criteria? (https://stackoverflow.com/questions/77801389/skip-filtering-in-spring-cloud-stream-workflow/77802387#77802387).
