### ISSUE TITLE
The Http function with GCP adapter using gradle instead of maven #561

### ISSUE THREAD

**Issue by htactive-nhaptt** [spring-cloud/spring-cloud-function#737]
The sample functions all have examples using Maven but not gradle. I tried to convert the pom.xml into a build.gradle file but was not able to achieve the same result. Could you please help with it?
Have any way to use grade with the Http function with GCP adapter?

**Comment by meltsufin** [comment]
Closely related to #561.

**Comment by olegz** [comment]
I am closing it as the solution has been provided as part of #561
