### ISSUE TITLE
No target folder created inside spring-cloud-function/spring-cloud-function-samples/function-sample after successful build from the root folder

### ISSUE THREAD

**Issue by shuknk8s** [spring-cloud/spring-cloud-function#738]
**Describe the bug**
Please provide details of the problem, including the version of Spring Cloud that you
are using. 
Latest

**Sample**
If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.
1. ./mvnw clean install - build passed without error
2. ls -l spring-cloud-function-samples/function-sample/target 
ls: cannot access 'spring-cloud-function-samples/function-sample/target': No such file or directory
2. java -jar spring-cloud-function-samples/function-sample/target/*.jar
Error: Unable to access jarfile spring-cloud-function-samples/function-sample/target/*.jar

**Comment by olegz** [comment]
I am puzzled as to why would you expect the `.jar` file? This is not how maven/java packaging works. 
JAR files have names which in maven builds matches `<artifactId>-<version>.jar`, so what you should be looking for is `function-sample-2.0.0.RELEASE.jar`

**Comment by shuknk8s** [comment]
Did not generate any jar inside target folder and don't teach me how Maven
works

See the outcome of the ls *.jar command
