### ISSUE TITLE
CloudEvent Result Enrichment only works for Flux or normal Spring Message's but not for Mono

### ISSUE THREAD

**Issue by Richardmbs12** [spring-cloud/spring-cloud-function#746]
**Describe the bug**
I have an easy function

```
@Bean
    public Function<Mono<Person>, Mono<Person>> uppercase() {
        return personMessage -> personMessage.map(person -> {
                person.setFirstName("eh");
                return person;
            }
        );
    }
```

```
@Component
public class ProxyActivatedEventMapper implements CloudEventHeaderEnricher {

	private static final String TYPE = "ProxyActivated";

	@Override
	public CloudEventMessageBuilder<?> enrich(final CloudEventMessageBuilder<?> messageBuilder) {
		return messageBuilder.setType(TYPE).setHeader("detail-type", TYPE);
	}

}
```

Im using the following to invoke:

```
curl --location --request POST 'localhost:8080' \
--header 'Content-Type: application/cloudevents+json' \
--data-raw '{
    "specversion": "1.0",
    "type": "com.sbsa.payments.proxy.core.api.model.Proxy",
    "source": "https://spring.io/",
    "id": "A234-1234-1234",
    "datacontenttype": "application/json",
    "data": {
        "firstName": "jef",
        "lastName": "dun"
    }
}'
```

When I receive the result, Its not in cloudevent format (no http headers for cloudevents).
My CloudEventHeader enricher was also not invoked.

After debugging deeper, I can see the following:

https://github.com/spring-cloud/spring-cloud-function/blob/main/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/context/catalog/SimpleFunctionRegistry.java#L844

SimpleFunctionRegistry.java

                   if (result instanceof Flux && functionInvocationHelper != null) {
				result = ((Flux) result).map(v -> {
					if (firstInputMessage.get() != null && CloudEventMessageUtils.isCloudEvent(firstInputMessage.get())) {
						return functionInvocationHelper.postProcessResult(v, firstInputMessage.get());
					}
					return v;
				});
			}

			return value instanceof OriginalMessageHolder
					? this.enrichInvocationResultIfNecessary(((OriginalMessageHolder) value).getOriginalMessage(), result)
					: result;

There is no result enrichment happening for Mono? Only Flux?

Proposal:

		

		if (result instanceof Mono && functionInvocationHelper != null) {
				result = ((Mono) result).map(v -> {
					if (firstInputMessage.get() != null && CloudEventMessageUtils.isCloudEvent(firstInputMessage.get())) {
						return functionInvocationHelper.postProcessResult(v, firstInputMessage.get());
					}
					return v;
				});
			}

I am not sure if the above would work at all, but just wanted to mention this issue Ive faced if it would bring value to the project, as I believe this issue will cause confusion for future developers using cloudevents and spring cloud function. For now Ive changed from using Mono to using Flux which works as a workaround

**Comment by Richardmbs12** [comment]
Thanks a lot @OlegDokuka ! That was some quick response with a fix.

**Comment by olegz** [comment]
wrong oleg

**Comment by OlegDokuka** [comment]
🤣. I got used to that @olegz 😁. May be it is a sign 😂
