### ISSUE TITLE
Issues with Spring Cloud Function for AWS and Kotlin

### ISSUE THREAD

**Issue by rieckpil** [spring-cloud/spring-cloud-function#747]
**Describe the bug**

I'm having issues getting the setup correct for a Spring Boot Kotlin project using Spring Cloud for AWS Lambda. 

The error is the following (if I don't specify `MAIN_CLASS` as an env variable)

```
Manifest-Version: 1.0
Created-By: Maven Jar Plugin 3.2.0
Build-Jdk-Spec: 11
Implementation-Title: spring-cloud-function-aws-kotlin
Implementation-Version: 1.0.0

Main-Class: org.springframework.boot.loader.wrapper.ThinJarWrapper
Start-Class: de.rieckpil.ApplicationKt
Spring-Boot-Version: 2.5.5
Spring-Boot-Classes: 

java.lang.IllegalStateException: Failed to discover main class. An attempt was made to discover main class as 'MAIN_CLASS' environment variable, system property as well as entry in META-INF/MANIFEST.MF (in that order).

        at org.springframework.cloud.function.utils.FunctionClassUtils.getStartClass(FunctionClassUtils.java:83)
        at org.springframework.cloud.function.utils.FunctionClassUtils.getStartClass(FunctionClassUtils.java:60)
        at org.springframework.cloud.function.adapter.aws.FunctionInvoker.start(FunctionInvoker.java:123)
        at org.springframework.cloud.function.adapter.aws.FunctionInvoker.<init>(FunctionInvoker.java:70)
```

The `MANIFEST.mf` clearly states the `Main-Class` and `Start-Class` and if I'm adding `MAIN_CLASS` as an env variable, the Spring context starts, but fails to gather all beans:

```
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.cloud.function.context.FunctionCatalog' available
```

I already investigated all open & closed issues on GitHub that are somehow related to the `An attempt was made to discover main class as 'MAIN_CLASS' environment variable` issue but none of them helped. 

I'm not sure what's going on and also already tried to run it with `TRACE` as the log level and it says it searches for an empty array for `FunctionClassUtils.getStartClass`:

```
2021-09-23 18:51:19.608 TRACE   --- [           main] o.s.c.function.utils.FunctionClassUtils  : Searching manifests: []

java.lang.IllegalStateException: Failed to discover main class. An attempt was made to discover main class as 'MAIN_CLASS' environment variable, system property as well as entry in META-INF/MANIFEST.MF (in that order).
```

Is there anything that needs to be configured in addition when using a thin JAR layout + Kotlin?

- Java Version: 11
- Spring Boot Version: 2.5.5
- Spring Cloud Version: 2020.0.4

**Sample**

You can find a sample with instructions here: https://github.com/rieckpil/blog-tutorials/tree/master/spring-cloud-function-aws-kotlin

**Comment by olegz** [comment]
This is very strange given that I see in the CloudWatch logs 
```
...
Main-Class: org.springframework.boot.loader.wrapper.ThinJarWrapper
Start-Class: de.rieckpil.ApplicationKt
...
```

Looking

**Comment by rieckpil** [comment]
Yes, that also confused me as from the manifest it looked fine. For plain Java projects, everything works fine 🧐

**Comment by olegz** [comment]
It's a bit more involved. I'll explain later on and will update documentation as well, but I've managed to get to the bottom of it and that is important. I'll push the fix shortly. 
The good thing is that we're dong M2 release today and the fix will make it to M2

**Comment by olegz** [comment]
One thing (unrelated) you would need to add to your POM is 
```
<dependency>
	<groupId>com.amazonaws</groupId>
	<artifactId>aws-lambda-java-events</artifactId>
	<version>3.9.0</version>
</dependency>
```
I'll dig in more as to why it is required when your are not using it, but that is a minor issue compared to what you had,

**Comment by rieckpil** [comment]
Excellent, thank you very much @olegz - do I always need the `aws-lambda-java-events` even though I'm not listening to e.g. a S3 event and only have a cron-based trigger for the Lambda function?

**Comment by olegz** [comment]
So the fix is in and will be part of the M2 release. As I said I'll provide more details and will update documentation and probably create few minor relevant issues, but as I said the main thing is that the big problem is addressed.

One of the minor issues is that currently for Kotlin even if you only have one function you still need to provide `spring_cloud_function_definition` as environment variable pointing to your function.
In your case i took a liberty changing the implementation of function as 
```
@Bean
fun uppercase(): (String) -> String {
   return { it.toUpperCase() }
}
```
So, `spring_cloud_function_definition=uppercase`

I guess if you want to build locally you can try it now, but I've just tested with your app on AWS and all is good

**Comment by olegz** [comment]
> Excellent, thank you very much @olegz - do I always need the `aws-lambda-java-events` even though I'm not listening to e.g. a S3 event and only have a cron-based trigger for the Lambda function?

That is what I meant. In my opinion you do NOT need to have it as a dependency if you're not using it, so it is kind of a bug (harmless but bug nevertheless). I'll fix it as well as the issue with requiring function definition, but that would be after M2

**Comment by rieckpil** [comment]
Okay 👍 I'll give it a shot as soon as M2 is available - I'm looking forward to getting the Kotlin example up-and-running 🚀

**Comment by olegz** [comment]
M2 is now available - https://repo.spring.io/ui/native/milestone/org/springframework/cloud/spring-cloud-function-context/3.2.0-M2

**Comment by rieckpil** [comment]
Excellent! I can confirm that with 3.2.0-M2 it's working for my Kotlin + Spring Boot setup. Thank you very much for the quick fix :) 

![grafik](https://user-images.githubusercontent.com/14176609/135743816-0e0428d0-ab04-450c-a22b-eeaa01c52f03.png)

**Comment by rieckpil** [comment]
One quick question on top (let me know if I should create a separate issue for this).

Do we still need the extensive `maven-shadeplugin` setup as mentioned in the [docs](https://docs.spring.io/spring-cloud-function/docs/3.1.3/reference/html/aws.html#_notes_on_jar_layout)?

```xml
 <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>3.2.4</version>
        <dependencies>
          <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-maven-plugin</artifactId>
            <version>2.5.5</version>
          </dependency>
        </dependencies>
        <configuration>
          <createDependencyReducedPom>false</createDependencyReducedPom>
          <shadedArtifactAttached>true</shadedArtifactAttached>
          <shadedClassifierName>aws</shadedClassifierName>
          <transformers>
            <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
              <resource>META-INF/spring.handlers</resource>
            </transformer>
            <transformer implementation="org.springframework.boot.maven.PropertiesMergingResourceTransformer">
              <resource>META-INF/spring.factories</resource>
            </transformer>
            <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
              <resource>META-INF/spring.schemas</resource>
            </transformer>
          </transformers>
        </configuration>
      </plugin>
```

I tried a stripped version (like in the Spring Cloud AWS samples on GitHub):

```xml
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-shade-plugin</artifactId>
  <version>3.2.4</version>
  <configuration>
    <createDependencyReducedPom>false</createDependencyReducedPom>
    <shadedArtifactAttached>true</shadedArtifactAttached>
    <shadedClassifierName>aws</shadedClassifierName>
  </configuration>
</plugin>
```

and it still works.
