### ISSUE TITLE
Can't send iterable message using Stream Bridge

### ISSUE THREAD

**Issue by xcejp03** [spring-cloud/spring-cloud-function#748]
I have a problem with stream bridge in last version of spring cloud 2020.0.4. If I try to send something iterable (json array) than I get this error:
`java.lang.ClassCastException: class reactor.core.publisher.FluxPeekFuseable cannot be cast to class org.springframework.messaging.Message (reactor.core.publisher.FluxPeekFuseable and org.springframework.messaging.Message are in unnamed module of loader 'app')
`

It is because when message is iterable than it is wrapped in Flux in `SimpleFunctionRegistry.java` and stream bridge is expecting `Message<byte[]>` so it fails.
Spring cloud 2020.3 is ok

libraries versions:
spring boot - 2.5.5
spring cloud - 2020.4
spring cloud stream - 3.1.4
spring cloud function - 3.1.4
```
@RequiredArgsConstructor
@Controller
@SpringBootApplication
public class DemoApplication {

    private final StreamBridge streamBridge;

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class);
    }

    @RequestMapping
    @ResponseStatus(HttpStatus.ACCEPTED)
    public void sendMsg() {
        String data = """
                [{"color":"red"},{"color":"blue"}]""";
                streamBridge.send("myDestination", data);
    }
}

```

**Comment by olegz** [comment]
What is the signature of the receiving function?

**Comment by olegz** [comment]
well, let me look first, If it is a stream issue i'l transfer it

**Comment by olegz** [comment]
So, I believe this has been resolved as part of another issue - https://github.com/spring-cloud/spring-cloud-function/commit/9c621f6d04608a0c5b28517bedfd487a8bee7493

In any event I just tried with your example and everything was successful 
You can try t with the latest 3.1 snapshot - 3.1.6-SNAPSHOT and let us know if you still see issues
