### ISSUE TITLE
Add `@EnableFunctionRegistry`

### ISSUE THREAD

**Issue by markfisher** [spring-cloud/spring-cloud-function#75]
Currently the `spring-cloud-function-compiler` can act as ether an app (`java -jar`) or a library. As an app, it exposes the `/function/` REST endpoints, but as a library it simply provides the proxy app listener that itself uses `FunctionCompiler` et al.

We should add support for `@EnableFunctionRegistry` so that the `/function/` REST endpoints can be enabled when `spring-cloud-function-compiler` is a dependency (and perhaps add `@EnableLambdaCompilation` or something similar as well, rather than always-on auto-config for the app listener).

**Comment by olegz** [comment]
Closing it due to trying to stay away from anything `@Enable`.
