### ISSUE TITLE
AWS: APIGatewayProxyRequestEvent not usable with routing

### ISSUE THREAD

**Issue by fabricemarchal** [spring-cloud/spring-cloud-function#751]
**Describe the bug**
function such as  `Function<APIGatewayProxyRequestEvent, String> myfunction()` are not composable. 
If deployed as the only handler, the event is correctly  populated with the data from APIGateway.
If deployed with routing (as in the example from `function-sample-aws-routing`), the event is empty.
(AWSLambdaUtils , inputType will be deserialized as a `java.lang.Object` instead of `APIGatewayProxyRequestEvent`)

**Sample**
In example `function-sample-aws-routing`, try to put a function with the signature described above.

**Comment by olegz** [comment]
Resolved with https://github.com/spring-cloud/spring-cloud-function/commit/306895dc17e5f1a4a28cd5b83b418b6d2d1e6686
https://github.com/spring-cloud/spring-cloud-function/commit/eeb5448a7d7415c41aff5cbba154bcb80d6836ea
