### ISSUE TITLE
Spring Cloud Function adapter for Azure (class org.springframework.cloud.function.adapter.azure.FunctionInvoker) does not “transmit” reactive behavior.  

### ISSUE THREAD

**Issue by alain-marcel** [spring-cloud/spring-cloud-function#757]
We want to write reactive java function, with Azure Function.
But now the returned value of handler is not of type Mono or Flux.
The handler is implemented in handleRequest() method of class org.springframework.cloud.function.adapter.azure.FunctionInvoker.

A piece of code of this class is shown bellow.
We can see that there is blocking call.

```java
   if (output instanceof Publisher) {
            if (FunctionTypeUtils.isMono(function.getOutputType())) {
                return (O) this.convertOutputIfNecessary(input, Mono.from((Publisher) output).blockOptional().get());
            }
            else {
                List resultList = new ArrayList<>();
                for (Object resultItem : Flux.from((Publisher) output).toIterable()) {
                    if (resultItem instanceof Collection) {
                        resultList.addAll((Collection) resultItem);
                    }
                    else {
                        if (Collection.class.isAssignableFrom(FunctionTypeUtils.getRawType(function.getInputType()))
                                && !Collection.class.isAssignableFrom(FunctionTypeUtils.getRawType(function.getOutputType()))) {
                            return (O) this.convertOutputIfNecessary(input, resultItem);
                        }
                        else {
                            resultList.add(resultItem);
                        }
                    }
                }
                return (O) this.convertOutputIfNecessary(input, resultList);
            }
        }
```

Thanks.

**Comment by alain-marcel** [comment]
Here are some details.

I am using the spring-cloud-function-adapter-azure SDK to build his function, and your expectation is return value to be in the form of Mono and Flux, but the function cannot return the corresponding value. 
 
 
The code link provided by the official website: 
 [Getting started with Spring Cloud Function in Azure | Microsoft Docs](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/getting-started-with-spring-cloud-function-in-azure#create-the-azure-function)

After checking the code provided by the official website, we found that only the return value in the HTTP response format was provided as follows:


`

public class HelloHandler extends FunctionInvoker<User, Greeting> {

    @FunctionName("hello")
    public HttpResponseMessage execute(
        @HttpTrigger(name = "request", methods = {HttpMethod.GET, HttpMethod.POST}, authLevel = AuthorizationLevel.ANONYMOUS) HttpRequestMessage<Optional<User>> request,
        ExecutionContext context) {
        User user = request.getBody()
                           .filter((u -> u.getName() != null))
                           .orElseGet(() -> new User(
                               request.getQueryParameters()
                                      .getOrDefault("name", "world")));
        context.getLogger().info("Greeting user name: " + user.getName());
        return request
            .createResponseBuilder(HttpStatus.OK)
            .body(handleRequest(user, context))
            .header("Content-Type", "application/json")
            .build();
    }
}

`

I would have a Mono or Flux returned, here it would be :  FunctionInvoker<User, Mono<Greeting>>.

This is supported by .Net :👍 

`
[FunctionName("Httpxample")]
public static async Task<IActionResult> Run(
  [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)]  HtppREquest req, Iloogger log) 
`

Thanks.

**Comment by RouxAntoine** [comment]
I observe same. And due to this miss reactive handling.  My handler configuration class should look like this : 

`class Reader : FunctionInvoker<ByteArray, List<XXX>>(ImportApplication::class.java) {`

**Comment by onobc** [comment]
Hi @alain-marcel 

AFAICT Azure does not currently [support asynchronous execution](https://github.com/Azure/azure-functions-java-worker/issues/244) of Java functions.

So in this case, if we returned back a Flux/Mono from `handleRequest` there would always need to be some code that subscribed to the publisher, otherwise the reactive flow would not execute. This would also go against one of our goals which is to keep as little code as possible in the `FuctionDefintion` (ideally only a single line w/ a call into `handleRequest`) . Adding this support would always require the code to subscribe. Ideally, if Azure supported async return types we could just pass the flux/mono back and it would be properly invoked and passed onto the output binding etc...

Can you tell us more about the usecase you are trying to solve w/ this?

**Comment by RouxAntoine** [comment]
Since I was also notified, I allow myself to give my experience,

On our side we have ended by implemented a new `ReactiveFunctionInvoker` which return a `Publisher<O>` cf below.
But yes I agree with @onobc we also do a `subscribe()` to use it. 
Our use case is to manually send `JmsMessage` with a `jmsTemplate` to azure service bus topic for each line of given input file.

If it can help.


```
package fr.test;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.microsoft.azure.functions.ExecutionContext;
import org.reactivestreams.Publisher;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.NoSuchBeanDefinitionException;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.WebApplicationType;
import org.springframework.cloud.function.context.*;
import org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry;
import org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry.FunctionInvocationWrapper;
import org.springframework.cloud.function.context.config.FunctionContextUtils;
import org.springframework.cloud.function.context.config.JsonMessageConverter;
import org.springframework.cloud.function.context.config.SmartCompositeMessageConverter;
import org.springframework.cloud.function.json.JacksonMapper;
import org.springframework.cloud.function.json.JsonMapper;
import org.springframework.context.ApplicationListener;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.context.event.ContextClosedEvent;
import org.springframework.messaging.support.MessageBuilder;
import org.springframework.util.CollectionUtils;
import org.springframework.util.StringUtils;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import java.lang.invoke.MethodHandles;
import java.lang.reflect.Array;
import java.lang.reflect.Type;
import java.util.Collections;
import java.util.Map;
import java.util.stream.Stream;

/**
 * This file is inspired From {@link org.springframework.cloud.function.adapter.azure.FunctionInvoker}
 * but give access to {@link applicationContext}
 *
 * @param <I> input type
 * @param <O> result type
 */
public class ReactiveFunctionInvoker<I, O> {

    private static final Logger LOGGER = LoggerFactory.getLogger(MethodHandles.lookup().lookupClass());
    private static final String EXECUTION_CONTEXT = "executionContext";

    private static FunctionCatalog functionCatalog;

    private static ConfigurableApplicationContext applicationContext;
    private static JsonMapper objectMapper;

    private static final Object lock = new Object();

    public ReactiveFunctionInvoker(Class<?> configurationClass) {
        try {
            initialize(configurationClass);
        } catch (Exception e) {
            close(null);
            throw new IllegalStateException("Failed to initialize", e);
        }
    }

    private static void initialize(Class<?> configurationClass) {
        synchronized (lock) {
            if (functionCatalog == null) {
                LOGGER.info("Initializing: {}", configurationClass);
                applicationContext = springApplication(configurationClass).run();

                Map<String, FunctionCatalog> mf = applicationContext.getBeansOfType(FunctionCatalog.class);
                if (CollectionUtils.isEmpty(mf)) {
                    objectMapper = new JacksonMapper(new ObjectMapper());
                    JsonMessageConverter jsonConverter = new JsonMessageConverter(objectMapper);
                    SmartCompositeMessageConverter messageConverter = new SmartCompositeMessageConverter(Collections.singletonList(jsonConverter));
                    functionCatalog = new SimpleFunctionRegistry(applicationContext.getBeanFactory().getConversionService(),
                        messageConverter, objectMapper);
                } else {
                    objectMapper = applicationContext.getBean(JsonMapper.class);
                    functionCatalog = mf.values().iterator().next();
                }
            }
        }
    }

    @SuppressWarnings({"unchecked"})
    public Publisher<O> handleRequest(I input, ExecutionContext executionContext) {
        String functionDefinition = executionContext.getFunctionName();
        FunctionInvocationWrapper function = functionCatalog.lookup(functionDefinition);
        if (function == null && StringUtils.hasText(functionDefinition) && applicationContext.containsBean(functionDefinition)) {
            this.registerFunction(functionDefinition);
            function = functionCatalog.lookup(functionDefinition);
        }

        // no function found with given name
        if (function == null) {
            throw new NoSuchBeanDefinitionException(executionContext.getFunctionName());
        }

        Object enhancedInput = enhanceInputIfNecessary(input, executionContext);

        Object output = function.apply(enhancedInput);
        Class<?> outputClass = output.getClass();

        if (Iterable.class.isAssignableFrom(outputClass)) {
            return Flux.fromIterable((Iterable<? extends O>) output);
        } else if (Publisher.class.isAssignableFrom(outputClass)) {
            return (Publisher<O>) output;
        } else if (Array.class.isAssignableFrom(outputClass)) {
            return Flux.fromArray((O[]) output);
        } else if (Stream.class.isAssignableFrom(outputClass)) {
            return Flux.fromStream((Stream<? extends O>) output);
        } else {
            return (Mono<O>) Mono.just(output);
        }
    }

    /**
     * Search {@link java.util.function.Function} {@link org.springframework.context.annotation.Bean} implementation
     * by spring cloud function name
     *
     * @param functionDefinition
     */
    private void registerFunction(String functionDefinition) {
        FunctionRegistration<?> functionRegistration =
            new FunctionRegistration<>(applicationContext.getBean(functionDefinition), functionDefinition);

        Type type = FunctionContextUtils.findType(functionDefinition, applicationContext.getBeanFactory());

        functionRegistration = functionRegistration.type(new FunctionType(type));
        ((FunctionRegistry) functionCatalog).register(functionRegistration);
    }

    /**
     * Add {@link EXECUTION_CONTEXT} header if missing
     *
     * @param input
     * @param executionContext
     * @return
     */
    private Object enhanceInputIfNecessary(I input, ExecutionContext executionContext) {
        if (input == null) { // Supplier
            return null;
        }
        return MessageBuilder.withPayload(input)
            .setHeaderIfAbsent(EXECUTION_CONTEXT, executionContext)
            .build();
    }

    private static SpringApplication springApplication(Class<?> configurationClass) {
        SpringApplication application = new FunctionalSpringApplication(configurationClass);
        application.setWebApplicationType(WebApplicationType.NONE);
        application.addListeners((ApplicationListener<ContextClosedEvent>) ReactiveFunctionInvoker::close);
        return application;
    }

    public static void close(ContextClosedEvent ctx) {
        functionCatalog = null;
    }

    public static ConfigurableApplicationContext getApplicationContext() {
        return applicationContext;
    }

    public static JsonMapper getObjectMapper() {
        return objectMapper;
    }

    protected static void setObjectMapper(JsonMapper objectMapper) {
        ReactiveFunctionInvoker.objectMapper = objectMapper;
    }
}
```

**Comment by olegz** [comment]
@RouxAntoine Thanks for the above code, it is understandable. Quick question, once your `ReactiveFunctionInvoker` returns from `handleRequest(..)` method, what do you do with the result? Can you share some code bits for that as well?

I mean someone has to subscribe. . .

**Comment by RouxAntoine** [comment]
Yes, we use `Flux.from(handleRequest(content, ctx))` to convert to lesser generic type.

and call a continuation of operation like `doFirst`, `map` operation and `doFinally` for logging and send message.

```
Flux.from(handleRequest(content, ctx))
    .doFirst {
        MDC.put("SpanId", spanId.toString())
        logger.info { "start - Import  ... " }
    }
    .mapNotNull {
        lateinit var message: Message
        jmsTemplate.send(topicName) { session ->
            val messageConverter: MessageConverter? = jmsTemplate.messageConverter
            if (messageConverter == null) {
                throw IllegalStateException("No 'messageConverter' specified. Check configuration of JmsTemplate.")
            } else {
                message = messageConverter.toMessage(it.result, session)
                message.jmsCorrelationID = context.invocationId
                message.jmsType = it.type.name
                return@send message
            }
        }
        return@mapNotNull message
    }
    .doFinally {
        logger.info { "end - Import ..." }
        MDC.remove("SpanId")
    }
    .subscribe()
```

**Comment by alain-marcel** [comment]
Hi everybody
Sorry for the delay.
The code you propose does not fix my need because the code integrate a reactive block.
What I want is 
   - server side : a code wtihout block (neither in spring side nor in user server side code).
   - ability to block at client side
This behavior is available with full .Net stack.

I think spring stack on Azure Function cannot do that because Azure Function for java has no such mechanism.
The next step is : how can I ask that to microsoft Azure Function teams : I need support from spring teams expert.
Thanks for any help

**Comment by RouxAntoine** [comment]
Hello @alain-marcel, 

Yes the code which i propose contains a reactive breaking with the subscribe call. But i don't understand what you win with blocking async supported by azure function like dot.net 🤔

**Comment by alain-marcel** [comment]
Hello @RouxAntoine,
Thanks for your response.

Like lambda with java in aws or azure function with dotnet, I would like to write an azure function in java without reactive breaking (i.e. no call to block).
Why ? when there is trouble in user code, we can have an infinite blocking and it is very hard to monitore.
To avoid that I have to estimate the duration of each azure function and call block(estimatedDuration) to signal error as soon as possible.
If there is no reactive breaking (and in case of chaining azure functions for example) , we could do the subcribe at client side.

I understand that azure function support for java do allow that fuctionnality (as it is done in aws lamba for java) , but I need spring expert to help me ask for an improvment at azure side.
Thanks for any help, or ideas.

**Comment by onobc** [comment]
Hi @alain-marcel ,
So I reached out to the assignee on the [associated feature request](https://github.com/Azure/azure-functions-java-worker/issues/244#issuecomment-1076412970) ticket. Let's see what they say. 

In the meantime, it may be helpful to add a plus+1 to the newly added comment.

**Comment by kaibocai** [comment]
> Hello @RouxAntoine, Thanks for your response.
> 
> Like lambda with java in aws or azure function with dotnet, I would like to write an azure function in java without reactive breaking (i.e. no call to block). Why ? when there is trouble in user code, we can have an infinite blocking and it is very hard to monitore. To avoid that I have to estimate the duration of each azure function and call block(estimatedDuration) to signal error as soon as possible. If there is no reactive breaking (and in case of chaining azure functions for example) , we could do the subcribe at client side.
> 
> I understand that azure function support for java do allow that fuctionnality (as it is done in aws lamba for java) , but I need spring expert to help me ask for an improvment at azure side. Thanks for any help, or ideas.

Hi @alain-marcel ,

Sorry I am not able to fully understand your use case. It will be great if you can give more context at [this issue](https://github.com/Azure/azure-functions-java-worker/issues/244). 
I was also wondering if you have checked out below features provided by azure functions, it they are going to help with your use case. 

[Azure Durable Functions](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-overview?tabs=java)
[Azure Functions with Application Insights](https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring)
[Application Insights - Distributed Tracing](https://docs.microsoft.com/en-us/azure/azure-monitor/app/distributed-tracing)

Thanks.
