### ISSUE TITLE
Azure ExecutionContext not registered in Spring Application Context

### ISSUE THREAD

**Issue by derSchtefan** [spring-cloud/spring-cloud-function#759]
Contrary to what https://cloud.spring.io/spring-cloud-static/spring-cloud-function/3.0.0.M1/azure.html#_accessing_azure_executioncontext  states, the ExecutionContext is not registered into the spring application context. It can neither be retrieved via dependency injection into any bean or component (or the Function<>), nor is it registered under the bean name targetExecutionContext in the application context / bean factory.

Using version 3.1.4

**Comment by derSchtefan** [comment]
FYI: I ended up registering the Execution Context into a InheritableThreadLocal with a WeakReference<T> upon function start and removed it on end, and used @CustomLog from Lombok to call into a logger that reads the Execution Context and thus the target logger from there.

That was the only viable solution to get logging done in Azure Functions with Spring

**Comment by olegz** [comment]
Sorry, i just pushed and backported doc updates so should be fine from now one. 
But basically the execution context available as Message header - https://github.com/spring-cloud/spring-cloud-function/blob/main/spring-cloud-function-samples/function-sample-azure/src/main/java/example/Config.java#L48

**Comment by derSchtefan** [comment]
The whole thing goes a bit deeper anyway, as with Azure Functions the ExecutionContext is only valid for that single call. We solved it by saving it to a InheritingThreadLocal static variable in a central logging system, and redirecting all logs to that instance, if it is present.

Otherwise you end up dragging the ExecutionContext and the logger through the whole system.
It is a pitty this is not abstracted away by Azure, and a function can simply use a Sl4j2 logger.

**Comment by olegz** [comment]
I understand, but at hat was actually fixed a while back, but we forgot to update the docs. So the point if having ExecutionContext as Message Header implies that you'll have a new one or the most current one on every invocation.

**Comment by derSchtefan** [comment]
I do undestand, but your example only works "okay" if you assume an Azure function's work is done in a couple of lines of code in a single class, in a single method, while often it is split out into multiple methods, components, services, etc. Each invocation of a service, each method call, will have the Message or ExecutionContext be passed around. It is super impractical.

That is why we chose to capture the ExecutionContext in a InheritingThreadLocal when the function is called, and use our own custom logger that wraps around it with lombok accross the whole application.
