### ISSUE TITLE
Recent change SimpleFunctionRegistry/fluxifyInputIfNecessary breaks routing Messages with array payloads

### ISSUE THREAD

**Issue by fiidim** [spring-cloud/spring-cloud-function#762]
**Describe the bug**
I noticed this side effect from the `stream-applications` process, `router-sink` function.  When you consider a function signature of `Function<Message<?>, Message<List<Object>>>`, the message payload does not get deserialized as a whole, but instead broken into several messages.  Prior to this change, there were no issues.

From tracing through, the new section of code that causes this is here:
https://github.com/spring-cloud/spring-cloud-function/blob/90cec8e350c5e1cd5ced9c3fec3c80486c18dc65/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/context/catalog/SimpleFunctionRegistry.java#L762-L773

Noteworthy is that enqueued messages are converted to `byte[]` arrays, but are set with `contentType=application/json`.

**Comment by olegz** [comment]
But what if your function is `Function<String, String>` and you are sending it `["foo", "bar"]`. If we convert it to `Message<List<String>>` you will end up with `ClassCastException`, since Function does not take List as input.
Did I miss something?

**Comment by olegz** [comment]
May be if input type is unknown (e.g., `Function<Object,...>` or `Function<Message<?>, ...>` or `Function<byte[], ...>` etc), we should not go through that fluxifying logic and treat input s is?

**Comment by olegz** [comment]
I think i see the issue now. We just need to be a bit more clever as to what we do and when we do it . For example

* If function input is typeless (Message<?>, byte[], Object), then do nothing and pass input as is
* If function input is Collection<Message>, then pre-convert input to Collection of messages (as what was done already but unconditionally)
* If function input is Message<Collection<?>>, then pre-convert input to Message<Collection<?>>

**Comment by fiidim** [comment]
I don't have the context of why the original change was made, but what you wrote sounds correct, and would produce the previous (desired) behaviour.
