### ISSUE TITLE
Add config option to enrich individual headers on output message

### ISSUE THREAD

**Issue by Nephery** [spring-cloud/spring-cloud-function#764]
**Is your feature request related to a problem? Please describe.**
It would be nice if the framework provided a configuration-driven output enricher that would allow for operators to set default header values or to override header values on outgoing messages.

Of course this can already be done using function composition, but just like #676, it would be great to have this for simple use cases to keep messaging logic within the application's configuration and out of business logic code.

**Describe the solution you'd like**
Similar to #676, a `spring.cloud.function.configuration.<function-name>.output-header-mapping-expression.<header-name>` config option could be added where its value is a SpEL expression that accepts the outgoing message as its context. That way you could use this config option for both setting default header values or for overriding header values.

e.g. to set the default header value for header `key1` on all output messages of function `echo`:
```
spring.cloud.function.configuration.echo.output-header-mapping-expression.key1="headers.key1 ?: 'hello1'"
```

e.g. To override the header value for header `key1` on all output messages of function `echo`:
```
spring.cloud.function.configuration.echo.output-header-mapping-expression.key1="'hello1'"
```

**Describe alternatives you've considered**
If providing the entire message as the SpEL's context is overkill, then just providing the header value would be sufficient.

**Additional context**
This issue originates from https://github.com/SolaceProducts/solace-spring-cloud/issues/93 where we were asked to provide a way to set default values for Solace headers on outgoing messages as part of the Solace Binder's binding config. Though instead of implementing this feature just for the Solace binder, I think this might be better suited to be generally implemented at the framework level.

**Comment by Nephery** [comment]
@olegz thanks for responding to this so quickly!

I gave it a test on the 3.1.x branch, but it looks like `output-header-mapping-expression` is being applied on the incoming message instead of the outgoing one.

**To reproduce:**

Using the `function-sample-pojo` sample, set `spring.cloud.function.configuration.uppercase.output-header-mapping-expression.testout='testvalue'` in `application.properties`.

Change the uppercase function to:
```java
@Bean
public Function<Message<Foo>, Bar> uppercase() {
	return value -> {
		System.out.println(value.getHeaders().get("testout"));
		return new Bar(value.getPayload().uppercase());
	};
}
```

Send some data to the function:
```
curl -H 'Content-Type: application/json' localhost:8080/uppercase -d '{"value": "foo"}'
```

Notice that the incoming message to `uppercase()` has it's `testout` header set to `testvalue`. I would've expected `testout` to not be present at all on the incoming message.

**Comment by olegz** [comment]
Oops

**Comment by olegz** [comment]
Fixed it and modified a test to ensure that output headers are not present on the input.

**Comment by Nephery** [comment]
Retested it on the `3.1.x` branch. Everything works now. Thanks! 🎉
