### ISSUE TITLE
Expose FunctionCatalog via an Actuator Endpoint

### ISSUE THREAD

**Issue by salaboy** [spring-cloud/spring-cloud-function#766]
**Is your feature request related to a problem? Please describe.**

The FunctionCatalog provides a list of all Suppliers,Consumers and Functions but it is not exposed as an endpoint.

**Describe the solution you'd like**

I would like to have an optional actuator endpoint to expose the FunctionCatalog: Set<String> getNames(Class<?> type);

**Describe alternatives you've considered**

**Additional context**
Discussed in slack with @olegz and @dsyer

**Comment by dsyer** [comment]
An actuator endpoint can't (easily) have a `Class<?>` as an input argument. Is it actually an actuator endpoint you need?

**Comment by salaboy** [comment]
@dsyer is there any other way to expose this in an endpoint that I can consume from outside the container running the functions?

**Comment by olegz** [comment]
If you have access to application context, you can get FunctionCatalog bean and access what you need from there

**Comment by salaboy** [comment]
@olegz the idea of having an endpoint is to enable the infrastructure to poll and access that information from outside of the container running the functions, so programatic access would not work. 

Regarding @dsyer comment, I was expecting something like the `routes` endpoint from the `spring-cloud-gateway` project which expose the available routes inside the gateway. 

I am happy to explore alternatives if I am pointed in a direction that you think that is feasible.
