### ISSUE TITLE
Function output converted to Message<byte[]> if Spring Cloud Sleuth is present

### ISSUE THREAD

**Issue by blake-bauman** [spring-cloud/spring-cloud-function#769]
**Description**

If you have a Function with any output type, if Spring Cloud Sleuth is present, the output will get wrapped in a GenericMessage and the payload converted to a byte[].

This started happening with 3.1.4.  The issue seems to be in [FunctionInvocationWrapper.convertOutputIfNecessary()](https://github.com/spring-cloud/spring-cloud-function/blob/v3.1.4/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/context/catalog/SimpleFunctionRegistry.java#L1044).  In 3.1.4 an additional condition was added with `functionAroundWrapper == null`.  In 3.1.3, this condition was not there and the function invocation passed this condition because `contentType` was empty and the output was not a `Publisher`.  In 3.1.4, if Spring Cloud Sleuth is present, `functionAroundWrapper` is not null because `TraceFunctionAroundWrapper` is being applied.

Reverting to 3.1.3 resolves the issue and so does removing Spring Cloud Sleuth.

**Sample**

To reproduce:

1. Create a `@Bean` of type `Function<String, String>`.
2. Make sure `spring-cloud-starter-sleuth` is present.
3. Use `FunctionCatalog.lookup()` to retrieve this function.
4. Call `apply()` on the function with any String.
5. The call results in a `ClassCastException` saying that it cannot cast a `GenericMessage` to a `String`.
6. Using a debugger, you can see that the final output is a `Message<byte[]>` instead of String.

**Comment by olegz** [comment]
Pleas clarify what version of sleuth you are using?

**Comment by blake-bauman** [comment]
I'm importing the 2020.0.4 version of `spring-cloud-dependencies`

**Comment by olegz** [comment]
it's fixed and backported. We'll be doing another cloud release in beginning of Dec

**Comment by blake-bauman** [comment]
awesome. thanks!

**Comment by ThomasVitale** [comment]
@olegz it looks like this is still an issue when using the newly released Spring Cloud 2021.0.0. In particular:
- Spring Cloud Function 3.2.1
- Spring Cloud Stream 3.2.1
- Spring Cloud Sleuth 3.1.0

**Comment by olegz** [comment]
@ThomasVitale sorry about that, but i seems like we're having sleuth related issues.  Can you please disable sleauth tracing and see if this works. Just set  `spring.sleuth.function.enabled=false` property

**Comment by ThomasVitale** [comment]
@olegz if I disable Sleuth with `spring.sleuth.function.enabled=false` then the tests run successfully. Is it something that can be fixed in Spring Cloud Function or should I open an issue on the Spring Cloud Sleuth project?

**Comment by olegz** [comment]
@ThomasVitale, i spoke with @marcingrzejszczak earlier and he has already fixed it is sleuth. So we may need to do a quick sleuth patch release on Monday. Stay tuned

**Comment by ThomasVitale** [comment]
Perfect, thanks a lot!

**Comment by blake-bauman** [comment]
Thanks for catching this @ThomasVitale

**Comment by marcingrzejszczak** [comment]
Can you check whether `2021.0.0-SNAPSHOT` works fine?

**Comment by ThomasVitale** [comment]
@marcingrzejszczak In my demo app, I have 3 tests that fail because of a `ClassCastException` with the following errors, when using `2021.0.0`:
1. `class com.example.springcloudfunctionsleuthbug.OrderAcceptedMessage cannot be cast to class org.springframework.messaging.Message`
2. `class java.lang.Long cannot be cast to class org.springframework.messaging.Message`
3. `class com.example.springcloudfunctionsleuthbug.OrderAcceptedMessage cannot be cast to class org.reactivestreams.Publisher`

I tried using `2021.0.0-SNAPSHOT` and now the first error is solved. Tests number 2 and 3 still fail.

**Comment by olegz** [comment]
@ThomasVitale what is the signature for functions 2 and 3 tests?

**Comment by ThomasVitale** [comment]
@olegz the functions are defined as follows:

```java
record OrderAcceptedMessage(Long orderId){}
record OrderDispatchedMessage(Long orderId){}

@Configuration
class DispatchingFunctions {

    @Bean
    Function<OrderAcceptedMessage, Long> pack() {
        return orderAcceptedMessage -> {
            return orderAcceptedMessage.orderId();
        };
    }

    @Bean
    Function<Flux<Long>, Flux<OrderDispatchedMessage>> label() {
        return orderFlux -> orderFlux.map(orderId -> {
            return new OrderDispatchedMessage(orderId);
        });
    }
}
```

And the 2 tests failing are as follows. They were working with Spring Cloud `2021.0.0-M3`.

```
@FunctionalSpringBootTest
class DispatchingFunctionsIntegrationTests {

	@Autowired
	private FunctionCatalog catalog;

	@Test
	void labelOrder() {
		Function<Flux<Long>, Flux<OrderDispatchedMessage>> label = catalog.lookup(Function.class, "label");
		Flux<Long> orderId = Flux.just(121L);

		StepVerifier.create(label.apply(orderId))
				.expectNextMatches(dispatchedOrder ->
						dispatchedOrder.equals(new OrderDispatchedMessage(121L)))
				.verifyComplete();
	}

	@Test
	void packAndLabelOrder() {
		Function<OrderAcceptedMessage, Flux<OrderDispatchedMessage>> packAndLabel =
				catalog.lookup(Function.class, "pack|label");
		long orderId = 121;

		StepVerifier.create(packAndLabel.apply(new OrderAcceptedMessage(orderId)))
				.expectNextMatches(dispatchedOrder ->
						dispatchedOrder.equals(new OrderDispatchedMessage(orderId)))
				.verifyComplete();
	}
}
```

Source code: https://github.com/ThomasVitale/spring-cloud-function-sleuth-bug

**Comment by olegz** [comment]
This is perfect, thank you @ThomasVitale  and sorry about all this mess. Will sort it out by the end of Monday

**Comment by ThomasVitale** [comment]
@olegz no worries, thanks a lot for looking into this issue in such a timely manner. If there's anything I can do to help, just let me know, I'd be happy to!

**Comment by blake-bauman** [comment]
Is there a resolution for this?

**Comment by olegz** [comment]
disconnect sleuth for now until the new release of sleuth is available `spring.sleuth.function.enabled=false`

**Comment by blake-bauman** [comment]
@olegz I'm still having this error with SCF 3.2.2 and SCSleuth 3.1.1 where a `Function<Foo, Mono<Bar>>` has the `result` converted to `Message<Mono<Bar>>` which ends up as a ClassCastException since it's looking for `Mono<Bar>`.  It's not clear in my debugging if this is a Sleuth issue wrapping in a Message when it shouldn't, or if it's SCF not unwrapping properly.

Should I open a new Issue in this project first?  My suspicion is that it's [this change here](https://github.com/spring-cloud/spring-cloud-function/commit/c86890806e856ef90f64f2b2e6142731eef74747#diff-f402dc47373cf433cb40bdebb95a4012ab40017839e9b0af6124349a71a038b0R1025) but I'm not sure if that was intentional and Sleuth is the real culprit.

**Comment by blake-bauman** [comment]
Actually, it looks like the issue is that the Bean definition for the Function has the response type as `org.reactivestreams.Publisher` even though it was returning Mono, so the `FunctionThypeUtils.isPublisher()` since it wasn't Mono or Flux specifically.

Is it required that the Bean definition have Flux or Mono explicitly as the return type?  (I'm not able to determine why this was working in earlier releases)
