### ISSUE TITLE
Kotlin lambda support?

### ISSUE THREAD

**Issue by linux-china** [spring-cloud/spring-cloud-function#77]
Now spring cloud function supports Function, Consumer, and Supplier in  java.util.function package.  Any idea to support Kotlin lambda? 

Function  ==   (T) -> R
Consumer  ==  (T) -> Unit
Supplier ==  ()-> T

Kotlin Code with java function
```
 @Bean
    fun uppercase(): Function<String, String> {
        return Function { it.toUpperCase() }
    }
```

Kotlin Code with Lambda

```
    @Bean
    fun uppercase2(): (String) -> String {
        return { it.toUpperCase() }
    }
```

**Comment by sdeleuze** [comment]
Obviously :+1:  from me on that one @markfisher ;-)

With Spring ongoing builtin Kotlin support (in [Framework](https://spring.io/blog/2017/01/04/introducing-kotlin-support-in-spring-framework-5-0), Boot, Data, Reactor) and Kotlin first class support for [functional programming](https://kotlinlang.org/docs/reference/lambdas.html), such support would make sense.

Even from a Java perspective, I tend to think supporting any kind of functional interface with the required signature would make sense.

On a related note, as part for Spring Framework 5 we have also put a focus on supporting immutable data classes which are a key building block in functional programming. See [SPR-15199](https://jira.spring.io/browse/SPR-15199) and [SPR-15673](https://jira.spring.io/browse/SPR-15673) for more details. It would be nice to make sure that Spring Cloud function leverage these capabilities.
