### ISSUE TITLE
Startup, parsing, routing tests for spring cloud function aws

### ISSUE THREAD

**Issue by Pilleo** [spring-cloud/spring-cloud-function#777]
**Is your feature request related to a problem? Please describe.**
Now we can test functions for aws just like any other Spring Boot app. Which is great to test business logic.
But for example if there is no `spring.cloud.function.definition` property it will still work, but in actual lambda it will fail. 
Same problem with testing using raw input: parsing stage is just skipped. The only way to test configuration and parsing reliably is to use `org.springframework.cloud.function.adapter.aws.FunctionInvoker`, but than we do not have an option to mock things except dirty ones like constructor mocking.

**Describe the solution you'd like**
 - Spring cloud function tests to fail because of wrong configuration like real lambda would fail
 - a way to test using raw input payload to test that data can be parsed and routed correctly

**Describe alternatives you've considered**
Currently we are using constructor mocking and FunctionInvoker which is dirty, but helps to identify many problems early

**Comment by olegz** [comment]
Couple of questions
1. What do you mean when you say `using raw input payload`. Isn 't it what `FunctionInvoker` will do as a first component that sits between Lambda environment and s-c-function?
2. You're basically asking to mock Lambda environment. In theory that is possible, but would be rather time consuming effort and really hard to maintain as Lambda environment itself changes.
3. What do you mean when you say `using constructor mocking and FunctionInvoker`? Can you post a sample for clarity?

**Comment by olegz** [comment]
I am closing it since there seems to be misunderstanding on the testing strategies around FunctionInvoker. It being a framework component should not be additionally tested by the sers and instead bugs should be reported against it so we can fix them.
