### ISSUE TITLE
How to configure the Kafka input/output topic names?

### ISSUE THREAD

**Issue by codependent** [spring-cloud/spring-cloud-function#78]
How can we customize the destination Kafka topic name to which stream functions write?

Given this supplier:

```
@SpringBootApplication
public class SupplierApplication {

	private Logger logger = LoggerFactory.getLogger(getClass());
	
	public static void main(String[] args) {
		SpringApplication.run(SupplierApplication.class, args);
	}
	
	@Bean
	public Supplier<Flux<String>> getValue(){
		return () -> {
			return Flux.interval(Duration.ofSeconds(1)).map( i -> String.valueOf(Math.random()))
				.doOnNext( val -> logger.info("*** Producing {} ***", val));
		};
	}
}
```
application.yml
```
spring:
  application:
    name: supplier

server:
  port: 8282
```
I see that this stream writes to `supplier:8282.output`: 
`o.s.integration.channel.DirectChannel    : Channel 'supplier:8282.output' has 1 subscriber(s).`

How can I customize it? 

Idem for a consumer that should read from the previous topic.

**Comment by markfisher** [comment]
Under the covers these are just Spring Cloud Stream bindings, and those are configurable using Boot properties (see: http://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#binding-properties).

For an output channel (a `Supplier` or a `Function`'s return values), provide:

```
spring.cloud.stream.bindings.output.destination=[topicName]
```

For an input channel (a `Consumer` or a `Function`'s parameter), provide:

```
spring.cloud.stream.bindings.input.destination=[topicName]
```
