### ISSUE TITLE
Invalid JSON response in AWS adapter

### ISSUE THREAD

**Issue by oclay1st** [spring-cloud/spring-cloud-function#787]
**Describe the bug**
After upgrading to 3.2.1 the resulting body response for the AWS adapter becomes invalid. This is caused because the double quotes were removed from the output. Is there any workaround?

**Comment by oclay1st** [comment]
@olegz, any advice?. Thanks in advance

**Comment by olegz** [comment]
Sorry, I was on PTO, will look shortly

**Comment by olegz** [comment]
@oclay1st Sorry, just getting to it. Can you please provide more details as I can not reproduce it, but perhaps I am looking at the wrong thing

**Comment by oclay1st** [comment]
@olegz 
The following line of code replaces quotes with an empty string which results in an invalid body response if you try to return a JSON.

https://github.com/spring-cloud/spring-cloud-function/blob/b89b7f325efafdc519934d7e1dec08d4dd14eca0/spring-cloud-function-adapters/spring-cloud-function-adapter-aws/src/main/java/org/springframework/cloud/function/adapter/aws/AWSLambdaUtils.java#L196

Current behavior:
 `body =  "{\"key\":\"value\"}"`
 after processing the output:
  `body = {key:value}`  // Invalid JSON

**Comment by oclay1st** [comment]
@olegz Can we have this fix in 3.2.x, please?. This basically prevents me from using recent versions of spring native

**Comment by olegz** [comment]
it already is
