### ISSUE TITLE
Add a copyInputHeaders boolean option for function configuration

### ISSUE THREAD

**Issue by artembilan** [spring-cloud/spring-cloud-function#791]
It looks like currently the `Function` contract does not carry the input message headers to the output message automatically. 

The current solution is explained here: https://docs.spring.io/spring-cloud-function/docs/3.2.1/reference/html/spring-cloud-function.html#_inputoutput_enrichment.
But those `output-header-mapping-expression` is not so request-agnostic and requires a knowledge about headers we would like to copy.

Imaging a use-case when we just host somewhere a common function which can be called may other ways, one of which is a request-reply over Spring Cloud Stream bindings.
The caller of such a function may decide itself what kind of correlation it can use, e.g. with Spring Integration gateway it is standard `replyChannel` header. 
Other solutions may provide their own header to correlate a reply back from the output destination.

So, the proposal is to have a generic `spring.cloud.function.configuration.uppercase.copy-input-headers=true/false` and don't care what headers are coming together with request.
We just copy them back to the reply if not present already.
This will be an alignment what we have so far in Spring Integration: https://docs.spring.io/spring-integration/docs/current/reference/html/messaging-endpoints.html#service-activator-return-type

**Comment by borg1310** [comment]
hi @olegz ,

i tried the copy-input-headers property with a reactive flux stream (see [0]). but this (see [2]) does not work. is this not intended or am i doing something wrong?

thanks in advance

best regards,
juergen

[0]
````
    @Bean
    public Function<File, File> testWithoutFlux() {
        return Function.identity();
    }
    
    @Bean
    public Function<Flux<File>, Flux<File>> testWithFlux() {
        return Function.identity();
    }
````
[1] this works
````
@Test
	public void test3() {
		try (ConfigurableApplicationContext ac = new SpringApplicationBuilder(FileSplitterProcessorApplication.class)
				.run("--logging.level.org.springframework.cloud.function=DEBUG",
						"--spring.main.lazy-initialization=true",
						"--spring.cloud.function.definition=testWithoutFlux",
						"--spring.cloud.function.configuration.testWithoutFlux.copy-input-headers=true")) {
			FunctionCatalog catalog = ac.getBean(FunctionCatalog.class);

			Function<Message<File>, Message<byte[]>> uppercase = catalog.lookup("testWithoutFlux", "application/json");
			Message<byte[]> result = uppercase.apply(MessageBuilder.withPayload(new File("test/bla")).setHeader("foo", "bar").build());
			assertThat(result.getHeaders()).containsKey("foo");
			System.out.println(result.getHeaders());
		}
	}
````

[2] this does not work
````	
	@Test
	public void test4() {
		try (ConfigurableApplicationContext ac = new SpringApplicationBuilder(FileSplitterProcessorApplication.class)
				.run("--logging.level.org.springframework.cloud.function=DEBUG",
						"--spring.main.lazy-initialization=true",
						"--spring.cloud.function.definition=testWithFlux",
						"--spring.cloud.function.configuration.testWithFlux.copy-input-headers=true")) {
			FunctionCatalog catalog = ac.getBean(FunctionCatalog.class);

			Function<Flux<Message<File>>, Flux<Message<byte[]>>> uppercase = catalog.lookup("testWithFlux", "application/json");
			Flux<Message<byte[]>> result = uppercase.apply(Flux.just(MessageBuilder.withPayload(new File("test/bla")).setHeader("foo", "bar").build()));
			StepVerifier.create(result)
				.expectNextMatches(a->{	
					System.out.println(a.getHeaders());
					return a.getHeaders().containsKey("foo");
				})
				.expectComplete()
				.verify();
		}
	}
````
