### ISSUE TITLE
Map input should not be serialized with Jackson if Func input accepts same Map input (Regression)

### ISSUE THREAD

**Issue by blake-bauman** [spring-cloud/spring-cloud-function#794]
Up through version 3.1.3, if you had a `Function<Map<X, Y>, Z>` and passed a value of type `Map<X, Y>` as input, the Map would be passed as-is. Internally, spring-cloud-function would use `MapToMapConverter` to "convert" the map (by making a copy).

Starting in 3.1.4 and later releases, the Map gets serialized into Jackson, losing type information and causing an unnecessary performance hit.

**Sample**

If you have a `Function` like:

```java
	@Bean
	public Function<Map<String, Object>, Object> testFunc() {
		return map -> map.get("foo");
	}
```

Or, using MongoDB's `Document`:

```java
	@Bean
	public Function<Document, Date> testFuncDocument() {
		return doc -> doc.getDate("foo");
	}
```

If you use the `FunctionCatalog` to look up the Function and call `apply()`, in 3.1.3 this is successful.  In 3.1.4 and later, the Map gets serialized via Jackson and immediately deserialized back into  a Map.  In the process, the type information for non-primitive values get lost.  In the 1st Function above, the result is a Long.  In the 2nd Function above, this results in a ClassCastException.

What's interesting is that this all works as expected if you wrap the `Map` in a `Message` container.

**Additional Context**

This is a followup to #768 where I did some more testing and attached a project with `@Test` cases in the `DemoTest` class.

[demo.tar.gz](https://github.com/spring-cloud/spring-cloud-function/files/7937003/demo.tar.gz)

If you run `DemoTest` using 3.1.3, the test cases pass.  If you change the version to 3.1.4 or later, the tests which don't use `Message` fail.

**Analysis**

The issue seems to stem from [FunctionInvocationWrapper.convertInputIfNecessary()](https://github.com/spring-cloud/spring-cloud-function/blob/v3.1.4/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/context/catalog/SimpleFunctionRegistry.java#L987). In 3.1.4 an additional condition was added with `input instanceof Map` in the call to `this.convertNonMessageInputIfNecessary()` which makes `maybeJson == true` instead of `false` as it is in 3.1.3. This causes the Map to be serialized via Jackson instead of using the `MapToMapConverter`.

In 3.1.3, `maybeJson` is `false` in this scenario and the `MapToMapConverter` gets used instead, which simply copies the key/value pairs instead of serializing/deserializing.  Not only is this preferred functionally, but it performs better because the types are the same and conversion is unnecessary.

**Comment by olegz** [comment]
This was part of the refactoring and I can not remember why `input instanceof Map` was added. I suspect it has something to do with parallel refactoring in s-c-f-web. In any event, it appears that this condition is no longer necessary. I am also adding a test

**Comment by blake-bauman** [comment]
Thanks for the fix.  I appreciate it.  Is there a 3.2.X SNAPSHOT version that I could try this fix with locally?

**Comment by blake-bauman** [comment]
@olegz Is there a 3.2.X SNAPSHOT I can test with which has this fix?

**Comment by olegz** [comment]
Yes, 3.2.2-SNAPSHOT

**Comment by olegz** [comment]
@blake-bauman please give it a shot and see if you can confirm before Feb 16 as we'll be making a release

**Comment by blake-bauman** [comment]
Looking good with my main app, too.

**Comment by olegz** [comment]
Thank you for the confirmation
