### ISSUE TITLE
avroSchemaMessageConverter bean conflicting with spring-cloud-schema-registry-client

### ISSUE THREAD

**Issue by stefnoten** [spring-cloud/spring-cloud-function#797]
When using both spring-cloud-schema-registry-client (1.1.5) and spring-cloud-function (through spring-cloud-stream 3.2.1), there are conflicting beans (introduced in #732):

* `ContextFunctionCatalogAutoConfiguration#avroSchemaMessageConverter()` (from spring-cloud-function-context)
* `AvroMessageConverterAutoConfiguration#avroSchemaMessageConverter()` (from spring-cloud-schema-registry-client)

This leads to following error:

```
Invalid bean definition with name 'avroSchemaMessageConverter' defined in class path resource [org/springframework/cloud/schema/registry/avro/AvroMessageConverterAutoConfiguration.class]: 
Cannot register bean definition [Root bean: class [null]; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.cloud.schema.registry.avro.AvroMessageConverterAutoConfiguration; factoryMethodName=avroSchemaMessageConverter; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/cloud/schema/registry/avro/AvroMessageConverterAutoConfiguration.class]] for bean 'avroSchemaMessageConverter': 
There is already [Root bean: class [null]; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration; factoryMethodName=avroSchemaMessageConverter; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/cloud/function/context/config/ContextFunctionCatalogAutoConfiguration.class]] bound.
```

**Comment by olegz** [comment]
@sobychacko can you please take a look at this?

**Comment by sobychacko** [comment]
@stefnoten Starting with 3.2.x release of Spring Cloud Stream, we stopped shipping the schema registry clients (artifacts such as `spring-cloud-schema-registry-client`) as part of Spring Cloud Stream. The recommendation is to use other schema registries (such as the one from Confluent if you are using Kafka for example). The AVRO message converter that you are having difficulty with multiple beans does not use any schema registries, rather it uses other mechanisms such as a fully qualified schema location for schema resolution. Before decommissioning the Spring Cloud schema registry, we migrated this AVRO message converter that doesn't require the use of a schema registry into Spring Cloud Function proper. Therefore, I suggest you remove `spring-cloud-schema-registry-client` from your project and rely on the one from SCFn.

**Comment by kamko** [comment]
@stefnoten might I ask what workaround did you use for this issue?

**Comment by stefnoten** [comment]
@kamko we registered our own AvroSchemaRegistryClientMessageConverter bean with a different name:
```java
@Configuration
@AutoConfigureBefore(AvroMessageConverterAutoConfiguration.class)
public class SomeAutoConfiguration {

    @Bean
    public AvroSchemaRegistryClientMessageConverter avroSchemaRegistryClientMessageConverterToAvoidBeanNameClashes() { 
        ...
    }
}
```

**Comment by kamko** [comment]
@stefnoten thanks, I've done the same. Just hoped you found something nicer.
