### ISSUE TITLE
Reference guide "current" pointing to older docs

### ISSUE THREAD

**Issue by onobc** [spring-cloud/spring-cloud-function#817]
Navigate to https://docs.spring.io/spring-cloud-function/docs/current/reference/html/ and you will see the docs for `3.0.14.RELEASE`. 

Navigate to https://docs.spring.io/spring-cloud-function/docs/3.2.1/reference/html/ and it shows the docs for the "current" release. 

"current" should point to "3.2.1".

**Comment by trevormarshall** [comment]
The autorepo project directory was not configured with the newer [autoln-scan](https://github.com/spring-io/autoln). Should be fixed now.

**Comment by onobc** [comment]
Yep, looks good. Thanks @trevormarshall
