### ISSUE TITLE
Unable to get arguments passed by Postman

### ISSUE THREAD

**Issue by liuboren0617** [spring-cloud/spring-cloud-function#821]
<img width="886" alt="image" src="https://user-images.githubusercontent.com/39522484/156149463-8361015e-457e-460c-a7bf-b29eaa604f7a.png">

<img width="992" alt="image" src="https://user-images.githubusercontent.com/39522484/156149677-d948d1b8-7776-49a0-9dac-72af0d89da0c.png">

**Comment by olegz** [comment]
I have no idea what does this mean or relates to
