### ISSUE TITLE
Replace usage of recently removed SocketUtils

### ISSUE THREAD

**Issue by onobc** [spring-cloud/spring-cloud-function#825]
Main fails to compile as SocketUtils has been [deprecated->removed](https://github.com/spring-projects/spring-framework/issues/28052) from the Spring Framework. 

### Temporary Workaround: 
I took a very slimmed down version of `org.springframework.util.SocketUtils` and dropped it under `spring-cloud-function-core`. It only exposes the `findAvailableTcpPort` as that is all that the tests are using. 

### Suggested Alternative 
Instead user port `0`  and rely on the OS to assign a port to the server and then query the server for the port it is running on. 

#### Option 2: Create a TestSocketUtils and put in shared test lib

I have started a team discussion and will let that drive the chosen option. In the meantime I will replace as many usages as possible. 

cc: @olegz

**Comment by onobc** [comment]
About 80% through the changes w/o the need for SocketUtils so far. I do see a couple of places I may need it though.

**Comment by chrylis** [comment]
Was the referenced possible `TestSocketUtils` ever created? I am relying on `SocketUtils` because the DynamoDB Local server does not support starting on a random port.

**Comment by onobc** [comment]
Hi @chrylis - it exists in the associated PR. However, the intention is to remove it ASAP in favor of a more centrally available one (such as the one in [spring-cloud-test-support](https://github.com/spring-cloud/spring-cloud-commons/blob/main/spring-cloud-test-support/src/main/java/org/springframework/cloud/test/TestSocketUtils.java). Also, the one in the PR will not be published or usable outside of the SCF repo.
