### ISSUE TITLE
Replace local TestSocketUtils with the one in spring-test

### ISSUE THREAD

**Issue by onobc** [spring-cloud/spring-cloud-function#834]
Once https://github.com/spring-projects/spring-framework/issues/28210 adds TestSocketUtils we should remove the temporary ones recently added:
- [ ] https://github.com/spring-cloud/spring-cloud-function/commit/1fb5af28a6d658ea214763f7a4029316644e241e#diff-22f02a66dd8b5e32b8fe149c40d0c139659f57b1fcb946386c94d8adcde1f613R30
- [ ] https://github.com/spring-cloud/spring-cloud-function/commit/1fb5af28a6d658ea214763f7a4029316644e241e#diff-d37cfba905a637b0311a0840e5dfb20585d453fe855beae5cdaf41fce978df5bR30

**Comment by olegz** [comment]
As  discussed, we can also remove `SocketUtils` that I just created inside of SCF

**Comment by olegz** [comment]
Chris, should we close it? If I remember correctly we discussed that it will be addressed with your Azure custom runtime commit

**Comment by onobc** [comment]
No this is still waiting on the change in the framework. Once its available I will get it in here. 

I think you are thinking that I would remove the public one that was added in previous commits (in the scope of my PR - which I have not gotten to yet but will shortly).
