### ISSUE TITLE
Docker support for running AWS Lambda using any JDK

### ISSUE THREAD

**Issue by mrjavascript** [spring-cloud/spring-cloud-function#839]
**Is your feature request related to a problem? Please describe.**
I'm in the process of upgrading code base to JDK 17.  Amazon still hasn't provided lambda support for JDK 17.  I created a lambda in AWS to run off of a container image.  Is there a way I can launch my lambda using a Dockerfile like the following?

```
FROM amazoncorretto:17
VOLUME /tmp
COPY ./my-lambda-project/build/libs/my-lambda-project-1.0.jar app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
```

My lambda is written like this to launch:

```
public static void main(String[] args) {
    FunctionalSpringApplication.run(Application.class, args);
}
```

**Describe the solution you'd like**
In AWS I can specify the handler with the following: 

`org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest`

With the container image, this handler needs to be defined using either the ENTRYPOINT or CMD directives in the Dockerfile.

**Describe alternatives you've considered**
I've asked AWS support many times for JDK 17 support for lambda.  Google Cloud Functions has JDK 17 support and I am still waiting on Amazon.  This LTS release has been GA for over six months now.  I'd also like to move away from the shadow packaging and use a container image for the lambda invocation.

I've thought about invoking the function itself in the main method, but want to keep the main method as is (trying to make code cloud-platform agnostic.)

**Additional context**
Is there a trick to this Dockerfile to make a lambda execute using any JDK?  I could use the AWS Java lambda libraries, but the only versions that are available are JDK 1.8 and 11.

**Comment by msailes** [comment]
There are two options, you can use your own container image with an implementation of the runtime API. https://github.com/aws/aws-lambda-java-libs/tree/master/aws-lambda-java-runtime-interface-client

Or you can create a custom runtime with Java 17 until the managed runtime is available.
https://github.com/msailes/lambda-java17-layer

**Comment by mrjavascript** [comment]
Thank you!

**Comment by olegz** [comment]
Closing it as it appears to be resolved. Thank you @msailes
