### ISSUE TITLE
 If Spring cloud function 3.0.9.Release is used in spring cloud Hoxton SR12 , can I upgrade 3.0.9 release to 3.1.7?

### ISSUE THREAD

**Issue by jinsenianhua-ai** [spring-cloud/spring-cloud-function#845]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by olegz** [comment]
3.0 is at EOL and is no longer supported. Please upgrade to 3.2+
