### ISSUE TITLE
Include query parameters in Message headers for GCP cloud function

### ISSUE THREAD

**Issue by cranberrysoft** [spring-cloud/spring-cloud-function#849]
Currently, there is no way to access HTTP GET query parameters for GCP cloud function with Spring Cloud Function.

Ideally, we should include query parameters and possibly other available information like query path and URI available via `https://javadoc.io/doc/com.google.cloud.functions/functions-framework-api/latest/com/google/cloud/functions/HttpRequest.html` within Message headers

This would require changes for the GCP adapter
https://github.com/spring-cloud/spring-cloud-function/blob/4af7f603d3d7f62e72b0b88ddffbfd57c9398a07/spring-cloud-function-adapters/spring-cloud-function-adapter-gcp/src/main/java/org/springframework/cloud/function/adapter/gcp/FunctionInvoker.java#L97

**Comment by olegz** [comment]
This is actually not related to GCF, rather a generic issue and it has been addressed - https://github.com/spring-cloud/spring-cloud-function/issues/864

**Comment by cranberrysoft** [comment]
Hi @olegz 
I believe the mentioned [changes]( https://github.com/spring-cloud/spring-cloud-function/issues/864) fixed with [commit](https://github.com/spring-cloud/spring-cloud-function/commit/1a5489b5b6d4b939ebe3a99bac660a7aeeac75e9)

are addressing only the issue when you use [spring-cloud-function-web](https://docs.spring.io/spring-cloud-function/docs/current/reference/html/spring-cloud-function.html#_standalone_web_applications) module. While it does not solve the issue if you run a function with [spring-cloud-function-adapter-gcp](https://docs.spring.io/spring-cloud-function/docs/current/reference/html/spring-cloud-function.html#_google_cloud_functions)
