### ISSUE TITLE
Spring cloud function server up time is more in aws lambda

### ISSUE THREAD

**Issue by jaganm2018** [spring-cloud/spring-cloud-function#852]
Issue: Spring cloud function server up is delay.
Description: Implemented spring cloud function and deployed into AWS lambda.. Some times more request are coming, new execution service will start in aws lambda.. That's taking more than 9 seconds.. So i'm getting gateway timeout exception in apigateway and some performance issues. 

Versions:  Spring boot starter parent is 2.5.0
spring-cloud-function-dependencies: 3.1.3
spring-loud-dependencies: 2020.0.2

Note:  Used @Lazy but getting same time to start up.

Questions:
1. is there any way to make start application in milliseconds? what configuration i need to change? 
2. Can make instance running quickly like Nodejs?. Do i need to upgrade or any extra configuration I need to configure?

Please suggest me on this. Appreciate your help on quick response.

Thanks a lot.

**Comment by msailes** [comment]
Hi @jaganm2018,

@olegz has a sample from SpringOne last year which uses Spring Cloud Functions with Spring Native.

https://github.com/olegz/springone2021

This should give you cold start times similar to Nodejs.

**Comment by jaganm2018** [comment]
Thanks Msailes. I'm going to refer this project.. 
https://github.com/olegz/springone2021/tree/main/aws-native/function-aws-native-springone
Please let me know if i'm wrong. 

Once again thanks for giving reply.

**Comment by olegz** [comment]
Please try this more formal sample - https://github.com/spring-projects-experimental/spring-native/tree/main/samples/cloud-function-aws.
The sample in my repo hasn't been maintained since SpringOne

**Comment by olegz** [comment]
After reading it some more indeed I would suggest native approach if you want fast startups

**Comment by olegz** [comment]
Closing it due to lack fo followup from the original reporter
