### ISSUE TITLE
StreamBridge resetting CloudEvent headers for Kafka

### ISSUE THREAD

**Issue by jason53** [spring-cloud/spring-cloud-function#856]
I am using Spring Cloud Stream 3.2.2 to produce Cloud Event messages to a kafka topic. According to the Cloud Event spec when using kafka the headers should use a prefix of "ce_".  https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/bindings/kafka-protocol-binding.md#3231-property-names.  In my configuration I have my binder set to kafka spring.cloud.stream.bindings.myBinding-out-0.binder=kafka. When I publish a message to kafka the headers always end up with the prefix ce- instead of ce_. I have also tried using .build("ce_") and also tried setting the header target-protocol to kafka but neither worked.

When I debugged this I found that line 219 of StreamBridge https://github.com/spring-cloud/spring-cloud-stream/blob/3.2.x/core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/function/StreamBridge.java#L219 resets target-protocol which looks like it causes the prefix to be changed to "ce-".

My producer looks like:
```      
     this.streamBridge.send(
      "myBinding-out-0",
      CloudEventMessageBuilder.withData(event)
          .setSource("my-source")
          .setId(UUID.randomUUID().toString())
          .setSpecVersion("1.0")
          .setType("myType")
          .build(),
      MimeTypeUtils.APPLICATION_JSON);
```

**Comment by olegz** [comment]
The corresponding fix is comming in s-c-stream as well

**Comment by alspicer** [comment]
> The corresponding fix is comming in s-c-stream as well

Any update on if this fix is in? I was looking for what version s-c-stream has it.
