### ISSUE TITLE
Create observability module

### ISSUE THREAD

**Issue by olegz** [spring-cloud/spring-cloud-function#865]
Initial support for observability was in `spring-cloud-function-context`, but was removed with https://github.com/spring-cloud/spring-cloud-function/commit/c8d59a5f3f9ef54c2f8c06f7256f9d73369c929f in favor of this issue

**Comment by msailes** [comment]
It would be great to see an integration with [Amazon CloudWatch EMF](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format.html) for pushing metrics to Amazon CloudWatch.

**Comment by olegz** [comment]
@marcingrzejszczak @jonatan-ivanov please see the comment from Mark Sailes (above).

**Comment by jonatan-ivanov** [comment]
@msailes I'm not sure how is EMF connected to this issue, but we already have a connected issue for Micrometer: https://github.com/micrometer-metrics/micrometer/issues/3112
