### ISSUE TITLE
@EnableScheduling/@scheduled is not working along with spring cloud function

### ISSUE THREAD

**Issue by nbenjamin** [spring-cloud/spring-cloud-function#866]
**@EnableScheduling/@Scheduled is not working along with spring cloud function**

**Sample**
Have a scheduler within spring cloud function, after the deploy this changes in AWS scheduler is not working.

TestScheduler.java
```java
package com.example.springcloudfunctionwithscheduler;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

@Component
public class TestScheduler {

    private Logger LOGGER = LoggerFactory.getLogger(TestScheduler.class);

    @Scheduled(fixedDelayString = "${fixedDelay:6000}", initialDelayString = "${initialDelay:1000}")
    public void loadConfigCache() {
        LOGGER.info("Loading config cache!!");
    }
}

```

```java
package com.example.springcloudfunctionwithscheduler;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.scheduling.annotation.EnableScheduling;

import java.util.function.Function;

@Configuration
@EnableScheduling
public class FunctionConfiguration {

    @Bean
    public Function<String, String> uppercase() {
        return value -> {
            if (value.equals("exception")) {
                throw new RuntimeException("Intentional exception");
            }
            else {
                return value.toUpperCase();
            }
        };
    }
}
```

I am using the following version

```xml
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-function-dependencies</artifactId>
				<version>3.2.4</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>

```

**Comment by olegz** [comment]
What made you believe that it is supposed to work?
Out of curiosity, in your example, what would you expect the input for a function be and where do you expect the output go?

**Comment by nbenjamin** [comment]
Hi @olegz,  the above code was just a sample to see if scheduler can work or not. We actually have an function which takes `ApplicationLoadBalancerRequestEvent` and return `ApplicationLoadBalancerResposeEvent` during our process we can actually fetch some data from database and send the response. Since we have some config data in the database which can change periodically so wanted to see if we can schedule the data and load. This might not be an ideal case for lambda using scheduler to refresh the config data, currently i am just loading all the config data in the initial start up..

**Comment by olegz** [comment]
@nbenjamin Understood. We actually have another project in Spring Cloud portfolio specifically for updating configuration at runtime - https://cloud.spring.io/spring-cloud-config/reference/html/. Is that what you're looking for?

I am not against a potentially new feature in s-c-function, but want to fully understand what exactly are you trying to do

**Comment by nbenjamin** [comment]
Our use case was little different, and we were trying refresh the data in memory periodically from the database. So I was trying to see if scheduler works with spring cloud function.

**Comment by olegz** [comment]
No, scheduler does not work with Spring Cloud Function. We would have to enable it as some kind of adapter. Basically it would be no different than any other s-c-function adapter which are effectively triggers for function execution. 
If you still believe you need it let me know and I'll turn it into a feature request

**Comment by olegz** [comment]
Resolving due to inactivity
