### ISSUE TITLE
Integration with spring-state-machine for simple bpm engine

### ISSUE THREAD

**Issue by zotona** [spring-cloud/spring-cloud-function#88]
it will be like a stateless bpm. With custom dsl we could register some flow like:

```
functionFlow {
  consumer(name: 'somename', transport: queue|http, port:9000){
    if (response == 'foo'){
      payload = payload + 'foo')
      send('logger')
    } else send('nop')
  }

  consumer(name: 'logger', transport: queue|http, port:9000){
    println "LOG: $payload"
  }
}
```
 
inner {} is a groovy closure, what can be dehydrated(serialized)

**Comment by dsyer** [comment]
Ping @kbastani because he already has his hands dirty with SSM and SCFn.

**Comment by kbastani** [comment]
@zotona Happy to chat. Take a look at this example I put together that is pre-SCF https://github.com/kbastani/event-stream-processing-microservices/blob/master/account/account-worker/src/main/java/demo/config/StateMachineConfig.java.

I'm working on samples that map SSM state transitions to SCFn consumers.

Feel free to e-mail me at kbastani at pivotal.io

**Comment by cforce** [comment]
Any update here?

**Comment by olegz** [comment]
Closing it as it seem to go stale. Feel free to reopen it if there are any updates
