### ISSUE TITLE
Custom object type conversion is failing, when it has "headers" inside payload

### ISSUE THREAD

**Issue by atyamlalithya** [spring-cloud/spring-cloud-function#882]
Could no reopen the original one, so creating a new issue with the same name.
https://github.com/spring-cloud/spring-cloud-function/issues/844#issue-1187092357

**Comment by atyamlalithya** [comment]
@olegz Please review this fix,
https://github.com/atyamlalithya/spring-cloud-function/pull/1#issue-1267866786

**Comment by atyamlalithya** [comment]
@olegz Could you please verify this

**Comment by olegz** [comment]
I believe it is related to this PR - https://github.com/spring-cloud/spring-cloud-function/pull/889 so I am waiting for response on that.

**Comment by olegz** [comment]
I believe this has been addressed with the PR and subsequent commit. So I am closing this one, but feel free to open a new one if the problem persists.
