### ISSUE TITLE
Failed to start application due to 'Error creating bean with name 'functionBindingRegistrar''

### ISSUE THREAD

**Issue by LiuZHolmes** [spring-cloud/spring-cloud-function#887]
**Describe the bug**
When start an application enabling zipkin and sleuth without spring.cloud.function.definition, application failed to start due to 'Error creating bean with name 'functionBindingRegistrar''

**Sample**
pom.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.6.6</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo</name>
	<description>Demo project for Spring Boot</description>
	<properties>
		<java.version>11</java.version>
		<spring-cloud.version>2021.0.1</spring-cloud.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-function-context</artifactId>
			<version>3.2.6</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-zipkin</artifactId>
			<version>2.2.8.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream</artifactId>
			<scope>test</scope>
			<classifier>test-binder</classifier>
			<type>test-jar</type>
		</dependency>
	</dependencies>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
```
application.yml
```
server:
  port: 8080
spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    sender:
      type: web
    base-url: https://www.baidu.com
```
DemoApplication.java
```
package com.example.demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class DemoApplication {

	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}

}
```

**Comment by Funnyadd** [comment]
I have the same issue.... Does it give you the same issue if you put spring-cloud-function-context to 3.2.5?

**Comment by LiuZHolmes** [comment]
> I have the same issue.... Does it give you the same issue if you put spring-cloud-function-context to 3.2.5?

No, only 3.2.6 of it would have this issue.

**Comment by jurgc11** [comment]
I also have the same problem. I'm currently using this workaround (in Kotlin):

```kotlin
@Bean
fun fixSpringBug() = Consumer<JsonNode> {}
```

**Comment by Funnyadd** [comment]
> I think the bug happens because Spring is looking for all functions, then taking the first one without actually checking there are any.
Unfortunately, I am not sure where I would put the bean. I put it on top of the other bean definition for Consumer. It doesn't work thought.....

**Comment by Funnyadd** [comment]
Thank you so much. It worked flawlessly!
Hopefully, spring-cloud-function-context comes with a patch soon...

**Comment by olegz** [comment]
So, if I understand correctly, you don't really intend to use s-c-function, since your DemoApplication provides no function beans, but by adding zipkin some other functions gets registered. Is that correct?

**Comment by Funnyadd** [comment]
I don't know for the person who created this issue but, I am not using s-c-function really but it's still needed as a dependency in order to run my application. It would be nice if that could be corrected as my application can only run with the fix you can see commented above in this issue. Thank you for taking the time to fix this issue.

**Comment by olegz** [comment]
This is what I don't understand. You are saying you are not using s-c-function, but you need it as a dependency. What do you mean by that. 
At this point all I am suspecting is that you have s-c-function as a dependency that you are not using, but because it comes with it's own auto-configuration it searches for functions. If there is only one function it attempts to bootstrap it. It seems like that function may be brought it by zipkin. Adding dummy function ensures that there is no unique function so nothing wil be bootstrapped without `spring.cloud.function.definition` property.
I need more context as to what is the issue

**Comment by Funnyadd** [comment]
I will be honest, I am not so sure. I am curently trying to support an API and version 3.2.5 of spring-cloud-function-core/context were vulnerable. Updating to 3.2.6 broke the ApplicationContext of my API by 'not being able to create a bean'.
Here is my dependency tree if it helps:
org.springframework.cloud:spring-cloud-stream-binder-rabbit:jar:3.2.4:compile
[INFO] | +- org.springframework.cloud:spring-cloud-stream-binder-rabbit-core:jar:3.2.3:compile
[INFO] | | +- org.springframework.integration:spring-integration-amqp:jar:5.5.12:compile
[INFO] | | \- com.rabbitmq:http-client:jar:2.1.0.RELEASE:compile
[INFO] | +- org.springframework.cloud:spring-cloud-stream:jar:3.2.4:compile
[INFO] | | +- org.springframework.integration:spring-integration-core:jar:5.5.12:compile
[INFO] | | \- org.springframework.cloud:spring-cloud-function-context:jar:3.2.6:compile
[INFO] | |  +- net.jodah:typetools:jar:0.6.2:compile
[INFO] | |  +- org.springframework.cloud:spring-cloud-function-core:jar:3.2.6:compile

**Comment by Funnyadd** [comment]
Hello, do you think this issue willl be fixed in the future since my team and I are trying to find a way to not use the dummy bean created at the main application level since it's not very clean? I would like to participate in the fixing of this issue if needed.

**Comment by olegz** [comment]
I do not know what the issue is. I can not reproduce it. 
If you can provide steps to reproduce or create a small application somewhere in github that reproduces the issue soe we can look that would be ideal.

Also. . .
You can try setting `spring.cloud.stream.function.autodetect=false`, that is kind of a back door to disable auto-discovery of functions

**Comment by olegz** [comment]
@Funnyadd  have you tried the setting `spring.cloud.stream.function.autodetect=false`?

**Comment by Funnyadd** [comment]
Yes it worked, sorry we finished testing firday and everything seems to be working properly, thank you so much!

**Comment by olegz** [comment]
Ok, I am closing this as it appears to be the result of auto-discovery feature that you can now disable with `spring.cloud.stream.function.autodetect` property.

**Comment by SemenovRustam** [comment]
I encountered this problem. Reason - in application.yaml : spring.cloud.function.definition - must be only consumer.
I deleted Producer from definition and it's work well.
