### ISSUE TITLE
Custom @ComponentScan not loading spring beans in dependency package when executing as a Lambda Function

### ISSUE THREAD

**Issue by jglesner** [spring-cloud/spring-cloud-function#890]
I have a project that uses spring-cloud-function-adapter-aws.  My main class has a custom @ComponentScan that forces a scan of a package dependency I bring in with maven.  

```java
package com.mypackage.mobileapi;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;

@SpringBootApplication
@ComponentScan(basePackages = {"com.mypackage.mobileapi", "com.mypackage.data"})
public class MobileapiApplication {
	public static void main(String[] args) {
		SpringApplication.run(MobileapiApplication.class, args);
	}
}
```

In the `com.mypackage.data` package dependency, I set up HikariCP in an @Configuration class that uses an @Profile annotation.  I have that profile set to active in my `application.properties` file.  When testing locally, everything works as expected.  The `com.mypackage.data` configuration class is loaded and the Hikari dataSource is created.  

However, when uploading and testing my `MobileapiApplication` in AWS Lambda, the component scan is not running. The correct main class is used, and the right Spring profiles are being used.  But the @Configuration file in `com.mypackage.data` is not being loaded, my Hikari dataSource isn't getting created and my function complains that I have not setup a dataSource.  I am **not** using `spring.cloud.function.scan.packages` in my application.properties file, so the @ComponentScan shouldn't be getting overridden. 

Why would running a spring cloud function as an AWS Lambda prevent the custom @ComponentScan and the discovery of other spring beans? 

I'm using spring-boot-starter-parent 2.7.1 with dependencyManagement of spring-cloud-function-dependencies 3.2.6, java-lambda-core 1.2.1, aws-lambda-java-events 3.11.0.  Using the AWS classifier jar as shown in the provided [example](https://github.com/spring-cloud/spring-cloud-function/tree/main/spring-cloud-function-samples/function-sample-aws) produced by the maven-shade-plugin in conjunction with spring-boot-maven-plugin 2.7.1 and spring-boot-thin-layout 1.0.28.RELEASE.

**Comment by jglesner** [comment]
Also tried using `scanBasePackages` to no avail: 

```java 
@SpringBootApplication(scanBasePackages = "com.corkhounds.data")
public class MobileapiApplication {

	public static void main(String[] args) {
		SpringApplication.run(MobileapiApplication.class, args);
	}

}
```

This looks very similar to an issue reported late last year to spring-projects-experimental/spring-native [#1295](https://github.com/spring-projects-experimental/spring-native/issues/1295) where the OP wasn't able to use a dependency in an external package once they uploaded the function to AWS.  

@olegz Any chance you could weigh in here?

**Comment by jglesner** [comment]
Figured out the issue.  When I use the Maven Shaded Plugin snippet in the the spring-cloud-function [documentation](https://cloud.spring.io/spring-cloud-function/reference/html/index.html), specifically the [Notes About Jar Layout](https://cloud.spring.io/spring-cloud-function/reference/html/spring-cloud-function.html#_notes_on_jar_layout) for AWS Lambda functions, the transformers do not run.  I believe that's because the configuration section is misplaced.  
```xml
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-shade-plugin</artifactId>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-maven-plugin</artifactId>
		</dependency>
	</dependencies>
	<configuration>
		<createDependencyReducedPom>false</createDependencyReducedPom>
		<shadedArtifactAttached>true</shadedArtifactAttached>
		<shadedClassifierName>aws</shadedClassifierName>
		<transformers>
			<transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
				<resource>META-INF/spring.handlers</resource>
			</transformer>
			<transformer implementation="org.springframework.boot.maven.PropertiesMergingResourceTransformer">
				<resource>META-INF/spring.factories</resource>
			</transformer>
			<transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
				<resource>META-INF/spring.schemas</resource>
			</transformer>
		</transformers>
	</configuration>
</plugin>
```

For the transformers to work, and allow Spring auto-configuration to work correctly, you need to use the layout specified in the maven shade plugin [documentation](https://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html), where `<configuration/>` is included within `<executions><execution>` as shown below.

```xml
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-shade-plugin</artifactId>
	<version>3.3.0</version>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-maven-plugin</artifactId>
			<version>2.7.1</version>
		</dependency>
	</dependencies>
	<executions>
		<execution>
			<goals>
			     <goal>shade</goal>
			</goals>
			<configuration>
				<createDependencyReducedPom>false</createDependencyReducedPom>
				<shadedArtifactAttached>true</shadedArtifactAttached>
				<shadedClassifierName>aws</shadedClassifierName>
				<transformers>
					<transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
						<resource>META-INF/spring.handlers</resource>
					</transformer>
					<transformer implementation="org.springframework.boot.maven.PropertiesMergingResourceTransformer">
						<resource>META-INF/spring.factories</resource>
					</transformer>
					<transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
						<resource>META-INF/spring.schemas</resource>
					</transformer>
					<transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
						<resource>META-INF/spring.components</resource>
					</transformer>
				</transformers>
			</configuration>
		</execution>
	</executions>
</plugin>
```

Once I did this, component scanning started to work as expected.

**Comment by olegz** [comment]
Let me look into that. Sorry I was on vacation for a while, just getting back

**Comment by olegz** [comment]
@jglesner for now I am just going to update the AWS docs. The use of shade plugin is not a requirement for every boot application, so I need to really take your input and discuss it with the boot team. But as I said, lets fix the immediate problem and then see if we can improve further,

Thank you for all the details.
