### ISSUE TITLE
Http Request Params only provided with GET request that contain an argument /{function}/{item}

### ISSUE THREAD

**Issue by srunnoe** [spring-cloud/spring-cloud-function#891]
Team,

It appears that you can only get the query string parameters if you also provide a path argument. You should also be able to get query string parameters if you don't provide a path argument. Please fix or update with a comment explaining the rational. 

https://docs.spring.io/spring-cloud-function/docs/current/reference/html/spring-cloud-function.html#_http_request_parameters

public final class **FunctionWebRequestProcessingHelper**

......
		**if (argument != null) {**
			MessageBuilder builder = MessageBuilder.withPayload(argument);
			if (!CollectionUtils.isEmpty(wrapper.getParams())) {
				builder = builder.setHeader(HeaderUtils.HTTP_REQUEST_PARAM, wrapper.getParams().toSingleValueMap());
			}
			inputMessage = builder.copyHeaders(headers.toSingleValueMap()).build();
		}

**Comment by olegz** [comment]
The real issue is the fact that we use `Message headers `to communicate request parameters and `argument` becomes a payload. 
The thing is . .  Message by definition can NOT have null payload, so we need to think what would go into a payload in that case.

**Comment by olegz** [comment]
I think for web cases having payload as `""` would be sensible

**Comment by srunnoe** [comment]
Not that you asked, but I did review your code and it looks good. Thanks for the follow up.
