### ISSUE TITLE
Error creating bean with name 'awsTypesConverter' defined in org.springframework.cloud.function.adapter.aws.AWSCompanionAutoConfiguration

### ISSUE THREAD

**Issue by mahi4949** [spring-cloud/spring-cloud-function#904]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'awsTypesConverter' defined in org.springframework.cloud.function.adapter.aws.AWSCompanionAutoConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.messaging.converter.MessageConverter]: Factory method 'awsTypesConverter' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/cloud/function/cloudevent/CloudEventMessageUtils
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.messaging.converter.MessageConverter]: Factory method 'awsTypesConverter' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/cloud/function/cloudevent/CloudEventMessageUtils
Caused by: java.lang.NoClassDefFoundError: org/springframework/cloud/function/cloudevent/CloudEventMessageUtils
Caused by: java.lang.ClassNotFoundException: org.springframework.cloud.function.cloudevent.CloudEventMessageUtils. Current classpath: file:/var/task/

**Comment by olegz** [comment]
I have absolutely no idea what you are trying to report. No details of any kind. No POM. No instructions on how to reproduce it. 
I am closing it as a non-actionable/invalid issue

**Comment by mo-zachery-harley** [comment]
What solved it for us was to ensure that is you are using lambda layers, that the layer with all your dependencies is a zip file with the structure:
```
java/
├─	lib/
|	├─ depdency-a.jar
|	├─ depdency-b.jar
|	├─ depdency-c.jar
```
Using an uber jar did not work for us.

If not using layers, ensure that you are using maven shard plugin using the configuration pulled in from the spring-boot-starter-parent. 
```
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.4</version>
</parent>

  <build>
      <plugins>
          <plugin>
              <groupId>org.springframework.boot</groupId>
              <artifactId>spring-boot-maven-plugin</artifactId>
          </plugin>
          <plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-shade-plugin</artifactId>
              <configuration>
                  <createDependencyReducedPom>false</createDependencyReducedPom>
                  <shadedArtifactAttached>true</shadedArtifactAttached>
                  <shadedClassifierName>aws</shadedClassifierName>
              </configuration>
          </plugin>
      </plugins>
  </build>
  ```
