### ISSUE TITLE
AWSLambdaUtils.AWS_CONTEXT is not public 

### ISSUE THREAD

**Issue by ivcuello** [spring-cloud/spring-cloud-function#910]
Hi, 

The current documentation [here](https://github.com/spring-cloud/spring-cloud-function/blob/main/docs/src/main/asciidoc/adapters/aws.adoc) states that there's a convinient constant to access aws context from Message headers.

However it seems that the class is not public, so the constant cannot be accessed thus giving this error

```
java: org.springframework.cloud.function.adapter.aws.AWSLambdaUtils is not public in org.springframework.cloud.function.adapter.aws; cannot be accessed from outside package
```

Was this class meant not to be public ? if so. Is there another way to access the constant that's not on the current documentation ?

**Comment by olegz** [comment]
Hmm, not sure how is that possible since it is public since the beginning 0659593cfe3a5d9e8a17870f860d391dc7bdac70

Anyway, I'll close this one as there is nothing to fix

**Comment by ivcuello** [comment]
Hi @olegz , the constant is public while the class is not.
