### ISSUE TITLE
update examples to spring boot 3.x embedded native - Graal capability for improved startup times

### ISSUE THREAD

**Issue by cforce** [spring-cloud/spring-cloud-function#938]
Follow up of https://github.com/spring-cloud/spring-cloud-function/issues/586
Please provide updated examples to compile based on spring boot 3.x native support for the server less stack - e.g. aws lambda

I tried by updating, running "mvn package -Pnative" but running into continuous errors.

**Comment by olegz** [comment]
You can find many examples (including functions) here - https://github.com/spring-projects/spring-aot-smoke-tests. Just go to  `cloud` directory

**Comment by cforce** [comment]
none of them dedicates to AWS and its specific requirement to CG-LIB binding and log configuration
