### ISSUE TITLE
Problem with Sleuth tracing creating stream bindings

### ISSUE THREAD

**Issue by yelkolk** [spring-cloud/spring-cloud-function#947]
**Describe the bug**
Hi,

In my company we have several projects with Springboot. Updating one of them to version 2.7.4 (cloud **2021.0.4**) we have encountered a problem when creating exchanges in RabbitMQ.

Specifically, it seems that when upgrading the version of Spring Cloud, where before the expected exchange was created, now these two are created instead:
``traceFunctionAroundWrapper-in-0``
``traceFunctionAroundWrapper-out-0``

We have done some research and have seen some related issues like [this one](https://github.com/spring-cloud/spring-cloud-sleuth/issues/2051) but disabling Sleuth does not seem to be the best solution.

I've prepared a sample project with the minimum configuration to reproduce it, and I've been doing some digging and I'll leave what I've seen (which may be useless, but I'm putting it here in case it helps 😃):

When passing through [normalizeFunctionDefinition](https://github.com/spring-cloud/spring-cloud-function/blob/7aa56b977eb66b2b9b063c249a8f1278381515ae/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/context/catalog/SimpleFunctionRegistry.java#L237), in that list of names is the function ``traceFunctionAroundWrapper`` and it is not filtered unlike the router function, and then it is taken as the default function of the application (and it is not 🤷‍♂️).

I think [this commit](https://github.com/spring-cloud/spring-cloud-function/commit/1381cd4e6d04961d028683d2226242c01d7397ab#diff-3bf8270d55d23189e202f3f0ebe97ec9fe5da6b77ba476327899cbeb9baf38ffR84) may be related, because when debugging if I add in runtime the ``traceFunctionAroundWrapper`` function everything goes back to normal.

Thank you for your time 🙇 

**Sample**
https://github.com/yelkolk/spring-cloud-function-sleuth-problem

**Comment by olegz** [comment]
Your issue is that FunctionAroundWrapper is a function and gets automatically picked up since there are no functional beans declared in your application. 
This has already been addressed on main (with new observability support in place of sleuth which is no longer supported), and I will ensure it doesn't happen in 3.2.x, but here is the question. . .
What does your application do if there are no beans? I mean yes you have demonstrated a bug but how realistic it is to cause a real problem in your application since it doesn't do anything?

**Comment by yelkolk** [comment]
Hi @olegz,

Thank you for your reply. The application I created for the demo does not do anything but our application does. It has no beans because it is a service that sends messages to Rabbit via Stream bridge from a rest request.

In any case, I wasn't aware that sleuth was deprecated in versions <3.0.0 🤔 

We'll take a look at the new observability to migrate, thank you.

**Comment by olegz** [comment]
No problem, I am fixing it anyway for 3.2 which we will release shortly
