### ISSUE TITLE
Add a fallback/default function to the rounting function.

### ISSUE THREAD

**Issue by thedep2** [spring-cloud/spring-cloud-function#958]
**Initial problem**

Hello.

In my company, we currently trying to use spring cloud stream to do asynchronous process with RabbitMQ. We currently doing some tests to try to find our best way to use.

We want to use the routing function to route a message from the queue inside an application. My  initial problem is the same if I use the function from definition or the function from expression.

I did some performance testing with message with `spring.cloud.function.definition` in the header. On my laptop I can handle around 500 messages per second. But if the producer send one message on two with a new definition which I don’t have in my application (i.e. I don’t implement the Function or the Consumer), my performance falls to 0.5 message per second. This is a huge lost.

This can be happen in the real life (we don't always handle the producer) and obviously this is not acceptable in production.

After an investigation it’s seems it is the system of retry which cause this lost of performance.

So I try with this custom retry template:

```
@StreamRetryTemplate
publicRetryTemplate myRetryTemplate() {
returnRetryTemplate.builder()
                        .maxAttempts(1)
                        .fixedBackoff(1)
                        .build();
}
```

And indeed, my performance seems to be the same than before (with a little lose, but acceptable)

And by using `spring.cloud.stream.default.error-handler-definition`, I can specify a business process of this kind of error. I’m ok with that.

But here, I’m overridding all my process of retry and I’m not happy with that. It's a workaround.

**Suggestion**
I suggest to add a property to the routing function, for example `spring.cloud.stream.function.routing.fallback` or `spring.cloud.stream.function.routing.default`, to specify a function when the router doesn’t find the specified one. It should work for the message header method and for the properties method.

So if the user wants, he can “short cut” the retry process by handling himself this problem.

**Context**
Tests done with:
- spring boot 2.7.4
- Java 17
- spring cloud 2021.0.4

I hope I don't miss something.

Thank you.

**Comment by olegz** [comment]
I am thinking along the lines of the following.
1. Let the framework have a default function which would effectively act as `dev/null`. This would simply drop/log an incoming message. This means that non-routing would not be considered an error as a default behavior.
2. Provide the ability for the user to identify which function should act as a default via some property as you suggested.

**Comment by olegz** [comment]
First i forgot to mention that you can already do it with [MessageRoutingCallback](https://docs.spring.io/spring-cloud-function/docs/current/reference/html/spring-cloud-function.html#_messageroutingcallback), where you can provide your own implementation routing and then simply return some default function name that you would pre-register if proper function can not be found.

That said, with this new feature you can simply register `DefaultMessageRoutingHandler` and the framework will fallback on it.
```
@Bean
public DefaultMessageRoutingHandler defaultRoutingHandler() {
	return new DefaultMessageRoutingHandler() {
		@Override
		public void accept(Message<?> message) {
			// do something really cool
		}
	};
}
```
