### ISSUE TITLE
Azure Spring Cloud Function - Validations

### ISSUE THREAD

**Issue by cslobodan** [spring-cloud/spring-cloud-function#977]
Idea is to come up with a middleware that validates the request after Azure Function is invoked or to just extend `FunctionInvoker` options when it comes to `handleRequest`.
Currently, `HttpRequestMessage<Optional<String>> request`  object can be used to manually inspect the request, validate the request body, request parameters, etc. before passing it to the Spring Cloud Function.
It would be great if, within Spring Cloud Function, we could just annotate that some parameter is required, similar to how we did it in Spring Boot APIs, e.g. `@RequestParam(required = true) String account` and of course to be able to validate that request body conforms to the defined model via `@Valid`.

I noticed there is one StackOverflow post that also talks about this feature: https://stackoverflow.com/questions/70285004/spring-cloud-function-bean-validation

**Comment by olegz** [comment]
This not related to Azure and is more generic and is duplicate to https://github.com/spring-cloud/spring-cloud-function/issues/1004

As you can see not in the top priority, so if anyone from the community want's to take a crack at it, we'll review the PR
