### ISSUE TITLE
spring.cloud.function.rsocket.enabled Boolean property in java.utils.Properties

### ISSUE THREAD

**Issue by mkluzacek** [spring-cloud/spring-cloud-function#978]
**Describe the bug**
Hello after migrating to spring boot 2.7 and spring cloud 3.2.5 there is a "system property" when calling `System.getProperties()` called `spring.cloud.function.rsocket.enabled` with Boolean value `false`. According to the `java.utils.Properties` docs the values should all be `String` - "The Properties class represents a persistent set of properties. The Properties can be saved to a stream or loaded from a stream. Each key and its corresponding value in the property list is a string."

Our problem is that we are using hazelcast library that goes through all the properties and tries to cast them to string as follows:
``` java
return properties.entrySet()
          .stream()
          .map(e -> new AbstractMap.SimpleEntry<>((String) e.getKey(), (String) e.getValue()))
          .filter(e -> e.getKey().startsWith(prefix))
          .collect(toMap(this::processKey, Map.Entry::getValue));
```
and it fails with `ClassCastException` thanks to it. I wasnt able to find to the property being set anywhere but according to the name i came to conclusion that it comes from spring-cloud-function.
I can workaround the problem by setting the property using `-Dspring.cloud.function.rsocket.enabled=false` but its kinda annoying.

**Sample**
Can be tested with:
``` java
@Test
  void testBooleanValue() {
    assertTrue(System.getProperties().containsKey("spring.cloud.function.rsocket.enabled"));
    assertTrue(!((Boolean) System.getProperties()
        .get("spring.cloud.function.rsocket.enabled")));
    assertThrows(
        ClassCastException.class, 
        () -> {
          String test = (String) System.getProperties().get("spring.cloud.function.rsocket.enabled");
        });
  }
```

**Comment by olegz** [comment]
It is actually fixed with https://github.com/spring-cloud/spring-cloud-stream/commit/38ce1f79d91b3d94e76b095e2014f9880fca8ddf in spring-cloud-stream which is the only place where this property is set as boolean. It is also back-ported to 4.0.x and 3.2.x
