### ISSUE TITLE
How to specify response headers for AWS ALB response?

### ISSUE THREAD

**Issue by 34875634567** [spring-cloud/spring-cloud-function#986]
**Describe the bug**

We're using the AWS adaptor, and want to manually control the details of the ALB response: the status code, payload, headers etc. 
We previously had this working with a function of type:

```
Message<byte[]> apply(Mono<ApplicationLoadBalancerRequestEvent> event) {
```
This resulted in the function returning a well-formed ALB response JSON object with the contents we expected:

```
{
  "statusCode": 200,
  "headers": {
    "connection": "close",
    "content-type": "application/xml;charset=UTF-8",
    "date": "Mon, 16 Jan 2023 15:17:21 GMT",
    "server": "envoy",
    "transfer-encoding": "chunked",
    "x-envoy-upstream-service-time": "2061"
  },
  "body": "<redacted plain text string>"
}
```

However, we upgraded spring-cloud-function from https://github.com/spring-cloud/spring-cloud-function/compare/v3.2.6...v3.2.7, and now our response now has additional headers and a base64-encoded body:

```
{
  "isBase64Encoded": false,
  "headers": {
    "content-type": "application/xml;charset=UTF-8",
    "contentType": "application/json",
    "date": "Thu, 12 Jan 2023 14:37:55 GMT",
    "id": "81e9c32b-a7bc-3879-7895-535cbe39af08",
    "server": "envoy",
    "timestamp": "1673534274893",
    "transfer-encoding": "chunked",
    "x-envoy-upstream-service-time": "65",
    "x-source": "adaptor"
  },
  "body": "<redacted base64 string>",
  "statusCode": 200
}
``` 
Note the mismatch of `isBase64Encoded` and `body` fields. 

We were wondering if these changes were intentional, and whether our use-case (manually controlled response contents) is still supported?
If so, how should we be doing this?

Thanks in advance for your help.

**Comment by olegz** [comment]
This could be a regression. Can you please provide a sample of `ApplicationLoadBalancerRequestEvent` you are sending (JSON view of it)

**Comment by 34875634567** [comment]
Sure, this is taken from cloudwatch logs, so should be to spec:

```json
{
    "requestContext": {
        "elb": {
            "targetGroupArn": "arn:aws:elasticloadbalancing:eu-west-2:123456789012:targetgroup/Redacted/000000000000"
        }
    },
    "httpMethod": "POST",
    "path": "/redacted/path",
    "queryStringParameters": {},
    "headers": {
        "accept": "*/*",
        "content-length": "3773",
        "content-type": "application/xml",
        "host": "redacted.com",
        "user-agent": "insomnia/2022.7.1",
        "x-amzn-trace-id": "Root=1-63c68ccc-362800af6c39d63344f6954b",
        "x-forwarded-for": "1.2.3.4",
        "x-forwarded-port": "443",
        "x-forwarded-proto": "https"
    },
    "body": "[redacted]",
    "isBase64Encoded": false
}
```

**Comment by olegz** [comment]
Thank you, yes this is regression. For now you can use `ApplicationLoadBalancerRequestEvent` instead ( in know not ideal), but I will push a fix today and we have releases coming up this month

**Comment by olegz** [comment]
Ok, snapshot is available, please give it a try and let us know
