### ISSUE TITLE
AWS Context is coming as null [message.getHeaders().get("aws-context", Context.class)]

### ISSUE THREAD

**Issue by nbenjamin** [spring-cloud/spring-cloud-function#997]
**Describe the bug**
Version 
Spring-cloud-function-adapter-aws - 3.2.4

AWS Context is coming as null from header. As mentioned in the document application was expecting context from Message header.

ex: 
```java

public class ServicenameFunction implements
    Function<Message<ApplicationLoadBalancerRequestEvent>, ApplicationLoadBalancerResponseEvent> {

  public ApplicationLoadBalancerResponseEvent apply(
      Message<ApplicationLoadBalancerRequestEvent> message) {
    var context = message.getHeaders().get("aws-context", Context.class);

  // context is coming as null
  }
}

```

**Comment by nbenjamin** [comment]
@olegz  - Could you please check this above issue?

**Comment by olegz** [comment]
Yes indeed it's not coming. Will fix

**Comment by olegz** [comment]
Changing it to task to add a test vaidating that this is not an issue with the latest version
